### ISSUE TITLE
NodeManager trying to start Server from other container in single host clustered env

### ISSUE THREAD

**Issue by ranjankhanna** [oracle/docker-images#1045]
I have created a docker image from 12213-domain. Below is my scenario
1. Multiple containers on Single host in clustered environment.
2. Volume mapping is done using "-v my-vol:/u01/oracle/user_projects" docker option in AdminServer and "--volumes-from wlsadmin" in Managed Servers. 
3. Total of 3 containers(running on same host):
i) Admin Server + Node Manager running
ii) ManagedServer name MS1 and Node Manager (starting using createServer.sh)
iii) ManagedServer name MS2 and Node Manager (started using createServer.sh)

AdminServer and MS1 starts correctly without any exceptions/errors.  MS2 also starts up correctly but as soon as Node Manager is started on MS2, i am start getting following errors on MS1

<Nov 6, 2018 11:07:53 PM UTC> <Info> <Management> <BEA-141297> <Could not get the server file lock. Ensure that another server is not running in the same directory. Retrying for another 60 seconds.>

weblogic.management.ManagementException: Unable to obtain lock on /u01/oracle/user_projects/domains/base_domain/servers/MS1/tmp/MS1.lok. Server may already be running
        at weblogic.management.internal.ServerLocks.getServerLock(ServerLocks.java:219)
        at weblogic.management.internal.ServerLocks.getServerLock(ServerLocks.java:73)
        at weblogic.management.internal.DomainDirectoryService.start(DomainDirectoryService.java:98)
        at weblogic.server.AbstractServerService.postConstruct(AbstractServerService.java:76)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)

It seems like node manager on MS2 is also trying to start MS1. The nodemanager of MS2 should not try to start MS1 instance.

**Comment by ranjankhanna** [comment]
I was able to resolve the issue by  adding "DomainsDirRemoteSharingEnabled" in nodemanager.properties file of all the node managers. 
As a permanent fix, i modified 
."./docker-images/OracleWebLogic/samples/12213-domain/container-scripts/create-wls-domain.py"
and add following line while(in node manager properties section) 
set('DomainsDirRemoteSharingEnabled','true')

This resolved the issue.

**Comment by mriccell** [comment]
@ranjankhanna  thanks for your suggestion I will make the change.
