### ISSUE TITLE
Oracle GoldenGate Docker Image fails when running

### ISSUE THREAD

**Issue by alesana-san** [oracle/docker-images#1226]
Hi!

I build my `Oracle GoldenGate` image as follows:
`````
docker build --build-arg BASE_IMAGE="container-registry.oracle.com/database/instantclient"                
			 --build-arg OGG_VERSION="12.3.0.1.4"                
			 --build-arg OGG_EDITION="microservices"                
			 --build-arg OGG_TARFILE="123014_fbo_ggs_Linux_x64_services_shiphome.tar"                
			 --tag oracle/goldengate-microservices:12.3.0.1.4 --no-cache .
`````
Then I run it with a command:
`````
docker run \
    --cap-add SYS_RESOURCE \
    -v T:/docker-data/ogg/conf:/u02/ogg/Local/etc/conf \
	-v T:/docker-data/ogg/trail:/u02/ogg/Local/var/lib/data \
	-p 443:443 \
    oracle/goldengate-microservices:12.3.0.1.4
`````
But after running I get the following errors in the output:
`````
2019-04-11T18:35:18.240Z | INFO    | /u01/app/ogg/bin/adminsrvr: error while loading shared libraries: libnnz11.so: cannot open shared object file: No such file or directory
2019-04-11T18:35:18.243Z | INFO    | Process exit value: 127
2019-04-11T18:35:18.244Z | SEVERE  | Error code: 127
2019-04-11T18:35:18.245Z | SEVERE  | Error(s) ocurred, please check log files.
2019-04-11T18:35:18.247Z | SEVERE  | Failed to import admin user.
2019-04-11T18:35:18.248Z | SEVERE  | Unable to import users.
2019-04-11T18:35:18.250Z | SEVERE  | Deployment (ServiceManager) creation failed. Check log file(s).
`````
`````
2019-04-11T18:35:20.649Z | SEVERE  | (1) Errors ocurred when removing deployment: 'Local'.
Service Manager is terminating because it cannot load the inventory from '/u02/ogg/ServiceManager/etc/conf/deploymentRegistry.dat'
Password: Apr 11, 2019 6:35:21 PM ogg.RestCall issueReport
SEVERE: > GET http://127.0.0.1:9100/ogg HTTP/1.1
Apr 11, 2019 6:35:21 PM ogg.RestCall issueReport
SEVERE: > Accept-Charset: UTF-8
Apr 11, 2019 6:35:21 PM ogg.RestCall issueReport
SEVERE: > Accept: application/json
Apr 11, 2019 6:35:21 PM ogg.RestCall issueReport
SEVERE: > Content-Type: application/json
Apr 11, 2019 6:35:21 PM ogg.RestCall issueReport
SEVERE: >
Apr 11, 2019 6:35:21 PM ogg.RestCall execute
WARNING: REST API call failed - Connection refused (Connection refused)
`````
And finally:
`````
SEVERE: >
Apr 11, 2019 6:35:26 PM ogg.RestCallException logException
SEVERE: Rest call exception: Connection failed for URL 'http://127.0.0.1:9100/ogg' - Connection refused (Connection refused)
java.net.ConnectException: Connection refused (Connection refused)
        at java.net.PlainSocketImpl.socketConnect(Native Method)
        at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
        at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
        at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
        at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
        at java.net.Socket.connect(Socket.java:589)
        at java.net.Socket.connect(Socket.java:538)
        at sun.net.NetworkClient.doConnect(NetworkClient.java:180)
        at sun.net.www.http.HttpClient.openServer(HttpClient.java:463)
        at sun.net.www.http.HttpClient.openServer(HttpClient.java:558)
        at sun.net.www.http.HttpClient.<init>(HttpClient.java:242)
        at sun.net.www.http.HttpClient.New(HttpClient.java:339)
        at sun.net.www.http.HttpClient.New(HttpClient.java:357)
        at sun.net.www.protocol.http.HttpURLConnection.getNewHttpClient(HttpURLConnection.java:1220)
        at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1156)
        at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1050)
        at sun.net.www.protocol.http.HttpURLConnection.connect(HttpURLConnection.java:984)
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1564)
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1492)
        at java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:480)
        at ogg.RestCall.makeCall(RestCall.java:118)
        at ogg.RestCall.execute(RestCall.java:55)
        at ServiceManager.GET(ServiceManager.java:57)
        at ServiceManager.<init>(ServiceManager.java:36)
        at Main.main(Main.java:24)

Error - Connection failed for URL 'http://127.0.0.1:9100/ogg' - Connection refused (Connection refused)
`````
Note that the image already has `libnnz12.so` but not `libnnz11.so`
`````
bash-4.2# find / -name "libnnz*"
/usr/lib/oracle/12.2/client64/lib/libnnz12.so
`````
My Docker version:
`````
$ docker version
Client: Docker Engine - Community
 Version:           18.09.1
 API version:       1.39
 Go version:        go1.10.6
 Git commit:        4c52b90
 Built:             Wed Jan  9 19:34:26 2019
 OS/Arch:           windows/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          18.09.1
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.10.6
  Git commit:       4c52b90
  Built:            Wed Jan  9 19:41:49 2019
  OS/Arch:          linux/amd64
  Experimental:     false
`````
OS: `Windows 10`

TAR-file was built manually as it described here: https://github.com/oracle/docker-images/tree/master/OracleGoldenGate
I used `Oracle GoldenGate 12.3.0.1.4 Microservices for Oracle on Linux x86-64` version from OTN

**Comment by sbalousek** [comment]
Hi @alesana-san,

The problem here is a mismatch of Oracle GoldenGate target database and the Oracle Instant Client library version.

In your example, the OGG database is version is 11g, but the instant client libraries are for 12c.  It looks like you extracted the 'filegroup1.jar' for Oracle 11g instead of the one for Oracle 12c.

- Steve

**Comment by alesana-san** [comment]
@sbalousek great thanks! It was such a silly mistake.
