### ISSUE TITLE
there is no 12213 jdbc config, where can i get it ?

### ISSUE THREAD

**Issue by willzhang** [oracle/docker-images#1242]
can i use the follow config for 12213:
```
docker-images/OracleWebLogic/samples/1221-domain-with-resources/
```

**Comment by mriccell** [comment]
In the process of removing the unsupported samples I will create new ones based on 12213.

**Comment by mriccell** [comment]
yes you can use this sample just make sure you extend (FROM) the 12.2.1.3 image

**Comment by willzhang** [comment]
### i got issues, maybe i should change wlst to wlst.sh
```
[root@localhost 1221-domain-with-resources]# sh build.sh 
Sending build context to Docker daemon  15.36kB
Step 1/4 : FROM oracle/weblogic:12.2.1.3-generic
 ---> 3b7136ac09fa
Step 2/4 : MAINTAINER Monica Riccelli <monica.riccelli@oracle.com>
 ---> Running in fc1804d7f217
Removing intermediate container fc1804d7f217
 ---> ee02563578a6
Step 3/4 : COPY container-scripts/* /u01/oracle/
 ---> 837e05bfc01a
Step 4/4 : RUN wlst -loadProperties /u01/oracle/datasource.properties /u01/oracle/ds-deploy.py &&     wlst /u01/oracle/jms-deploy.py
 ---> Running in a2e68a41002c
/bin/sh: wlst: command not found
The command '/bin/sh -c wlst -loadProperties /u01/oracle/datasource.properties /u01/oracle/ds-deploy.py &&     wlst /u01/oracle/jms-deploy.py' returned a non-zero code: 127
```
### then i get error again
```
[root@localhost 1221-domain-with-resources]# sh build.sh 
Sending build context to Docker daemon  15.36kB
Step 1/4 : FROM oracle/weblogic:12.2.1.3-generic
 ---> 3b7136ac09fa
Step 2/4 : MAINTAINER Monica Riccelli <monica.riccelli@oracle.com>
 ---> Using cache
 ---> ee02563578a6
Step 3/4 : COPY container-scripts/* /u01/oracle/
 ---> Using cache
 ---> 837e05bfc01a
Step 4/4 : RUN wlst.sh -loadProperties /u01/oracle/datasource.properties /u01/oracle/ds-deploy.py &&     wlst.sh /u01/oracle/jms-deploy.py
 ---> Running in 2022fb0ca3bf

Initializing WebLogic Scripting Tool (WLST) ...

Jython scans all the jar files it can find at first startup. Depending on the system, this process may take a few minutes to complete, and WLST may not return a prompt right away.

Welcome to WebLogic Server Administration Scripting Shell

Type help() for help on available commands

Error: runCmd() failed. Do dumpStack() to see details.
Problem invoking WLST - Traceback (innermost last):
  File "/u01/oracle/ds-deploy.py", line 19, in ?
  File "/tmp/WLSTOfflineIni6611239058251446014.py", line 131, in readDomain
  File "/tmp/WLSTOfflineIni6611239058251446014.py", line 19, in command
The domain directory must exist and contain config/config.xml
        at com.oracle.cie.domain.script.jython.CommandExceptionHandler.handleException(CommandExceptionHandler.java:69)
        at com.oracle.cie.domain.script.jython.WLScriptContext.handleException(WLScriptContext.java:2983)
        at com.oracle.cie.domain.script.jython.WLScriptContext.runCmd(WLScriptContext.java:735)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)

com.oracle.cie.domain.script.jython.WLSTException: com.oracle.cie.domain.script.jython.WLSTException: Error reading domain: 
The domain directory must exist and contain config/config.xml

The command '/bin/sh -c wlst.sh -loadProperties /u01/oracle/datasource.properties /u01/oracle/ds-deploy.py &&     wlst.sh /u01/oracle/jms-deploy.py' returned a non-zero code: 1
[root@localhost 1221-domain-with-resources]# 
```

**Comment by willzhang** [comment]
i build 12.2.1.3 use the follow command,and i  access the console success
```
sh buildDockerImage.sh -v 12.2.1.3 -g
```
is it that when i create jdbc ,i should keep  the weblogic server in running  state?

or is there a script for me to create jdbc，i want the jdbc be ready before i start the container ,because i want use the images in cicd

**Comment by mriccell** [comment]
Building the 12.2.1.3 WebLogic image only creates the binary image of WebLogic.  What kind of domain do you need  we have 2 samples the "single server domain" and the domain with an admin server, wls cluster, and x number of managed servers.  Which model do you need?  If it is the second then the next step is to create the WebLogic domain configuration.  We support 2 models of where the domain home is persisted 1) inside of an image 2) in a host volume.  Which of these two models are you interested in?

**Comment by willzhang** [comment]
i just want a single adminserver and a jdbc config

**Comment by mriccell** [comment]
What you need to do is change the wlst script in https://github.com/oracle/docker-images/blob/master/OracleWebLogic/dockerfiles/12.2.1.3/container-scripts/create-wls-domain.py to include the data source creation code in https://github.com/oracle/docker-images/blob/master/OracleWebLogic/samples/1221-domain-with-resources/container-scripts/ds-deploy.py make sure to set the properties like in https://github.com/oracle/docker-images/blob/master/OracleWebLogic/samples/1221-domain-with-resources/container-scripts/datasource.properties adjusted to the database you will connect to.

**Comment by willzhang** [comment]
i find i must build domain and datasource together, is there have a way divide this two step?
as above ,you will get the error "The domain directory must exist and contain config/config.xml"

**Comment by mriccell** [comment]
Yes you can use one WLST script or use two one to configure the domain alone and then one to configure the datasource.  After you have the store/oracle/weblogic:12.2.1.3  extend it and write a WLST script that configures the datasource with WLST online during the Docker build.  Look at the sample https://github.com/oracle/docker-images/tree/master/OracleWebLogic/samples/12212-domain-online-config.
Monica

**Comment by mriccell** [comment]
@willzhang Do you still have questions or issues?

**Comment by willzhang** [comment]
yes, before i deploy my app, sometime i just need one jndi datasource ,but sometimes i must run two or more jndi datasource for the app, how can i do that when i don't want to build another docker images?

**Comment by mriccell** [comment]
The Operator doesn’t provide a way to add new resource modules (such as Datasources or JMS Modules); instead, you can create 'skeleton' modules in your original configuration and then use overrides to alter the existing modules. 

For example, you can configure a skeleton datasource with a min-pool-size to 0 and its driver set to valid values, but its other values invalid - such as username and password.  This allows the datasource to start without errors at runtime even if no overrides are specified, but ensures the datasource cannot be accidentally used at runtime without overrides that are correct for the current environment.

When you are ready to use the datasource you can do a config override to set the valid values.

**Comment by mriccell** [comment]
please take a look at the newly created sample OracleWebLogic/samples/12213-deploy-application.

**Comment by willzhang** [comment]
thanks,the file help me:
docker-images/OracleWebLogic/samples/1221-domain-with-resources/container-scripts/ds-deploy.py

**Comment by willzhang** [comment]
close the issue，thanks
