### ISSUE TITLE
WebLogic error during domain configuration phase

### ISSUE THREAD

**Issue by AnkurRaj** [oracle/docker-images#1484]

**Comment by rjeberhard** [comment]
@AnkurRaj, we need more information.

**Comment by AnkurRaj** [comment]
Domain Configuration Phase
==========================

Initializing WebLogic Scripting Tool (WLST) ...

Welcome to WebLogic Server Administration Scripting Shell

Type help() for help on available commands

Creating Servers...
Configuring SSL for app_ms_1
Configuring SSL for AdminServer
Writing base domain...
Base domain created at /u01/oracle/user_projects/domains/pdc_domain
Extending domain at /u01/oracle/user_projects/domains/pdc_domain
Applying JRF templates...
Extension Templates added
Configuring the Service Table DataSource...
Getting Database Defaults...
Error: getDatabaseDefaults() failed. Do dumpStack() to see details.
Error: runCmd() failed. Do dumpStack() to see details.
Problem invoking WLST - Traceback (innermost last):
  File "/u02/container-scripts/create-jrf-domain.py", line 282, in ?
  File "/u02/container-scripts/create-jrf-domain.py", line 130, in createJRFDomain
  File "/u02/container-scripts/create-jrf-domain.py", line 205, in extendDomain
  File "/tmp/WLSTOfflineIni8429327948441902873.py", line 263, in getDatabaseDefaults
  File "/tmp/WLSTOfflineIni8429327948441902873.py", line 19, in command
Failed to build JDBC Connection object:
        at com.oracle.cie.domain.script.jython.CommandExceptionHandler.handleException(CommandExceptionHandler.java:69)
        at com.oracle.cie.domain.script.jython.WLScriptContext.handleException(WLScriptContext.java:2983)
        at com.oracle.cie.domain.script.jython.WLScriptContext.runCmd(WLScriptContext.java:735)
        at sun.reflect.GeneratedMethodAccessor153.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)

com.oracle.cie.domain.script.jython.WLSTException: com.oracle.cie.domain.script.jython.WLSTException: Got exception when auto configuring the schema component(s) with data obtained from shadow table:
Failed to build JDBC Connection object:

Domain Creation Failed (return code= 1)
Domain check failed

**Comment by Djelibeybi** [comment]
That's not more information, that's just more output. If you want assistance, please provide more contenxt, i.e. what were you trying to do? What image are you using? How did you build it? What did you expect would happen? What actually happened? What are the steps to reproduce the issue?
