### ISSUE TITLE
error occurred while executing this line: /u01/oracle/wlserver/samples/server/medrec/install/common/build.xml:27: Java returned: 1

### ISSUE THREAD

**Issue by douglas-man** [oracle/docker-images#151]
updating with more concise  error log... (looks like I have a log-In Issue ..)

```
 [java] WLST-WLS-1472479103433: <Aug 29, 2016 1:59:44 PM UTC> <Notice> <Security> <BEA-090946> <Security pre-initializing using security realm: myrealm> 
 [java] java.io.IOException: Stream closed
 [java]     at java.io.BufferedInputStream.getBufIfOpen(BufferedInputStream.java:170)
 [java]     at java.io.BufferedInputStream.read1(BufferedInputStream.java:283)
 [java]     at java.io.BufferedInputStream.read(BufferedInputStream.java:345)
 [java]     at sun.nio.cs.StreamDecoder.readBytes(StreamDecoder.java:284)
 [java]     at sun.nio.cs.StreamDecoder.implRead(StreamDecoder.java:326)
 [java]     at sun.nio.cs.StreamDecoder.read(StreamDecoder.java:178)
 [java]     at java.io.InputStreamReader.read(InputStreamReader.java:184)
 [java]     at java.io.BufferedReader.fill(BufferedReader.java:161)
 [java]     at java.io.BufferedReader.readLine(BufferedReader.java:324)
 [java]     at java.io.BufferedReader.readLine(BufferedReader.java:389)
 [java]     at weblogic.management.scripting.utils.WLSTProcess.run(WLSTProcess.java:82)
 [java]     at java.lang.Thread.run(Thread.java:745)
 [java] Problem invoking WLST - Traceback (innermost last):
 [java]   File "/u01/oracle/wlserver/samples/server/medrec/install/common/startAdminServer.py", line 11, in ?
 [java]   File "<iostream>", line 366, in startServer
 [java]   File "<iostream>", line 553, in raiseWLSTException
 [java] WLSTException: Error occurred while performing startServer : Could not start the server, the process might have timed out or there is an Error starting the server. Please refer to the log files for more details.
 [java] 
 [java] .............Could not connect to the server to verify that it has started. The error returned is: javax.naming.CommunicationException: t3://localhost:7001: [RJVM:000575]Destination 0:0:0:0:0:0:0:1, 7001 unreachable.; nested exception is: 
 [java]     java.net.ConnectException: Connection refused; [RJVM:000576]No available router to destination.; nested exception is
```

downloaded this ..

fmw_12.2.1.0.0_wls_supplemental_quick_Disk1_1of1

and
running....

/1221-medrec$ docker run -ti -p 7001:7001 1221-medrec

as the last step beginning with README... 

```
    $ cd OracleJDK/java-8
    $ sh build.sh
```

 $ sh buildDockerImage.sh -v 12.2.1 -d

...
....

but gets this...

```
 [java] WLST-WLS-1472232376962: <Aug 26, 2016 5:26:18 PM UTC> <Info> <RCM> <BEA-2165021> <"ResourceManagement" is not enabled in this JVM. Enable "ResourceManagement" to use the WebLogic Server "Resource Consumption Management" feature. To enable "ResourceManagement", you must specify the following JVM options in the WebLogic Server instance in which the JVM runs: -XX:+UnlockCommercialFeatures -XX:+ResourceManagement.> 
 [java] WLST-WLS-1472232376962: <Aug 26, 2016 5:26:18 PM UTC> <Info> <Management> <BEA-141107> <Version: WebLogic Server 12.2.1.0.0 Tue Oct  6 10:05:47 PDT 2015 1721936> 
 [java] java.io.IOException: Stream closed
 [java]     at java.io.BufferedInputStream.getBufIfOpen(BufferedInputStream.java:170)
 [java]     at java.io.BufferedInputStream.read1(BufferedInputStream.java:283)
 [java]     at java.io.BufferedInputStream.read(BufferedInputStream.java:345)
 [java]     at sun.nio.cs.StreamDecoder.readBytes(StreamDecoder.java:284)
 [java]     at sun.nio.cs.StreamDecoder.implRead(StreamDecoder.java:326)
 [java]     at sun.nio.cs.StreamDecoder.read(StreamDecoder.java:178)
 [java]     at java.io.InputStreamReader.read(InputStreamReader.java:184)
 [java]     at java.io.BufferedReader.fill(BufferedReader.java:161)
 [java]     at java.io.BufferedReader.readLine(BufferedReader.java:324)
 [java]     at java.io.BufferedReader.readLine(BufferedReader.java:389)
 [java]     at weblogic.management.scripting.utils.WLSTProcess.run(WLSTProcess.java:82)
 [java]     at java.lang.Thread.run(Thread.java:745)
 [java] .................................Could not connect to the server to verify that it has started. The error returned is: javax.naming.CommunicationException: t3://localhost:7001: [RJVM:000575]Destination 0:0:0:0:0:0:0:1, 7001 unreachable.; nested exception is: 
 [java]     java.net.ConnectException: Connection refused; [RJVM:000576]No available router to destination.; nested exception is: 
 [java]     java.rmi.ConnectException: [RJVM:000576]No available router to destination. [Root exception is java.net.ConnectException: t3://localhost:7001: [RJVM:000575]Destination 0:0:0:0:0:0:0:1, 7001 unreachable.; nested exception is: 
 [java]     java.net.ConnectException: Connection refused; [RJVM:000576]No available router to destination.; nested exception is: 
 [java]     java.rmi.ConnectException: [RJVM:000576]No available router to destination.]
 [java] WLST-WLS-1472232376962: IOException when running WLSTProcess
 [java] WLST-WLS-1472232376962: Stopped draining WLST-WLS-1472232376962
 [java] No stack trace available.
 [java] Problem invoking WLST - Traceback (innermost last):
 [java]   File "/u01/oracle/wlserver/samples/server/medrec/install/common/startAdminServer.py", line 11, in ?
 [java]   File "<iostream>", line 366, in startServer
 [java]   File "<iostream>", line 553, in raiseWLSTException
 [java] WLSTException: Error occurred while performing startServer : Could not start the server, the process might have timed out or there is an Error starting the server. Please refer to the log files for more details.
 [java] 
```

BUILD FAILED
/u01/oracle/wlserver/samples/server/medrec/build.xml:27: The following error occurred while executing this line:
/u01/oracle/wlserver/samples/server/medrec/install/build.xml:10: The following error occurred while executing this line:
/u01/oracle/wlserver/samples/server/medrec/install/non-mt-single-server/build.xml:21: The following error occurred while executing this line:
/u01/oracle/wlserver/samples/server/medrec/install/non-mt-single-server/build.xml:39: The following error occurred while executing this line:
/u01/oracle/wlserver/samples/server/medrec/install/common/build.xml:27: Java returned: 1

**Comment by jeroendewolf** [comment]
I have the same problem with the medrec sample. The process of running the medrec container appears to hang during domain write, but after a little while, killing it with ctrl-c results in this stack trace.

**Comment by brunoborges** [comment]
@mriccell, Monica, could you review this please?

**Comment by mriccell** [comment]
Could you please try with the 12.2.1.1 or 12.2.1.2 medrec sample?

**Comment by brunoborges** [comment]
@jeroendewolf, mind to test 12.2.1.1 or 12.2.1.2 medrec sample that Monica added recently to the samples folder?

**Comment by jeroendewolf** [comment]
I will take a look at it. Currently I have a bigger problem ...the oracle maven repo seems to have problems...cant get my application to work. It used to work however.

Outlook voor Android<https://aka.ms/ghei36> downloaden



On Wed, Oct 26, 2016 at 9:07 PM +0200, "Bruno Borges" <notifications@github.com<mailto:notifications@github.com>> wrote:


@jeroendewolf<https://github.com/jeroendewolf>, mind to test 12.2.1.1 or 12.2.1.2 medrec sample that Monica added recently to the samples folder?

-

**Comment by mriccell** [comment]
@jeroendewolf have you had a chance to try on 12.2.1.1 or 12.2.1.2 medrec sample?

**Comment by mriccell** [comment]
Closing issue due to lack of feedback
