### ISSUE TITLE
Sample 12213-domain-with-resource error

### ISSUE THREAD

**Issue by Z-EMB** [oracle/docker-images#1646]
`./build.sh` on linux results in below.

```
12213-domain-with-resources$ ./build.sh 
Sending build context to Docker daemon  15.87kB
Step 1/4 : FROM 12213-weblogic-domain-in-volume
 ---> 1eb09361ac1e
Step 2/4 : MAINTAINER Monica Riccelli <monica.riccelli@oracle.com>
 ---> Using cache
 ---> dc7c8ac020c9
Step 3/4 : COPY container-scripts/* /u01/oracle/
 ---> 70b0938cfb0d
Step 4/4 : RUN wlst -loadProperties /u01/oracle/datasource.properties /u01/oracle/ds-deploy.py &&     wlst /u01/oracle/jms-deploy.py
 ---> Running in 55ae0c1c2945

Initializing WebLogic Scripting Tool (WLST) ...

Welcome to WebLogic Server Administration Scripting Shell

Type help() for help on available commands

Error: runCmd() failed. Do dumpStack() to see details.
Problem invoking WLST - Traceback (innermost last):
  File "/u01/oracle/ds-deploy.py", line 19, in ?
  File "/tmp/WLSTOfflineIni1540186262229217057.py", line 131, in readDomain
  File "/tmp/WLSTOfflineIni1540186262229217057.py", line 19, in command
The domain directory must exist and contain config/config.xml
        at com.oracle.cie.domain.script.jython.CommandExceptionHandler.handleException(CommandExceptionHandler.java:69)
        at com.oracle.cie.domain.script.jython.WLScriptContext.handleException(WLScriptContext.java:2983)
        at com.oracle.cie.domain.script.jython.WLScriptContext.runCmd(WLScriptContext.java:735)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)

com.oracle.cie.domain.script.jython.WLSTException: com.oracle.cie.domain.script.jython.WLSTException: Error reading domain: 
The domain directory must exist and contain config/config.xml

The command '/bin/sh -c wlst -loadProperties /u01/oracle/datasource.properties /u01/oracle/ds-deploy.py &&     wlst /u01/oracle/jms-deploy.py' returned a non-zero code: 1

```

On windows it doesn't even get this far, crashes with below. Have to change `wlst` to `wlst.sh -skipWLSModuleScanning` (as intended by wlst in the first place. After the "fix" it results in the same error as above.

```
Step 4/4 : RUN wlst -loadProperties /u01/oracle/datasource.properties /u01/oracle/ds-deploy.py &&     wlst /u01/oracle/jms-deploy.py
/bin/sh: /u01/oracle/container-scripts/wlst: /bin/sh^M: bad interpreter: No such file or directory
```

**Comment by Djelibeybi** [comment]
Is this still an issue?

**Comment by mriccell** [comment]
@Z-EMB  You need to first build a domain follow example https://github.com/oracle/docker-images/tree/master/OracleWebLogic/samples/12213-domain this builds an image called 12213-weblogic-domain-in-volume with a WLS domain and then this sample extends this image and deploys resources.

**Comment by dabicho** [comment]
Does it really work that way?
As far as I understand from the sources , the domain is built when the container is run for the first time (this is done that way so the domain can reside on a volume, hence the image name 12213-weblogic-domain-in-volume ), so it wouldn't exist when building the image.

So the createWLSDomain.sh from the parent image should be replaced with one that runs the ds and jms scripts after creating the domain, instead of creating the jms and ds on the Dockerfile.
That could work with if the docker inherited [https://github.com/oracle/docker-images/tree/main/OracleWebLogic/samples/12213-domain-home-in-image](https://github.com/oracle/docker-images/tree/main/OracleWebLogic/samples/12213-domain-home-in-image) instead
