### ISSUE TITLE
WebLogicServer_DemoIdentity.jks

### ISSUE THREAD

**Issue by senthil83p** [oracle/docker-images#1659]
WebLogicServer 12.2.1.3 

<WebLogicServer> <BEA-000297> Inconsistent security configuration, weblogic.management.configuration.ConfigurationException: Cannot find identity keystore file /u01/oracle/user_projects/domains/docker_domain/security/DemoIdentity.jks on server AdminServer

logs..
<Error> <WebLogicServer> <BEA-000297> <Inconsistent security configuration, weblogic.management.configuration.ConfigurationException: Cannot find identity keystore file /u01/oracle/user_projects/domains/docker_domain/security/DemoIdentity.jks on server AdminServer> 
<Jul 15, 2020 6:50:04,730 PM IST> <Emergency> <Security> <BEA-090034> <Not listening for SSL, weblogic.management.configuration.ConfigurationException: Cannot find identity keystore file /u01/oracle/user_projects/domains/docker_domain/security/DemoIdentity.jks on server AdminServer.> 
<Jul 15, 2020 6:50:04,780 PM IST> <Notice> <Security> <BEA-090946> <Security pre-initializing using security realm: myrealm> 
<Jul 15, 2020 6:50:05,274 PM IST> <Notice> <Security> <BEA-090947> <Security post-initializing using security realm: myrealm> 
<Jul 15, 2020 6:50:06,193 PM IST> <Notice> <Security> <BEA-090082> <Security initialized using administrative security realm: myrealm> 
<Jul 15, 2020 6:50:06,234 PM IST> <Notice> <Security> <BEA-090083> <Storing boot identity in the file: /u01/oracle/user_projects/domains/docker_domain/servers/AdminServer/security/boot.properties.> 
<Jul 15, 2020 6:50:06,812 PM IST> <Notice> <JMX> <BEA-149512> <JMX Connector Server started at service:jmx:iiop://172.17.0.2:9002/jndi/weblogic.management.mbeanservers.runtime.> 
<Jul 15, 2020 6:50:06,838 PM IST> <Warning> <JMX> <BEA-149513> <JMX Connector Server stopped at service:jmx:iiop://172.17.0.2:9002/jndi/weblogic.management.mbeanservers.runtime.> 
<Jul 15, 2020 6:50:06,842 PM IST> <Critical> <WebLogicServer> <BEA-000362> <Server failed. Reason: 

There are 1 nested errors:

java.io.IOException: [Server:002664]Failed to start Admin Channel DefaultAdministration[admin].
	at weblogic.server.channels.ServerSocketManager.createAndBindServerSockets(ServerSocketManager.java:132)
	at weblogic.server.channels.ServerSocketManager.createAndBindAllServerSockets(ServerSocketManager.java:89)
	at weblogic.server.channels.AdminPortService.createAndBindServerSockets(AdminPortService.java:108)
	at weblogic.server.channels.EnableAdminListenersService.start(EnableAdminListenersService.java:60)
	at weblogic.server.AbstractServerService.postConstruct(AbstractServerService.java:76)
	at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.glassfish.hk2.utilities.reflection.ReflectionHelper.invoke(ReflectionHelper.java:1287)
	at org.jvnet.hk2.internal.ClazzCreator.postConstructMe(ClazzCreator.java:333)
	at org.jvnet.hk2.internal.ClazzCreator.create(ClazzCreator.java:375)
	at org.jvnet.hk2.internal.SystemDescriptor.create(SystemDescriptor.java:487)
	at org.glassfish.hk2.runlevel.internal.AsyncRunLevelContext.findOrCreate(AsyncRunLevelContext.java:305)
	at org.glassfish.hk2.runlevel.RunLevelContext.findOrCreate(RunLevelContext.java:85)
	at org.jvnet.hk2.internal.Utilities.createService(Utilities.java:2126)
	at org.jvnet.hk2.internal.ServiceHandleImpl.getService(ServiceHandleImpl.java:116)
	at org.jvnet.hk2.internal.ServiceHandleImpl.getService(ServiceHandleImpl.java:90)
	at org.glassfish.hk2.runlevel.internal.CurrentTaskFuture$QueueRunner.oneJob(CurrentTaskFuture.java:1237)
	at org.glassfish.hk2.runlevel.internal.CurrentTaskFuture$QueueRunner.run(CurrentTaskFuture.java:1168)
	at weblogic.work.SelfTuningWorkManagerImpl$WorkAdapterImpl.run(SelfTuningWorkManagerImpl.java:670)
	at weblogic.invocation.ComponentInvocationContextManager._runAs(ComponentInvocationContextManager.java:352)
	at weblogic.invocation.ComponentInvocationContextManager.runAs(ComponentInvocationContextManager.java:337)
	at weblogic.work.LivePartitionUtility.doRunWorkUnderContext(LivePartitionUtility.java:57)
	at weblogic.work.PartitionUtility.runWorkUnderContext(PartitionUtility.java:41)
	at weblogic.work.SelfTuningWorkManagerImpl.runWorkUnderContext(SelfTuningWorkManagerImpl.java:644)
	at weblogic.work.ExecuteThread.execute(ExecuteThread.java:415)
	at weblogic.work.ExecuteThread.run(ExecuteThread.java:355)
Caused by: java.io.IOException: Cannot find identity keystore file /u01/oracle/user_projects/domains/docker_domain/security/DemoIdentity.jks on server AdminServer
	at weblogic.server.channels.ServerSocketWrapperJSSE.<init>(ServerSocketWrapperJSSE.java:75)
	at weblogic.server.channels.ServerSocketManager.createServerSocketWrapper(ServerSocketManager.java:184)
	at weblogic.server.channels.ServerSocketManager.createBindAndEnableServerSocket(ServerSocketManager.java:158)
	at weblogic.server.channels.ServerSocketManager.createAndBindServerSockets(ServerSocketManager.java:126)
	... 26 more
Caused by: weblogic.management.configuration.ConfigurationException: Cannot find identity keystore file /u01/oracle/user_projects/domains/docker_domain/security/DemoIdentity.jks on server AdminServer
	at weblogic.security.utils.SSLContextManager.fail(SSLContextManager.java:818)
	at weblogic.security.utils.SSLContextManager.getServerSSLIdentity(SSLContextManager.java:743)
	at weblogic.security.utils.SSLContextManager.createSSLContext(SSLContextManager.java:509)
	at weblogic.security.utils.SSLContextManager.getChannelSSLContext(SSLContextManager.java:447)
	at weblogic.security.utils.SSLContextManager.getChannelSSLContext(SSLContextManager.java:433)
	at weblogic.security.utils.SSLContextManager.getSSLEngineFactory(SSLContextManager.java:382)
	at weblogic.server.channels.ServerSocketWrapperJSSE.<init>(ServerSocketWrapperJSSE.java:69)
	... 29 more

> 
<Jul 15, 2020 6:50:06,854 PM IST> <Notice> <WebLogicServer> <BEA-000365> <Server state changed to FAILED.> 
<Jul 15, 2020 6:50:06,855 PM IST> <Error> <WebLogicServer> <BEA-000383> <A critical service failed. The server will shut itself down.> 
<Jul 15, 2020 6:50:06,857 PM IST> <Notice> <WebLogicServer> <BEA-000365> <Server state changed to FORCE_SHUTTING_DOWN.> 
Stopping Derby server...
Derby server stopped.
	at weblogic.security.utils.SSLContextManager.getSSLEngineFactory(SSLContextManager.java:382)
	at weblogic.server.channels.ServerSocketWrapperJSSE.<init>(ServerSocketWrapperJSSE.java:69)
	... 29 more

> 
####<Jul 15, 2020 6:50:06,854 PM IST> <Notice> <WebLogicServer> <11e4d2a7045d> <AdminServer> <main> <<WLS Kernel>> <> <> <1594819206854> <[severity-value: 32] [partition-id: 0] [partition-name: DOMAIN] > <BEA-000365> <Server state changed to FAILED.> 
####<Jul 15, 2020 6:50:06,855 PM IST> <Error> <WebLogicServer> <11e4d2a7045d> <AdminServer> <main> <<WLS Kernel>> <> <> <1594819206855> <[severity-value: 8] [partition-id: 0] [partition-name: DOMAIN] > <BEA-000383> <A critical service failed. The server will shut itself down.> 
####<Jul 15, 2020 6:50:06,857 PM IST> <Notice> <WebLogicServer> <11e4d2a7045d> <AdminServer> <main> <<WLS Kernel>> <> <> <1594819206857> <[severity-value: 32] [partition-id: 0] [partition-name: DOMAIN] > <BEA-000365> <Server state changed to FORCE_SHUTTING_DOWN.> 
####<Jul 15, 2020 6:50:06,859 PM IST> <Info> <WebLogicServer> <11e4d2a7045d> <AdminServer> <[STANDBY] ExecuteThread: '1' for queue: 'weblogic.kernel.Default (self-tuning)'> <<WLS Kernel>> <> <> <1594819206859> <[severity-value: 64] [partition-id: 0] [partition-name: DOMAIN] > <BEA-000236> <Stopping execute threads.> 
####<Jul 15, 2020 6:50:06,862 PM IST> <Info> <WebLogicServer> <11e4d2a7045d> <AdminServer> <main> <<WLS Kernel>> <> <> <1594819206862> <[severity-value: 64] [partition-id: 0] [partition-name: DOMAIN] > <BEA-000238> <Shutdown has completed.>

**Comment by Djelibeybi** [comment]
Is this still an issue?

**Comment by mriccell** [comment]
could you share how you do the docker run?  How are you creating the domain? What are your properties?

**Comment by mriccell** [comment]
is the domain in the image or on a host volume?

**Comment by mriccell** [comment]
You can disable the Admin channel NOTE: For security, the Administration port 9002 is enabled by default, before running the container in WebLogic 12.2.1.4. If you prefer to not enable the Administration port when you issue the docker run command, set ADMINISTRTATION_PORT_ENABLED to false. If you intend to run these images in production, then you must change the Production Mode to production. When you set the DOMAIN_NAME, the DOMAIN_HOME=/u01/oracle/user_projects/domains/$DOMAIN_NAME.
