### ISSUE TITLE
java.io.IOException: SystemDatagramSocketProvider failed to bind to configured port

### ISSUE THREAD

**Issue by srikanthreddykota** [oracle/docker-images#1692]
Getting an issue with WebLogic 12.2.1.4 version of Docker Image. The same worked in 12.2.1.3 version of WebLogic Docker Image without issue. Below is the error log.

Kindly look into the issue and help me to resolve it.

Error Log
-----------------
Aug 04, 2020 10:22:44 PM com.tangosol.coherence.component.util.logOutput.Jdk log
SEVERE: 2020-08-04 22:22:44.420/54.520 Oracle Coherence GE 12.2.1.4.0 <Error> (thread=[STANDBY] ExecuteThread: '13' for queue: 'weblogic.kernel.Default (self-tuning)', member=n/a): Error while starting cluster: (Wrapped) java.io.IOException: SystemDatagramSocketProvider failed to bind to configured port 8842. Note, that port auto-adjust feature has been explicitly disabled
	at com.tangosol.util.Base.ensureRuntimeException(Base.java:324)
	at com.tangosol.util.Base.ensureRuntimeException(Base.java:305)
	at com.tangosol.coherence.component.net.Cluster.onStart(Cluster.CDB:41)
	at com.tangosol.coherence.component.net.Cluster.start(Cluster.CDB:12)
	at com.tangosol.coherence.component.util.SafeCluster.startCluster(SafeCluster.CDB:5)
	at com.tangosol.coherence.component.util.SafeCluster.restartCluster(SafeCluster.CDB:10)
	at com.tangosol.coherence.component.util.SafeCluster.ensureRunningCluster(SafeCluster.CDB:32)
	at com.tangosol.coherence.component.util.SafeCluster.getRunningCluster(SafeCluster.CDB:7)
	at com.tangosol.coherence.component.util.SafeCluster.start(SafeCluster.CDB:5)
	at com.tangosol.net.CacheFactory.ensureCluster(CacheFactory.java:580)
	at com.tangosol.net.ExtensibleConfigurableCacheFactory.ensureService(ExtensibleConfigurableCacheFactory.java:634)
	at com.tangosol.coherence.config.scheme.AbstractCachingScheme.realizeCache(AbstractCachingScheme.java:53)
	at com.tangosol.coherence.config.scheme.NearScheme.realizeCache(NearScheme.java:96)
	at com.tangosol.net.ExtensibleConfigurableCacheFactory.ensureCacheInternal(ExtensibleConfigurableCacheFactory.java:340)
	at com.tangosol.net.ExtensibleConfigurableCacheFactory.ensureCache(ExtensibleConfigurableCacheFactory.java:213)
	at com.tangosol.net.CacheFactory.getCache(CacheFactory.java:296)
	at com.tangosol.net.CacheFactory.getCache(CacheFactory.java:212)
	at com.adminserver.cycle.agent.bll.CycleServiceBll.<init>(CycleServiceBll.java:35)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.springframework.beans.BeanUtils.instantiateClass(BeanUtils.java:203)
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:87)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateBean(AbstractAutowireCapableBeanFactory.java:1312)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1214)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:557)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:517)
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:323)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:222)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:321)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:202)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:879)
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:878)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:550)
	at org.springframework.web.context.ContextLoader.configureAndRefreshWebApplicationContext(ContextLoader.java:401)
	at org.springframework.web.context.ContextLoader.initWebApplicationContext(ContextLoader.java:292)
	at org.springframework.web.context.ContextLoaderListener.contextInitialized(ContextLoaderListener.java:103)
	at com.adminserver.web.helper.ServletContextLoadListener.contextInitialized(ServletContextLoadListener.java:47)
	at weblogic.servlet.internal.EventsManager$FireContextListenerAction.run(EventsManager.java:719)
	at weblogic.security.acl.internal.AuthenticatedSubject.doAs(AuthenticatedSubject.java:344)
	at weblogic.security.service.SecurityManager.runAsForUserCode(SecurityManager.java:197)
	at weblogic.servlet.provider.WlsSecurityProvider.runAsForUserCode(WlsSecurityProvider.java:203)
	at weblogic.servlet.provider.WlsSubjectHandle.run(WlsSubjectHandle.java:71)
	at weblogic.servlet.internal.EventsManager.executeContextListener(EventsManager.java:251)
	at weblogic.servlet.internal.EventsManager.notifyContextCreatedEvent(EventsManager.java:204)
	at weblogic.servlet.internal.EventsManager.notifyContextCreatedEvent(EventsManager.java:189)
	at weblogic.servlet.internal.WebAppServletContext.preloadResources(WebAppServletContext.java:1929)
	at weblogic.servlet.internal.WebAppServletContext.start(WebAppServletContext.java:3191)
	at weblogic.servlet.internal.WebAppModule.startContexts(WebAppModule.java:1864)
	at weblogic.servlet.internal.WebAppModule.start(WebAppModule.java:919)
	at weblogic.application.internal.ExtensibleModuleWrapper$StartStateChange.next(ExtensibleModuleWrapper.java:360)
	at weblogic.application.internal.ExtensibleModuleWrapper$StartStateChange.next(ExtensibleModuleWrapper.java:356)
	at weblogic.application.utils.StateMachineDriver.nextState(StateMachineDriver.java:45)
	at weblogic.application.internal.ExtensibleModuleWrapper.start(ExtensibleModuleWrapper.java:138)
	at weblogic.application.internal.flow.ModuleListenerInvoker.start(ModuleListenerInvoker.java:124)
	at weblogic.application.internal.flow.ModuleStateDriver$3.next(ModuleStateDriver.java:233)
	at weblogic.application.internal.flow.ModuleStateDriver$3.next(ModuleStateDriver.java:228)
	at weblogic.application.utils.StateMachineDriver.nextState(StateMachineDriver.java:45)
	at weblogic.application.internal.flow.ModuleStateDriver.start(ModuleStateDriver.java:78)
	at weblogic.application.internal.flow.StartModulesFlow.activate(StartModulesFlow.java:52)
	at weblogic.application.internal.BaseDeployment$2.next(BaseDeployment.java:752)
	at weblogic.application.utils.StateMachineDriver.nextState(StateMachineDriver.java:45)
	at weblogic.application.internal.BaseDeployment.activate(BaseDeployment.java:262)
	at weblogic.application.internal.SingleModuleDeployment.activate(SingleModuleDeployment.java:52)
	at weblogic.application.internal.DeploymentStateChecker.activate(DeploymentStateChecker.java:165)
	at weblogic.deploy.internal.targetserver.AppContainerInvoker.activate(AppContainerInvoker.java:90)
	at weblogic.deploy.internal.targetserver.operations.AbstractOperation.activate(AbstractOperation.java:631)
	at weblogic.deploy.internal.targetserver.operations.ActivateOperation.activateDeployment(ActivateOperation.java:171)
	at weblogic.deploy.internal.targetserver.operations.ActivateOperation.doCommit(ActivateOperation.java:121)
	at weblogic.deploy.internal.targetserver.operations.AbstractOperation.commit(AbstractOperation.java:348)
	at weblogic.deploy.internal.targetserver.DeploymentManager.handleDeploymentCommit(DeploymentManager.java:907)
	at weblogic.deploy.internal.targetserver.DeploymentManager.activateDeploymentList(DeploymentManager.java:1468)
	at weblogic.deploy.internal.targetserver.DeploymentManager.handleCommit(DeploymentManager.java:459)
	at weblogic.deploy.internal.targetserver.DeploymentServiceDispatcher.commit(DeploymentServiceDispatcher.java:181)
	at weblogic.deploy.service.internal.targetserver.DeploymentReceiverCallbackDeliverer.doCommitCallback(DeploymentReceiverCallbackDeliverer.java:217)
	at weblogic.deploy.service.internal.targetserver.DeploymentReceiverCallbackDeliverer.access$100(DeploymentReceiverCallbackDeliverer.java:14)
	at weblogic.deploy.service.internal.targetserver.DeploymentReceiverCallbackDeliverer$2.run(DeploymentReceiverCallbackDeliverer.java:69)
	at weblogic.work.SelfTuningWorkManagerImpl$WorkAdapterImpl.run(SelfTuningWorkManagerImpl.java:681)
	at weblogic.invocation.ComponentInvocationContextManager._runAs(ComponentInvocationContextManager.java:352)
	at weblogic.invocation.ComponentInvocationContextManager.runAs(ComponentInvocationContextManager.java:337)
	at weblogic.work.LivePartitionUtility.doRunWorkUnderContext(LivePartitionUtility.java:57)
	at weblogic.work.PartitionUtility.runWorkUnderContext(PartitionUtility.java:41)
	at weblogic.work.SelfTuningWorkManagerImpl.runWorkUnderContext(SelfTuningWorkManagerImpl.java:655)
	at weblogic.work.ExecuteThread.execute(ExecuteThread.java:420)
	at weblogic.work.ExecuteThread.run(ExecuteThread.java:360)
Caused by: java.io.IOException: SystemDatagramSocketProvider failed to bind to configured port 8842. Note, that port auto-adjust feature has been explicitly disabled
	at com.tangosol.coherence.component.net.Cluster$SocketManager.bindSockets(Cluster.CDB:162)
	at com.tangosol.coherence.component.net.Cluster.onStart(Cluster.CDB:37)
	... 83 more
Caused by: java.net.BindException: Address already in use
	at sun.nio.ch.Net.bind0(Native Method)
	at sun.nio.ch.Net.bind(Net.java:433)
	at sun.nio.ch.Net.bind(Net.java:425)
	at sun.nio.ch.ServerSocketChannelImpl.bind(ServerSocketChannelImpl.java:223)
	at sun.nio.ch.ServerSocketAdaptor.bind(ServerSocketAdaptor.java:74)
	at com.oracle.common.internal.net.WrapperServerSocket.bind(WrapperServerSocket.java:71)
	at com.oracle.common.internal.net.MultiplexedSocketProvider.open(MultiplexedSocketProvider.java:2234)
	at com.oracle.common.internal.net.MultiplexedSocketProvider.open(MultiplexedSocketProvider.java:2106)
	at com.oracle.common.internal.net.MultiplexedSocketProvider$MultiplexedServerSocketChannel$1.bind(MultiplexedSocketProvider.java:775)
	at com.oracle.common.internal.net.WrapperServerSocket.bind(WrapperServerSocket.java:71)
	at com.oracle.common.internal.net.DemultiplexedSocketProvider$DemultiplexedServerSocketChannel$1.bind(DemultiplexedSocketProvider.java:165)
	at com.tangosol.coherence.component.net.Cluster$SocketManager$AcceptorChannel.instantiateChannel(Cluster.CDB:14)
	at com.tangosol.coherence.component.net.Cluster$SocketManager.bindSockets(Cluster.CDB:60)
	... 84 more

<Aug 4, 2020 10:22:44,420 PM GMT> <Error> <Coherence> <BEA-000000> <2020-08-04 22:22:44.420/54.520 Oracle Coherence GE 12.2.1.4.0 <Error> (thread=[STANDBY] ExecuteThread: '13' for queue: 'weblogic.kernel.Default (self-tuning)', member=n/a): Error while starting cluster: (Wrapped) java.io.IOException: SystemDatagramSocketProvider failed to bind to configured port 8842. Note, that port auto-adjust feature has been explicitly disabled
	at com.tangosol.util.Base.ensureRuntimeException(Base.java:324)
	at com.tangosol.util.Base.ensureRuntimeException(Base.java:305)
	at com.tangosol.coherence.component.net.Cluster.onStart(Cluster.CDB:41)
	at com.tangosol.coherence.component.net.Cluster.start(Cluster.CDB:12)
	at com.tangosol.coherence.component.util.SafeCluster.startCluster(SafeCluster.CDB:5)
	at com.tangosol.coherence.component.util.SafeCluster.restartCluster(SafeCluster.CDB:10)
	at com.tangosol.coherence.component.util.SafeCluster.ensureRunningCluster(SafeCluster.CDB:32)
	at com.tangosol.coherence.component.util.SafeCluster.getRunningCluster(SafeCluster.CDB:7)
	at com.tangosol.coherence.component.util.SafeCluster.start(SafeCluster.CDB:5)
	at com.tangosol.net.CacheFactory.ensureCluster(CacheFactory.java:580)
	at com.tangosol.net.ExtensibleConfigurableCacheFactory.ensureService(ExtensibleConfigurableCacheFactory.java:634)
	at com.tangosol.coherence.config.scheme.AbstractCachingScheme.realizeCache(AbstractCachingScheme.java:53)
	at com.tangosol.coherence.config.scheme.NearScheme.realizeCache(NearScheme.java:96)
	at com.tangosol.net.ExtensibleConfigurableCacheFactory.ensureCacheInternal(ExtensibleConfigurableCacheFactory.java:340)
	at com.tangosol.net.ExtensibleConfigurableCacheFactory.ensureCache(ExtensibleConfigurableCacheFactory.java:213)
	at com.tangosol.net.CacheFactory.getCache(CacheFactory.java:296)
	at com.tangosol.net.CacheFactory.getCache(CacheFactory.java:212)
	at com.adminserver.cycle.agent.bll.CycleServiceBll.<init>(CycleServiceBll.java:35)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.springframework.beans.BeanUtils.instantiateClass(BeanUtils.java:203)
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:87)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateBean(AbstractAutowireCapableBeanFactory.java:1312)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1214)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:557)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:517)
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:323)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:222)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:321)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:202)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:879)
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:878)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:550)
	at org.springframework.web.context.ContextLoader.configureAndRefreshWebApplicationContext(ContextLoader.java:401)
	at org.springframework.web.context.ContextLoader.initWebApplicationContext(ContextLoader.java:292)
	at org.springframework.web.context.ContextLoaderListener.contextInitialized(ContextLoaderListener.java:103)
	at com.adminserver.web.helper.ServletContextLoadListener.contextInitialized(ServletContextLoadListener.java:47)
	at weblogic.servlet.internal.EventsManager$FireContextListenerAction.run(EventsManager.java:719)
	at weblogic.security.acl.internal.AuthenticatedSubject.doAs(AuthenticatedSubject.java:344)
	at weblogic.security.service.SecurityManager.runAsForUserCode(SecurityManager.java:197)
	at weblogic.servlet.provider.WlsSecurityProvider.runAsForUserCode(WlsSecurityProvider.java:203)
	at weblogic.servlet.provider.WlsSubjectHandle.run(WlsSubjectHandle.java:71)
	at weblogic.servlet.internal.EventsManager.executeContextListener(EventsManager.java:251)
	at weblogic.servlet.internal.EventsManager.notifyContextCreatedEvent(EventsManager.java:204)
	at weblogic.servlet.internal.EventsManager.notifyContextCreatedEvent(EventsManager.java:189)
	at weblogic.servlet.internal.WebAppServletContext.preloadResources(WebAppServletContext.java:1929)
	at weblogic.servlet.internal.WebAppServletContext.start(WebAppServletContext.java:3191)
	at weblogic.servlet.internal.WebAppModule.startContexts(WebAppModule.java:1864)
	at weblogic.servlet.internal.WebAppModule.start(WebAppModule.java:919)
	at weblogic.application.internal.ExtensibleModuleWrapper$StartStateChange.next(ExtensibleModuleWrapper.java:360)
	at weblogic.application.internal.ExtensibleModuleWrapper$StartStateChange.next(ExtensibleModuleWrapper.java:356)
	at weblogic.application.utils.StateMachineDriver.nextState(StateMachineDriver.java:45)
	at weblogic.application.internal.ExtensibleModuleWrapper.start(ExtensibleModuleWrapper.java:138)
	at weblogic.application.internal.flow.ModuleListenerInvoker.start(ModuleListenerInvoker.java:124)
	at weblogic.application.internal.flow.ModuleStateDriver$3.next(ModuleStateDriver.java:233)
	at weblogic.application.internal.flow.ModuleStateDriver$3.next(ModuleStateDriver.java:228)
	at weblogic.application.utils.StateMachineDriver.nextState(StateMachineDriver.java:45)
	at weblogic.application.internal.flow.ModuleStateDriver.start(ModuleStateDriver.java:78)
	at weblogic.application.internal.flow.StartModulesFlow.activate(StartModulesFlow.java:52)
	at weblogic.application.internal.BaseDeployment$2.next(BaseDeployment.java:752)
	at weblogic.application.utils.StateMachineDriver.nextState(StateMachineDriver.java:45)
	at weblogic.application.internal.BaseDeployment.activate(BaseDeployment.java:262)
	at weblogic.application.internal.SingleModuleDeployment.activate(SingleModuleDeployment.java:52)
	at weblogic.application.internal.DeploymentStateChecker.activate(DeploymentStateChecker.java:165)
	at weblogic.deploy.internal.targetserver.AppContainerInvoker.activate(AppContainerInvoker.java:90)
	at weblogic.deploy.internal.targetserver.operations.AbstractOperation.activate(AbstractOperation.java:631)
	at weblogic.deploy.internal.targetserver.operations.ActivateOperation.activateDeployment(ActivateOperation.java:171)
	at weblogic.deploy.internal.targetserver.operations.ActivateOperation.doCommit(ActivateOperation.java:121)
	at weblogic.deploy.internal.targetserver.operations.AbstractOperation.commit(AbstractOperation.java:348)
	at weblogic.deploy.internal.targetserver.DeploymentManager.handleDeploymentCommit(DeploymentManager.java:907)
	at weblogic.deploy.internal.targetserver.DeploymentManager.activateDeploymentList(DeploymentManager.java:1468)
	at weblogic.deploy.internal.targetserver.DeploymentManager.handleCommit(DeploymentManager.java:459)
	at weblogic.deploy.internal.targetserver.DeploymentServiceDispatcher.commit(DeploymentServiceDispatcher.java:181)
	at weblogic.deploy.service.internal.targetserver.DeploymentReceiverCallbackDeliverer.doCommitCallback(DeploymentReceiverCallbackDeliverer.java:217)
	at weblogic.deploy.service.internal.targetserver.DeploymentReceiverCallbackDeliverer.access$100(DeploymentReceiverCallbackDeliverer.java:14)
	at weblogic.deploy.service.internal.targetserver.DeploymentReceiverCallbackDeliverer$2.run(DeploymentReceiverCallbackDeliverer.java:69)
	at weblogic.work.SelfTuningWorkManagerImpl$WorkAdapterImpl.run(SelfTuningWorkManagerImpl.java:681)
	at weblogic.invocation.ComponentInvocationContextManager._runAs(ComponentInvocationContextManager.java:352)
	at weblogic.invocation.ComponentInvocationContextManager.runAs(ComponentInvocationContextManager.java:337)
	at weblogic.work.LivePartitionUtility.doRunWorkUnderContext(LivePartitionUtility.java:57)
	at weblogic.work.PartitionUtility.runWorkUnderContext(PartitionUtility.java:41)
	at weblogic.work.SelfTuningWorkManagerImpl.runWorkUnderContext(SelfTuningWorkManagerImpl.java:655)
	at weblogic.work.ExecuteThread.execute(ExecuteThread.java:420)
	at weblogic.work.ExecuteThread.run(ExecuteThread.java:360)
Caused by: java.io.IOException: SystemDatagramSocketProvider failed to bind to configured port 8842. Note, that port auto-adjust feature has been explicitly disabled
	at com.tangosol.coherence.component.net.Cluster$SocketManager.bindSockets(Cluster.CDB:162)
	at com.tangosol.coherence.component.net.Cluster.onStart(Cluster.CDB:37)
	... 83 more
Caused by: java.net.BindException: Address already in use
	at sun.nio.ch.Net.bind0(Native Method)
	at sun.nio.ch.Net.bind(Net.java:433)
	at sun.nio.ch.Net.bind(Net.java:425)
	at sun.nio.ch.ServerSocketChannelImpl.bind(ServerSocketChannelImpl.java:223)
	at sun.nio.ch.ServerSocketAdaptor.bind(ServerSocketAdaptor.java:74)
	at com.oracle.common.internal.net.WrapperServerSocket.bind(WrapperServerSocket.java:71)
	at com.oracle.common.internal.net.MultiplexedSocketProvider.open(MultiplexedSocketProvider.java:2234)
	at com.oracle.common.internal.net.MultiplexedSocketProvider.open(MultiplexedSocketProvider.java:2106)
	at com.oracle.common.internal.net.MultiplexedSocketProvider$MultiplexedServerSocketChannel$1.bind(MultiplexedSocketProvider.java:775)
	at com.oracle.common.internal.net.WrapperServerSocket.bind(WrapperServerSocket.java:71)
	at com.oracle.common.internal.net.DemultiplexedSocketProvider$DemultiplexedServerSocketChannel$1.bind(DemultiplexedSocketProvider.java:165)
	at com.tangosol.coherence.component.net.Cluster$SocketManager$AcceptorChannel.instantiateChannel(Cluster.CDB:14)
	at com.tangosol.coherence.component.net.Cluster$SocketManager.bindSockets(Cluster.CDB:60)
	... 84 more
>

**Comment by sree5877** [comment]
**Note**: I got this error in the WebLogic 12.2.1.4 version image only. Previously I used to WebLogic 12.2.1.3 version of docker image and worked without issues.

**Comment by srikanthreddykota** [comment]
Hi Team, This issue is impacting our product release plans. Could you please take a look into this on priority?

**Comment by srikanthreddykota** [comment]
> Hi Team, This issue is impacting our product release plans. Could you please take a look into this on priority?

**Comment by Djelibeybi** [comment]
This is not an official support channel. If you have product dependencies on this, you need to open an SR with Oracle Support.

**Comment by mriccell** [comment]
This is a Coherence exception not WebLogic @thegridman .
Monica

**Comment by thegridman** [comment]
The error says that Coherence cannot start because it is trying to bind to a port that is already in use, specifically port 8842. This would suggest something is mis-configured. 

I have no idea how all of this runs inside WebLogic. How are you running you image, what is the command you use to start it.

**Comment by rjeberhard** [comment]
@srikanthreddykota, please open an SR. Someone is going to need to spend some time with you to figure out why Coherence@Web is attempting to use a port that is already in use.
