### ISSUE TITLE
Error when creating managed server with version 12.2.1.4

### ISSUE THREAD

**Issue by secarullo** [oracle/docker-images#1799]
Hi,
I've modified Dockerfile from sample directory 12213, to be able to create Weblogic container for version 12.2.1.4
When I run script run_admin_server.sh the container is created Ok, and I can deploy some apps on it. Everything works fine.
But when I want to create a managed server using script run_managed_server, always get errors.
This is the message:
`
Starting WLS with line:
/usr/java/jdk-8/bin/java -server   -Djava.security.egd=file:/dev/./urandom -cp /u01/oracle/wlserver/server/lib/weblogic-launcher.jar -Dlaunch.use.env.classpath=true -Dweblogic.Name=MS1 -Djava.security.policy=/u01/oracle/wlserver/server/lib/weblogic.policy -Doracle.jdbc.fanEnabled=false -Dweblogic.StdoutDebugEnabled=false -Djava.system.class.loader=com.oracle.classloader.weblogic.LaunchClassLoader  -javaagent:/u01/oracle/wlserver/server/lib/debugpatch-agent.jar -da -Dwls.home=/u01/oracle/wlserver/server -Dweblogic.home=/u01/oracle/wlserver/server   -Dweblogic.management.server=http://AdminContainer:7001   weblogic.Server
<Dec 1, 2020 4:52:37 PM CET> <Info> <Security> <BEA-090905> <Disabling the CryptoJ JCE Provider self-integrity check for better startup performance. To enable this check, specify -Dweblogic.security.allowCryptoJDefaultJCEVerification=true.>
<Dec 1, 2020 4:52:37 PM CET> <Info> <Security> <BEA-090906> <Changing the default Random Number Generator in RSA CryptoJ from ECDRBG128 to HMACDRBG. To disable this change, specify -Dweblogic.security.allowCryptoJDefaultPRNG=true.>
<Dec 1, 2020 4:52:38 PM CET> <Info> <WebLogicServer> <BEA-000377> <Starting WebLogic Server with Java HotSpot(TM) 64-Bit Server VM Version 25.231-b11 from Oracle Corporation.>
<Dec 1, 2020 4:52:38 PM CET> <Info> <RCM> <BEA-2165021> <"ResourceManagement" is not enabled in this JVM. Enable "ResourceManagement" to use the WebLogic Server "Resource Consumption Management" feature. To enable "ResourceManagement", you must specify the following JVM options in the WebLogic Server instance in which the JVM runs: -XX:+UnlockCommercialFeatures -XX:+ResourceManagement.>
<Dec 1, 2020 4:52:40 PM CET> <Info> <Management> <BEA-141307> <Unable to connect to the Administration Server. Waiting 5 second(s) to retry (attempt number 1 of 3).>
<Dec 1, 2020 4:52:45 PM CET> <Info> <Management> <BEA-141307> <Unable to connect to the Administration Server. Waiting 5 second(s) to retry (attempt number 2 of 3).>
<Dec 1, 2020 4:52:50 PM CET> <Info> <Management> <BEA-141307> <Unable to connect to the Administration Server. Waiting 5 second(s) to retry (attempt number 3 of 3).>
<Dec 1, 2020 4:52:55 PM CET> <Info> <Management> <BEA-141298> <Could not register with the Administration Server: java.rmi.RemoteException: [Deployer:149150]An IOException occurred while reading the input. : with response code '403' : with response message 'Forbidden'>
<Dec 1, 2020 4:52:55 PM CET> <Info> <Management> <BEA-141107> <Version: WebLogic Server 12.2.1.4.0 Thu Sep 12 04:04:29 GMT 2019 1974621>
<Dec 1, 2020 4:52:55 PM CET> <Alert> <Management> <BEA-141151> <The Administration Server could not be reached at http://AdminContainer:7001.>
<Dec 1, 2020 4:52:55 PM CET> <Info> <Configuration Management> <BEA-150018> <This server is being started in Managed Server independence mode in the absence of the Administration Server.>
<Dec 1, 2020 4:52:56 PM CET> <Notice> <WebLogicServer> <BEA-000365> <Server state changed to STARTING.>
<Dec 1, 2020 4:52:56 PM CET> <Info> <WorkManager> <BEA-002900> <Initializing self-tuning thread pool.>
<Dec 1, 2020 4:52:56 PM CET> <Info> <WorkManager> <BEA-002942> <CMM memory level becomes 0. Setting standby thread pool size to 256.>
<Dec 1, 2020 4:52:56,728 PM CET> <Notice> <Log Management> <BEA-170019> <The server log file weblogic.logging.FileStreamHandler instance=1722202809
Current log file=/u01/oracle/user_projects/domains/myDomain/servers/MS1/logs/MS1.log
Rotation dir=/u01/oracle/user_projects/domains/myDomain/servers/MS1/logs
 is opened. All server side log events will be written to this file.>
<Dec 1, 2020 4:52:56,795 PM CET> <Notice> <Security> <BEA-090171> <Loading the identity certificate and private key stored under the alias DemoIdentity from the jks keystore file /u01/oracle/user_projects/domains/myDomain/security/DemoIdentity.jks.>
<Dec 1, 2020 4:52:56,822 PM CET> <Notice> <Security> <BEA-090169> <Loading trusted certificates from the jks keystore file /u01/oracle/wlserver/server/lib/DemoTrust.jks.>
<Dec 1, 2020 4:52:56,840 PM CET> <Notice> <Security> <BEA-090169> <Loading trusted certificates from the jks keystore file /usr/java/jdk-8/jre/lib/security/cacerts.>
<Dec 1, 2020 4:52:56,878 PM CET> <Notice> <Server> <BEA-002613> <Channel "DefaultAdministration" is now listening on 172.17.0.4:9002 for protocols admin, ldaps, https.>
<Dec 1, 2020 4:52:56,891 PM CET> <Notice> <Server> <BEA-002613> <Channel "DefaultAdministration[1]" is now listening on 127.0.0.1:9002 for protocols admin, ldaps, https.>
<Dec 1, 2020 4:52:56,892 PM CET> <Notice> <Server> <BEA-002613> <Channel "DefaultAdministration" is now listening on 172.17.0.4:9002 for protocols admin, ldaps, https.>
<Dec 1, 2020 4:52:56,892 PM CET> <Notice> <Server> <BEA-002613> <Channel "DefaultAdministration[1]" is now listening on 127.0.0.1:9002 for protocols admin, ldaps, https.>
<Dec 1, 2020 4:52:56,909 PM CET> <Notice> <Security> <BEA-090946> <Security pre-initializing using security realm: myrealm>
<Dec 1, 2020 4:52:57,372 PM CET> <Notice> <Security> <BEA-090947> <Security post-initializing using security realm: myrealm>
<Dec 1, 2020 4:52:58,385 PM CET> <Notice> <Security> <BEA-090082> <Security initialized using administrative security realm: myrealm>
<Dec 1, 2020 4:52:58,404 PM CET> <Critical> <Security> <BEA-090402> <Authentication denied: Boot identity not valid. The user name or password or both from the boot identity file (boot.properties) is not valid. The boot identity may have been changed since the boot identity file was created. Please edit and update the boot identity file with the proper values of username and password. The first time the updated boot identity file is used to start the server, these new values are encrypted.>
<Dec 1, 2020 4:52:58,444 PM CET> <Critical> <WebLogicServer> <BEA-000386> <Server subsystem failed. Reason: A MultiException has 6 exceptions.  They are:
1. weblogic.security.SecurityInitializationException: Authentication denied: Boot identity not valid. The user name or password or both from the boot identity file (boot.properties) is not valid. The boot identity may have been changed since the boot identity file was created. Please edit and update the boot identity file with the proper values of username and password. The first time the updated boot identity file is used to start the server, these new values are encrypted.
2. java.lang.IllegalStateException: Unable to perform operation: post construct on weblogic.security.SecurityService
3. java.lang.IllegalArgumentException: While attempting to resolve the dependencies of weblogic.jndi.internal.RemoteNamingService errors were found
4. java.lang.IllegalStateException: Unable to perform operation: resolve on weblogic.jndi.internal.RemoteNamingService
5. java.lang.IllegalArgumentException: While attempting to resolve the dependencies of weblogic.deployment.DeploymentRegistrationService errors were found
6. java.lang.IllegalStateException: Unable to perform operation: resolve on weblogic.deployment.DeploymentRegistrationService

A MultiException has 6 exceptions.  They are:
1. weblogic.security.SecurityInitializationException: Authentication denied: Boot identity not valid. The user name or password or both from the boot identity file (boot.properties) is not valid. The boot identity may have been changed since the boot identity file was created. Please edit and update the boot identity file with the proper values of username and password. The first time the updated boot identity file is used to start the server, these new values are encrypted.
2. java.lang.IllegalStateException: Unable to perform operation: post construct on weblogic.security.SecurityService
3. java.lang.IllegalArgumentException: While attempting to resolve the dependencies of weblogic.jndi.internal.RemoteNamingService errors were found
4. java.lang.IllegalStateException: Unable to perform operation: resolve on weblogic.jndi.internal.RemoteNamingService
5. java.lang.IllegalArgumentException: While attempting to resolve the dependencies of weblogic.deployment.DeploymentRegistrationService errors were found
6. java.lang.IllegalStateException: Unable to perform operation: resolve on weblogic.deployment.DeploymentRegistrationService

        at org.jvnet.hk2.internal.Collector.throwIfErrors(Collector.java:89)
        at org.jvnet.hk2.internal.ClazzCreator.resolveAllDependencies(ClazzCreator.java:250)
        at org.jvnet.hk2.internal.ClazzCreator.create(ClazzCreator.java:358)
        at org.jvnet.hk2.internal.SystemDescriptor.create(SystemDescriptor.java:487)
        at org.glassfish.hk2.runlevel.internal.AsyncRunLevelContext.findOrCreate(AsyncRunLevelContext.java:305)
        Truncated. see log file for complete stacktrace
Caused By: weblogic.security.SecurityInitializationException: Authentication denied: Boot identity not valid. The user name or password or both from the boot identity file (boot.properties) is not valid. The boot identity may have been changed since the boot identity file was created. Please edit and update the boot identity file with the proper values of username and password. The first time the updated boot identity file is used to start the server, these new values are encrypted.
        at weblogic.security.service.CommonSecurityServiceManagerDelegateImpl.doBootAuthorization(CommonSecurityServiceManagerDelegateImpl.java:1152)
        at weblogic.security.service.CommonSecurityServiceManagerDelegateImpl.postInitialize(CommonSecurityServiceManagerDelegateImpl.java:1272)
        at weblogic.security.service.SecurityServiceManager.postInitialize(SecurityServiceManager.java:586)
        at weblogic.security.SecurityService.start(SecurityService.java:130)
        at weblogic.server.AbstractServerService.postConstruct(AbstractServerService.java:76)
        Truncated. see log file for complete stacktrace
Caused By: javax.security.auth.login.FailedLoginException: [Security:090938]Authentication failure: The specified user failed to log in. weblogic.security.providers.authentication.LDAPAtnDelegateException: [Security:090295]caught unexpected exception, No such object
        at com.bea.common.security.utils.ExceptionHandler.throwFailedLoginException(ExceptionHandler.java:62)
        at weblogic.security.providers.authentication.LDAPAtnLoginModuleImpl.login(LDAPAtnLoginModuleImpl.java:369)
        at com.bea.common.security.internal.service.LoginModuleWrapper$1.run(LoginModuleWrapper.java:117)
        at java.security.AccessController.doPrivileged(Native Method)
        at com.bea.common.security.internal.service.LoginModuleWrapper.login(LoginModuleWrapper.java:114)
        Truncated. see log file for complete stacktrace
>
<Dec 1, 2020 4:52:58,456 PM CET> <Notice> <WebLogicServer> <BEA-000365> <Server state changed to FAILED.>
<Dec 1, 2020 4:52:58,456 PM CET> <Error> <WebLogicServer> <BEA-000383> <A critical service failed. The server will shut itself down.>
<Dec 1, 2020 4:52:58,464 PM CET> <Notice> <WebLogicServer> <BEA-000365> <Server state changed to FORCE_SHUTTING_DOWN.>
        at weblogic.work.PartitionUtility.runWorkUnderContext(PartitionUtility.java:41)
        at weblogic.work.SelfTuningWorkManagerImpl.runWorkUnderContext(SelfTuningWorkManagerImpl.java:655)
        at weblogic.work.ExecuteThread.execute(ExecuteThread.java:420)
        at weblogic.work.ExecuteThread.run(ExecuteThread.java:360)
>
####<Dec 1, 2020 4:52:58,456 PM CET> <Notice> <WebLogicServer> <6870f5615e56> <MS1> <main> <<WLS Kernel>> <> <326b5b1a-785a-4110-959a-de37f34fe4e7-00000003> <1606837978456> <[severity-value: 32] [rid: 0] [partition-id: 0] [partition-name: DOMAIN] > <BEA-000365> <Server state changed to FAILED.>
####<Dec 1, 2020 4:52:58,456 PM CET> <Error> <WebLogicServer> <6870f5615e56> <MS1> <main> <<WLS Kernel>> <> <326b5b1a-785a-4110-959a-de37f34fe4e7-00000003> <1606837978456> <[severity-value: 8] [rid: 0] [partition-id: 0] [partition-name: DOMAIN] > <BEA-000383> <A critical service failed. The server will shut itself down.>
####<Dec 1, 2020 4:52:58,464 PM CET> <Notice> <WebLogicServer> <6870f5615e56> <MS1> <main> <<WLS Kernel>> <> <326b5b1a-785a-4110-959a-de37f34fe4e7-00000003> <1606837978464> <[severity-value: 32] [rid: 0] [partition-id: 0] [partition-name: DOMAIN] > <BEA-000365> <Server state changed to FORCE_SHUTTING_DOWN.>
####<Dec 1, 2020 4:52:58,468 PM CET> <Info> <WebLogicServer> <6870f5615e56> <MS1> <[STANDBY] ExecuteThread: '2' for queue: 'weblogic.kernel.Default (self-tuning)'> <<WLS Kernel>> <> <326b5b1a-785a-4110-959a-de37f34fe4e7-00000004> <1606837978468> <[severity-value: 64] [rid: 0] [partition-id: 0] [partition-name: DOMAIN] > <BEA-000236> <Stopping execute threads.>
####<Dec 1, 2020 4:52:58,470 PM CET> <Info> <WebLogicServer> <6870f5615e56> <MS1> <main> <<WLS Kernel>> <> <326b5b1a-785a-4110-959a-de37f34fe4e7-00000003> <1606837978470> <[severity-value: 64] [rid: 0] [partition-id: 0] [partition-name: DOMAIN] > <BEA-000238> <Shutdown has completed.>

Could you please help how to solve the issue?
Thank you,
Best regards,
Sebastian

**Comment by secarullo** [comment]
Hi!
I was able to deploy admin and managed server, both of them using version 12.2.1.4.0
Just started from scratch, downloading all files from git again, and copy directory "12213-domain" to a new one called "12214-domain". Replaced references to docker image to 12214-developer image, and using scripts without modifications, just change docker ports and admin server name ("wlsadmin2")
Everything works now!
Best regards,
Sebastian
