### ISSUE TITLE
django.db.utils.DatabaseError: ORA-12541: TNS:no listener

### ISSUE THREAD

**Issue by zarif98sjs** [oracle/docker-images#1934]
I am trying to use Oracle 12C with Django. But I am getting `django.db.utils.DatabaseError: ORA-12541: TNS:no listener`

This is my `Dockerfile`

```python
#Tells Docker to use the official python 3 image from dockerhub as a base image
FROM python:3
# Sets an environmental variable that ensures output from python is sent straight to the terminal without buffering it first
ENV PYTHONUNBUFFERED 1


WORKDIR /opt/oracle
RUN        apt-get update && apt-get install -y libaio1 wget unzip \
            && wget https://download.oracle.com/otn_software/linux/instantclient/instantclient-basiclite-linuxx64.zip \
            && unzip instantclient-basiclite-linuxx64.zip \
            && rm -f instantclient-basiclite-linuxx64.zip \
            && cd /opt/oracle/instantclient* \
            && rm -f *jdbc* *occi* *mysql* *README *jar uidrvci genezi adrci \
            && echo /opt/oracle/instantclient* > /etc/ld.so.conf.d/oracle-instantclient.conf \
            && ldconfig

# Sets the container's working directory to /app
WORKDIR /app
# runs the pip install command for all packages listed in the requirements.txt file
COPY ./requirements.txt /app/requirements.txt
RUN pip install -r requirements.txt

# Copies all files from our local project into the container
COPY . /app
```

and this is my docker-compose

```yml
version: '3'
services:
    db:
        image: store/oracle/database-enterprise:12.2.0.1
        restart: "unless-stopped"
        ports:
            - 1523:1521
            # - 8080:8080
            - 5501:5500
        volumes:
            - /home/oracle/oradata:/opt/oracle/oradata # persistent oracle database data.
            - ./setup-scripts:/container-entrypoint-startdb.d
        environment: 
            - "ORACLE_PWD=oracle"
    web:
        build: .
        command: python manage.py runserver 0.0.0.0:8000
        ports:
            - "8000:8000"
        depends_on:
            - db
```

and this is my django connection

```python
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.oracle',
        'NAME': 'ORCLCDB',
        'USER': 'INNOCITY',
        'PASSWORD': '2108',
        'HOST': 'localhost',
        'PORT': '1523',
        'CONN_MAX_AGE': None,
    },
    'test': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}
```

The whole logfile is following :

```
innocity_test_db_1 is up-to-date
innocity_test_web_1 is up-to-date
Attaching to innocity_test_db_1, innocity_test_web_1
db_1   | Setup Oracle Database
db_1   | Oracle Database 12.2.0.1 Setup
db_1   | Thu May 6 08:56:01 UTC 2021
db_1   |
db_1   | Check parameters ......
db_1   | log file is : /home/oracle/setup/log/paramChk.log
db_1   | paramChk.sh is done at 1 sec
db_1   |
db_1   | untar DB bits ......
db_1   | log file is : /home/oracle/setup/log/untarDB.log
db_1   | untarDB.sh is done at 623 sec
db_1   |
db_1   | config DB ......
db_1   | log file is : /home/oracle/setup/log/configDB.log
db_1   | Thu May 6 09:06:23 UTC 2021
db_1   | Start Docker DB configuration
db_1   | Call configDBora.sh to configure database
db_1   | Thu May 6 09:06:23 UTC 2021
db_1   | Configure DB as oracle user
db_1   | Setup Database directories ...
db_1   | startup database instance
db_1   |
db_1   | SQL*Plus: Release 12.2.0.1.0 Production on Thu May 6 09:06:23 2021
db_1   |
db_1   | Copyright (c) 1982, 2016, Oracle.  All rights reserved.
db_1   |
db_1   | Connected to an idle instance.
db_1   |
db_1   | SQL> ORA-01261: Parameter db_recovery_file_dest destination string cannot be translated
db_1   | ORA-01262: Stat failed on a file destination directory
db_1   | Linux-x86_64 Error: 2: No such file or directory
db_1   | SQL> Disconnected
db_1   |
db_1   | LSNRCTL for Linux: Version 12.2.0.1.0 - Production on 06-MAY-2021 09:06:25
db_1   |
db_1   | Copyright (c) 1991, 2016, Oracle.  All rights reserved.
db_1   |
db_1   | Starting /u01/app/oracle/product/12.2.0/dbhome_1/bin/tnslsnr: please wait...
db_1   |
db_1   | TNSLSNR for Linux: Version 12.2.0.1.0 - Production
db_1   | System parameter file is /u01/app/oracle/product/12.2.0/dbhome_1/admin/ORCLCDB/listener.ora
db_1   | Log messages written to /u01/app/oracle/diag/tnslsnr/87e2e6cb90fe/listener/alert/log.xml
db_1   | Listening on: (DESCRIPTION=(ADDRESS=(PROTOCOL=tcp)(HOST=0.0.0.0)(PORT=1521)))
db_1   | Listening on: (DESCRIPTION=(ADDRESS=(PROTOCOL=ipc)(KEY=EXTPROC1521)))
db_1   |
db_1   | Connecting to (DESCRIPTION=(ADDRESS=(PROTOCOL=TCP)(HOST=0.0.0.0)(PORT=1521)))
db_1   | STATUS of the LISTENER
db_1   | ------------------------
db_1   | Alias                     LISTENER
db_1   | Version                   TNSLSNR for Linux: Version 12.2.0.1.0 - Production
db_1   | Start Date                06-MAY-2021 09:06:28
db_1   | Uptime                    0 days 0 hr. 0 min. 3 sec
db_1   | Trace Level               off
db_1   | Security                  ON: Local OS Authentication
db_1   | SNMP                      OFF
db_1   | Listener Parameter File   /u01/app/oracle/product/12.2.0/dbhome_1/admin/ORCLCDB/listener.ora
db_1   | Listener Log File         /u01/app/oracle/diag/tnslsnr/87e2e6cb90fe/listener/alert/log.xml
db_1   | Listening Endpoints Summary...
db_1   |   (DESCRIPTION=(ADDRESS=(PROTOCOL=tcp)(HOST=0.0.0.0)(PORT=1521)))
db_1   |   (DESCRIPTION=(ADDRESS=(PROTOCOL=ipc)(KEY=EXTPROC1521)))
db_1   | The listener supports no services
db_1   | The command completed successfully
db_1   |
db_1   | DONE!
db_1   | Remove password info
db_1   | Docker DB configuration is complete !
db_1   | ERROR : config DB failed, please check log /home/oracle/setup/log/configDB.log for details!
db_1   | ORA-27301: OS failure message: No such file or directory
db_1   | ORA-27302: failure occurred at: parse failed
db_1   | ORA-27303: additional information: Filesystem     1K-blocks     Used Available Use% Mounted on
db_1   | overlay        263174212 93328860 156407196  38% /
db_1   | Image consistency checking encountered an error, checking disabled
db_1   | LICENSE_MAX_SESSION = 0
db_1   | LICENSE_SESSIONS_WARNING = 0
db_1   | Initial number of CPU is 8
db_1   | Number of processor cores in the system is 4
db_1   | Number of processor sockets in the system is 1
db_1   | Start up Oracle Database
db_1   | Thu May 6 09:11:25 UTC 2021
db_1   | start database
db_1   | start listener
db_1   | The database is ready for use .
db_1   | ORA-27301: OS failure message: No such file or directory
db_1   | ORA-27302: failure occurred at: parse failed
db_1   | ORA-27303: additional information: Filesystem     1K-blocks     Used Available Use% Mounted on
db_1   | overlay        263174212 93329288 156406768  38% /
db_1   | Image consistency checking encountered an error, checking disabled
db_1   | LICENSE_MAX_SESSION = 0
db_1   | LICENSE_SESSIONS_WARNING = 0
db_1   | Initial number of CPU is 8
db_1   | Number of processor cores in the system is 4
db_1   | Number of processor sockets in the system is 1
db_1   | Start up Oracle Database
db_1   | Thu May 6 09:14:44 UTC 2021
db_1   | start database
db_1   | start listener
db_1   | The database is ready for use .
db_1   | ORA-27301: OS failure message: No such file or directory
db_1   | ORA-27302: failure occurred at: parse failed
db_1   | ORA-27303: additional information: Filesystem     1K-blocks     Used Available Use% Mounted on
db_1   | overlay        263174212 93329336 156406720  38% /
db_1   | Image consistency checking encountered an error, checking disabled
db_1   | LICENSE_MAX_SESSION = 0
db_1   | LICENSE_SESSIONS_WARNING = 0
db_1   | Initial number of CPU is 8
db_1   | Number of processor cores in the system is 4
db_1   | Number of processor sockets in the system is 1
web_1  | Watching for file changes with StatReloader
web_1  | Performing system checks...
web_1  |
web_1  | System check identified no issues (0 silenced).
web_1  | Exception in thread django-main-thread:
web_1  | Traceback (most recent call last):
web_1  |   File "/usr/local/lib/python3.9/site-packages/django/db/backends/base/base.py", line 219, in ensure_connection
web_1  |     self.connect()
web_1  |   File "/usr/local/lib/python3.9/site-packages/django/utils/asyncio.py", line 26, in inner
web_1  |     return func(*args, **kwargs)
web_1  |   File "/usr/local/lib/python3.9/site-packages/django/db/backends/base/base.py", line 200, in connect
web_1  |     self.connection = self.get_new_connection(conn_params)
web_1  |   File "/usr/local/lib/python3.9/site-packages/django/utils/asyncio.py", line 26, in inner
web_1  |     return func(*args, **kwargs)
web_1  |   File "/usr/local/lib/python3.9/site-packages/django/db/backends/oracle/base.py", line 240, in get_new_connection
web_1  |     return Database.connect(
web_1  | cx_Oracle.DatabaseError: ORA-12541: TNS:no listener
web_1  |
web_1  | The above exception was the direct cause of the following exception:
web_1  |
web_1  | Traceback (most recent call last):
web_1  |   File "/usr/local/lib/python3.9/threading.py", line 954, in _bootstrap_inner
web_1  |     self.run()
web_1  |   File "/usr/local/lib/python3.9/threading.py", line 892, in run
web_1  |     self._target(*self._args, **self._kwargs)
web_1  |   File "/usr/local/lib/python3.9/site-packages/django/utils/autoreload.py", line 53, in wrapper
web_1  |     fn(*args, **kwargs)
web_1  |   File "/usr/local/lib/python3.9/site-packages/django/core/management/commands/runserver.py", line 121, in inner_run
web_1  |     self.check_migrations()
web_1  |   File "/usr/local/lib/python3.9/site-packages/django/core/management/base.py", line 459, in check_migrations
web_1  |     executor = MigrationExecutor(connections[DEFAULT_DB_ALIAS])
web_1  |   File "/usr/local/lib/python3.9/site-packages/django/db/migrations/executor.py", line 18, in __init__
web_1  |     self.loader = MigrationLoader(self.connection)
web_1  |   File "/usr/local/lib/python3.9/site-packages/django/db/migrations/loader.py", line 53, in __init__
web_1  |     self.build_graph()
web_1  |   File "/usr/local/lib/python3.9/site-packages/django/db/migrations/loader.py", line 216, in build_graph
web_1  |     self.applied_migrations = recorder.applied_migrations()
web_1  |   File "/usr/local/lib/python3.9/site-packages/django/db/migrations/recorder.py", line 77, in applied_migrations
web_1  |     if self.has_table():
web_1  |   File "/usr/local/lib/python3.9/site-packages/django/db/migrations/recorder.py", line 55, in has_table
web_1  |     with self.connection.cursor() as cursor:
web_1  |   File "/usr/local/lib/python3.9/site-packages/django/utils/asyncio.py", line 26, in inner
web_1  |     return func(*args, **kwargs)
web_1  |   File "/usr/local/lib/python3.9/site-packages/django/db/backends/base/base.py", line 259, in cursor
web_1  |     return self._cursor()
web_1  |   File "/usr/local/lib/python3.9/site-packages/django/db/backends/base/base.py", line 235, in _cursor
web_1  |     self.ensure_connection()
web_1  |   File "/usr/local/lib/python3.9/site-packages/django/utils/asyncio.py", line 26, in inner
web_1  |     return func(*args, **kwargs)
web_1  |   File "/usr/local/lib/python3.9/site-packages/django/db/backends/base/base.py", line 219, in ensure_connection
web_1  |     self.connect()
web_1  |   File "/usr/local/lib/python3.9/site-packages/django/db/utils.py", line 90, in __exit__
web_1  |     raise dj_exc_value.with_traceback(traceback) from exc_value
web_1  |   File "/usr/local/lib/python3.9/site-packages/django/db/backends/base/base.py", line 219, in ensure_connection
web_1  |     self.connect()
web_1  |   File "/usr/local/lib/python3.9/site-packages/django/utils/asyncio.py", line 26, in inner
web_1  |     return func(*args, **kwargs)
web_1  |   File "/usr/local/lib/python3.9/site-packages/django/db/backends/base/base.py", line 200, in connect
web_1  |     self.connection = self.get_new_connection(conn_params)
web_1  |   File "/usr/local/lib/python3.9/site-packages/django/utils/asyncio.py", line 26, in inner
web_1  |     return func(*args, **kwargs)
web_1  |   File "/usr/local/lib/python3.9/site-packages/django/db/backends/oracle/base.py", line 240, in get_new_connection
web_1  |     return Database.connect(
web_1  | django.db.utils.DatabaseError: ORA-12541: TNS:no listener
web_1  | Watching for file changes with StatReloader
web_1  | Performing system checks...
web_1  |
web_1  | System check identified no issues (0 silenced).
web_1  | Exception in thread django-main-thread:
web_1  | Traceback (most recent call last):
web_1  |   File "/usr/local/lib/python3.9/site-packages/django/db/backends/base/base.py", line 219, in ensure_connection
web_1  |     self.connect()
web_1  |   File "/usr/local/lib/python3.9/site-packages/django/utils/asyncio.py", line 26, in inner
web_1  |     return func(*args, **kwargs)
web_1  |   File "/usr/local/lib/python3.9/site-packages/django/db/backends/base/base.py", line 200, in connect
web_1  |     self.connection = self.get_new_connection(conn_params)
web_1  |   File "/usr/local/lib/python3.9/site-packages/django/utils/asyncio.py", line 26, in inner
web_1  |     return func(*args, **kwargs)
web_1  |   File "/usr/local/lib/python3.9/site-packages/django/db/backends/oracle/base.py", line 240, in get_new_connection
web_1  |     return Database.connect(
web_1  | cx_Oracle.DatabaseError: ORA-12541: TNS:no listener
web_1  |
web_1  | The above exception was the direct cause of the following exception:
web_1  |
web_1  | Traceback (most recent call last):
web_1  |   File "/usr/local/lib/python3.9/threading.py", line 954, in _bootstrap_inner
web_1  |     self.run()
web_1  |   File "/usr/local/lib/python3.9/threading.py", line 892, in run
web_1  |     self._target(*self._args, **self._kwargs)
web_1  |   File "/usr/local/lib/python3.9/site-packages/django/utils/autoreload.py", line 53, in wrapper
web_1  |     fn(*args, **kwargs)
web_1  |   File "/usr/local/lib/python3.9/site-packages/django/core/management/commands/runserver.py", line 121, in inner_run
web_1  |     self.check_migrations()
web_1  |   File "/usr/local/lib/python3.9/site-packages/django/core/management/base.py", line 459, in check_migrations
web_1  |     executor = MigrationExecutor(connections[DEFAULT_DB_ALIAS])
web_1  |   File "/usr/local/lib/python3.9/site-packages/django/db/migrations/executor.py", line 18, in __init__
web_1  |     self.loader = MigrationLoader(self.connection)
web_1  |   File "/usr/local/lib/python3.9/site-packages/django/db/migrations/loader.py", line 53, in __init__
web_1  |     self.build_graph()
web_1  |   File "/usr/local/lib/python3.9/site-packages/django/db/migrations/loader.py", line 216, in build_graph
web_1  |     self.applied_migrations = recorder.applied_migrations()
web_1  |   File "/usr/local/lib/python3.9/site-packages/django/db/migrations/recorder.py", line 77, in applied_migrations
web_1  |     if self.has_table():
web_1  |   File "/usr/local/lib/python3.9/site-packages/django/db/migrations/recorder.py", line 55, in has_table
web_1  |     with self.connection.cursor() as cursor:
web_1  |   File "/usr/local/lib/python3.9/site-packages/django/utils/asyncio.py", line 26, in inner
web_1  |     return func(*args, **kwargs)
web_1  |   File "/usr/local/lib/python3.9/site-packages/django/db/backends/base/base.py", line 259, in cursor
web_1  |     return self._cursor()
web_1  |   File "/usr/local/lib/python3.9/site-packages/django/db/backends/base/base.py", line 235, in _cursor
web_1  |     self.ensure_connection()
web_1  |   File "/usr/local/lib/python3.9/site-packages/django/utils/asyncio.py", line 26, in inner
web_1  |     return func(*args, **kwargs)
web_1  |   File "/usr/local/lib/python3.9/site-packages/django/db/backends/base/base.py", line 219, in ensure_connection
web_1  |     self.connect()
web_1  |   File "/usr/local/lib/python3.9/site-packages/django/db/utils.py", line 90, in __exit__
web_1  |     raise dj_exc_value.with_traceback(traceback) from exc_value
web_1  |   File "/usr/local/lib/python3.9/site-packages/django/db/backends/base/base.py", line 219, in ensure_connection
web_1  |     self.connect()
web_1  |   File "/usr/local/lib/python3.9/site-packages/django/utils/asyncio.py", line 26, in inner
web_1  |     return func(*args, **kwargs)
web_1  |   File "/usr/local/lib/python3.9/site-packages/django/db/backends/base/base.py", line 200, in connect
web_1  |     self.connection = self.get_new_connection(conn_params)
web_1  |   File "/usr/local/lib/python3.9/site-packages/django/utils/asyncio.py", line 26, in inner
web_1  |     return func(*args, **kwargs)
web_1  |   File "/usr/local/lib/python3.9/site-packages/django/db/backends/oracle/base.py", line 240, in get_new_connection
web_1  |     return Database.connect(
web_1  | django.db.utils.DatabaseError: ORA-12541: TNS:no listener
web_1  | Watching for file changes with StatReloader
web_1  | Performing system checks...
web_1  |
web_1  | System check identified no issues (0 silenced).
web_1  | Exception in thread django-main-thread:
web_1  | Traceback (most recent call last):
web_1  |   File "/usr/local/lib/python3.9/site-packages/django/db/backends/base/base.py", line 219, in ensure_connection
web_1  |     self.connect()
web_1  |   File "/usr/local/lib/python3.9/site-packages/django/utils/asyncio.py", line 26, in inner
web_1  |     return func(*args, **kwargs)
web_1  |   File "/usr/local/lib/python3.9/site-packages/django/db/backends/base/base.py", line 200, in connect
web_1  |     self.connection = self.get_new_connection(conn_params)
web_1  |   File "/usr/local/lib/python3.9/site-packages/django/utils/asyncio.py", line 26, in inner
web_1  |     return func(*args, **kwargs)
web_1  |   File "/usr/local/lib/python3.9/site-packages/django/db/backends/oracle/base.py", line 240, in get_new_connection
web_1  |     return Database.connect(
web_1  | cx_Oracle.DatabaseError: ORA-12541: TNS:no listener
web_1  |
web_1  | The above exception was the direct cause of the following exception:
web_1  |
web_1  | Traceback (most recent call last):
web_1  |   File "/usr/local/lib/python3.9/threading.py", line 954, in _bootstrap_inner
web_1  |     self.run()
web_1  |   File "/usr/local/lib/python3.9/threading.py", line 892, in run
web_1  |     self._target(*self._args, **self._kwargs)
web_1  |   File "/usr/local/lib/python3.9/site-packages/django/utils/autoreload.py", line 53, in wrapper
web_1  |     fn(*args, **kwargs)
web_1  |   File "/usr/local/lib/python3.9/site-packages/django/core/management/commands/runserver.py", line 121, in inner_run
web_1  |     self.check_migrations()
web_1  |   File "/usr/local/lib/python3.9/site-packages/django/core/management/base.py", line 459, in check_migrations
web_1  |     executor = MigrationExecutor(connections[DEFAULT_DB_ALIAS])
web_1  |   File "/usr/local/lib/python3.9/site-packages/django/db/migrations/executor.py", line 18, in __init__
web_1  |     self.loader = MigrationLoader(self.connection)
web_1  |   File "/usr/local/lib/python3.9/site-packages/django/db/migrations/loader.py", line 53, in __init__
web_1  |     self.build_graph()
web_1  |   File "/usr/local/lib/python3.9/site-packages/django/db/migrations/loader.py", line 216, in build_graph
web_1  |     self.applied_migrations = recorder.applied_migrations()
web_1  |   File "/usr/local/lib/python3.9/site-packages/django/db/migrations/recorder.py", line 77, in applied_migrations
web_1  |     if self.has_table():
web_1  |   File "/usr/local/lib/python3.9/site-packages/django/db/migrations/recorder.py", line 55, in has_table
web_1  |     with self.connection.cursor() as cursor:
web_1  |   File "/usr/local/lib/python3.9/site-packages/django/utils/asyncio.py", line 26, in inner
web_1  |     return func(*args, **kwargs)
web_1  |   File "/usr/local/lib/python3.9/site-packages/django/db/backends/base/base.py", line 259, in cursor
web_1  |     return self._cursor()
web_1  |   File "/usr/local/lib/python3.9/site-packages/django/db/backends/base/base.py", line 235, in _cursor
web_1  |     self.ensure_connection()
web_1  |   File "/usr/local/lib/python3.9/site-packages/django/utils/asyncio.py", line 26, in inner
web_1  |     return func(*args, **kwargs)
web_1  |   File "/usr/local/lib/python3.9/site-packages/django/db/backends/base/base.py", line 219, in ensure_connection
web_1  |     self.connect()
web_1  |   File "/usr/local/lib/python3.9/site-packages/django/db/utils.py", line 90, in __exit__
web_1  |     raise dj_exc_value.with_traceback(traceback) from exc_value
web_1  |   File "/usr/local/lib/python3.9/site-packages/django/db/backends/base/base.py", line 219, in ensure_connection
web_1  |     self.connect()
web_1  |   File "/usr/local/lib/python3.9/site-packages/django/utils/asyncio.py", line 26, in inner
web_1  |     return func(*args, **kwargs)
web_1  |   File "/usr/local/lib/python3.9/site-packages/django/db/backends/base/base.py", line 200, in connect
web_1  |     self.connection = self.get_new_connection(conn_params)
web_1  |   File "/usr/local/lib/python3.9/site-packages/django/utils/asyncio.py", line 26, in inner
web_1  |     return func(*args, **kwargs)
web_1  |   File "/usr/local/lib/python3.9/site-packages/django/db/backends/oracle/base.py", line 240, in get_new_connection
web_1  |     return Database.connect(
web_1  | django.db.utils.DatabaseError: ORA-12541: TNS:no listener
web_1  | Watching for file changes with StatReloader
web_1  | Performing system checks...
web_1  |
web_1  | System check identified no issues (0 silenced).
web_1  | Exception in thread django-main-thread:
web_1  | Traceback (most recent call last):
web_1  |   File "/usr/local/lib/python3.9/site-packages/django/db/backends/base/base.py", line 219, in ensure_connection
web_1  |     self.connect()
web_1  |   File "/usr/local/lib/python3.9/site-packages/django/utils/asyncio.py", line 26, in inner
web_1  |     return func(*args, **kwargs)
web_1  |   File "/usr/local/lib/python3.9/site-packages/django/db/backends/base/base.py", line 200, in connect
web_1  |     self.connection = self.get_new_connection(conn_params)
web_1  |   File "/usr/local/lib/python3.9/site-packages/django/utils/asyncio.py", line 26, in inner
web_1  |     return func(*args, **kwargs)
web_1  |   File "/usr/local/lib/python3.9/site-packages/django/db/backends/oracle/base.py", line 240, in get_new_connection
web_1  |     return Database.connect(
web_1  | cx_Oracle.DatabaseError: ORA-12541: TNS:no listener
web_1  |
web_1  | The above exception was the direct cause of the following exception:
web_1  |
web_1  | Traceback (most recent call last):
web_1  |   File "/usr/local/lib/python3.9/threading.py", line 954, in _bootstrap_inner
web_1  |     self.run()
web_1  |   File "/usr/local/lib/python3.9/threading.py", line 892, in run
web_1  |     self._target(*self._args, **self._kwargs)
web_1  |   File "/usr/local/lib/python3.9/site-packages/django/utils/autoreload.py", line 53, in wrapper
web_1  |     fn(*args, **kwargs)
web_1  |   File "/usr/local/lib/python3.9/site-packages/django/core/management/commands/runserver.py", line 121, in inner_run
web_1  |     self.check_migrations()
web_1  |   File "/usr/local/lib/python3.9/site-packages/django/core/management/base.py", line 459, in check_migrations
web_1  |     executor = MigrationExecutor(connections[DEFAULT_DB_ALIAS])
web_1  |   File "/usr/local/lib/python3.9/site-packages/django/db/migrations/executor.py", line 18, in __init__
web_1  |     self.loader = MigrationLoader(self.connection)
web_1  |   File "/usr/local/lib/python3.9/site-packages/django/db/migrations/loader.py", line 53, in __init__
web_1  |     self.build_graph()
web_1  |   File "/usr/local/lib/python3.9/site-packages/django/db/migrations/loader.py", line 216, in build_graph
web_1  |     self.applied_migrations = recorder.applied_migrations()
web_1  |   File "/usr/local/lib/python3.9/site-packages/django/db/migrations/recorder.py", line 77, in applied_migrations
web_1  |     if self.has_table():
web_1  |   File "/usr/local/lib/python3.9/site-packages/django/db/migrations/recorder.py", line 55, in has_table
web_1  |     with self.connection.cursor() as cursor:
web_1  |   File "/usr/local/lib/python3.9/site-packages/django/utils/asyncio.py", line 26, in inner
web_1  |     return func(*args, **kwargs)
web_1  |   File "/usr/local/lib/python3.9/site-packages/django/db/backends/base/base.py", line 259, in cursor
web_1  |     return self._cursor()
web_1  |   File "/usr/local/lib/python3.9/site-packages/django/db/backends/base/base.py", line 235, in _cursor
web_1  |     self.ensure_connection()
web_1  |   File "/usr/local/lib/python3.9/site-packages/django/utils/asyncio.py", line 26, in inner
web_1  |     return func(*args, **kwargs)
web_1  |   File "/usr/local/lib/python3.9/site-packages/django/db/backends/base/base.py", line 219, in ensure_connection
web_1  |     self.connect()
web_1  |   File "/usr/local/lib/python3.9/site-packages/django/db/utils.py", line 90, in __exit__
web_1  |     raise dj_exc_value.with_traceback(traceback) from exc_value
web_1  |   File "/usr/local/lib/python3.9/site-packages/django/db/backends/base/base.py", line 219, in ensure_connection
web_1  |     self.connect()
web_1  |   File "/usr/local/lib/python3.9/site-packages/django/utils/asyncio.py", line 26, in inner
web_1  |     return func(*args, **kwargs)
web_1  |   File "/usr/local/lib/python3.9/site-packages/django/db/backends/base/base.py", line 200, in connect
web_1  |     self.connection = self.get_new_connection(conn_params)
web_1  |   File "/usr/local/lib/python3.9/site-packages/django/utils/asyncio.py", line 26, in inner
web_1  |     return func(*args, **kwargs)
web_1  |   File "/usr/local/lib/python3.9/site-packages/django/db/backends/oracle/base.py", line 240, in get_new_connection
web_1  |     return Database.connect(
web_1  | django.db.utils.DatabaseError: ORA-12541: TNS:no listener
```

**Comment by AmedeeBulle** [comment]
In containers, `localhost` is the container itself, not the host interface, so 

```
        'HOST': 'localhost',
        'PORT': '1523',
```

won't connect to anything.

When you use `docker-compse`,  compose will setup a network and a DNS for the services. In principle, you don't have to expose port `1521` to the host (unless you want to for other duties), and the connection parameters from the `web` container should be:
 
```
        'HOST': 'db',
        'PORT': '1521',
```

**Comment by AmedeeBulle** [comment]
You also need to make sure that the database is running  before tying to connect. The `depends on` is not enough as it only checks that the container is up.

I can't help much on the Django side, but from a pure database perspective I can show the setup works with the following compose file (no port needs to be exposed for the database):

```yaml
version: '3'
services:
    db:
      image: oracledb:12.2.0.1
      restart: "unless-stopped"
      volumes:
        - ./setup-scripts:/opt/oracle/scripts/setup
        - ./oradata:/opt/oracle/oradata
      environment:
        - ORACLE_PWD=Change0nInstall
    app:
      build: app
      command: python3 /app/time.py
      depends_on:
          - db
```

The app is a simple python script which connects to the DB:

Dockerfile:

```dockerfile
FROM ghcr.io/oracle/oraclelinux7-python:3.6-oracledb

WORKDIR /app

ENV PYTHONUNBUFFERED 1

COPY ./time.py /app/time.py
```

time.py -- uses `db` to connect on the default port (1521):
```python
#!/usr/bin/env python3
import time
import cx_Oracle

connection = None
while not connection:
    try:
        connection = cx_Oracle.connect(
            user="system",
            password="Change0nInstall",
            dsn="db/ORCLCDB")
    except cx_Oracle.DatabaseError as e:
        err, = e.args
        print(f"Database Error while connecting: {err.message}")
        time.sleep(10)
print("Successfully connected to Oracle Database")

cursor = connection.cursor()
while True:
    cursor.execute("select sysdate from dual")
    row = cursor.fetchone()
    sysdate, = row
    print(f"Database date is {sysdate}")
    time.sleep(10)
```

Then we have:
```
$ docker-compose up 
Creating network "12c-compose_default" with the default driver                                     
Creating 12c-compose_db_1 ... done                                                             
Creating 12c-compose_app_1 ... done
Attaching to 12c-compose_db_1, 12c-compose_app_1
db_1   |
db_1   | LSNRCTL for Linux: Version 12.2.0.1.0 - Production on 06-MAY-2021 18:47:56
db_1   |
db_1   | Copyright (c) 1991, 2016, Oracle.  All rights reserved.
db_1   |
db_1   | Starting /opt/oracle/product/12.2.0.1/dbhome_1/bin/tnslsnr: please wait...
db_1   |
db_1   | TNSLSNR for Linux: Version 12.2.0.1.0 - Production
db_1   | System parameter file is /opt/oracle/product/12.2.0.1/dbhome_1/network/admin/listener.ora
db_1   | Log messages written to /opt/oracle/diag/tnslsnr/5aad06fe3e66/listener/alert/log.xml
db_1   | Listening on: (DESCRIPTION=(ADDRESS=(PROTOCOL=ipc)(KEY=EXTPROC1)))
db_1   | Listening on: (DESCRIPTION=(ADDRESS=(PROTOCOL=tcp)(HOST=0.0.0.0)(PORT=1521)))

<SNIP>

db_1   | Connected to an idle instance.
db_1   |
app_1  | Database Error while connecting: ORA-12514: TNS:listener does not currently know of service requested in connect descriptor
db_1   | SQL> ORACLE instance started.
db_1   |
db_1   | Total System Global Area 1610612736 bytes
db_1   | Fixed Size                 8793304 bytes
db_1   | Variable Size            520094504 bytes
db_1   | Database Buffers        1073741824 bytes
db_1   | Redo Buffers               7983104 bytes
db_1   | Database mounted.
app_1  | Successfully connected to Oracle Database
app_1  | Database date is 2021-05-06 18:50:40
...
```

**Comment by zarif98sjs** [comment]
@AmedeeBulle Is there any definitive way to make sure that  the database is running before tying to connect. As you said `depends on` is not enough as it only checks that the container is up

**Comment by AmedeeBulle** [comment]
Not really...

You can easily find wait scripts (docker-compose-wait, wait-for-it, ...) used as entry point which will wait until a port is available, but this doesn't help in this case as the listener port will be up before the database is operational.

Best is to use a a simple script (like the first half of my sample above) which loops until the database is available.
Maybe `django-probes` can be used as an alternative.

Tagging @gvenzl from the DB team to see if he has a better idea...
