### ISSUE TITLE
Error when trying to run image Oracle Fusion Middleware Infrastructure 12.2.1.4 

### ISSUE THREAD

**Issue by tlemoing** [oracle/docker-images#2026]
Hi,
   
  When trying to run image Oracle Fusion Middleware Infrastructure 12.2.1.4, I have an error com.oracle.cie.domain.script.jython.WLSTException: com.oracle.cie.domain.script.jython.WLSTException: ServerStartMode can only be either "dev", "prod" or "secure"

Below is the trace of the bash execution

Thanks
Best regards
Thierry

Domain Home is:  /u01/oracle/user_projects/domains/myinfraDomain
Configuring Domain for first time
Start the Admin and Managed Servers
=====================================
CONNECTION_STRING=InfraDB:1521/InfraPDB1
RCUPREFIX=INFRA01
DOMAIN_NAME=myinfraDomain
DOMAIN_HOME=/u01/oracle/user_projects/domains/myinfraDomain
Loading RCU Phase
=================
CONNECTION_STRING=InfraDB:1521/InfraPDB1
RCUPREFIX=INFRA01
jdbc_url=jdbc:oracle:thin:@InfraDB:1521/InfraPDB1
Creating Domain 1st execution
Loading SOA RCU into database
RCU has some error
RCU has already loaded schemas into the Database
RCU Ignore error
Domain Configuration Phase
==========================

Initializing WebLogic Scripting Tool (WLST) ...

Welcome to WebLogic Server Administration Scripting Shell

Type help() for help on available commands

sys.argv[0] = /u01/oracle/container-scripts/createInfraDomain.py
sys.argv[1] = -oh
sys.argv[2] = /u01/oracle
sys.argv[3] = -jh
sys.argv[4] = /u01/jdk
sys.argv[5] = -parent
sys.argv[6] = /u01/oracle/user_projects/domains
sys.argv[7] = -name
sys.argv[8] = myinfraDomain
sys.argv[9] = -user
sys.argv[10] = weblogic
sys.argv[11] = -password
sys.argv[12] = Manager12
sys.argv[13] = -rcuDb
sys.argv[14] = InfraDB:1521/InfraPDB1
sys.argv[15] = -rcuPrefix
sys.argv[16] = INFRA01
sys.argv[17] = -rcuSchemaPwd
sys.argv[18] = Oradoc_db1
sys.argv[19] = -adminListenPort
sys.argv[20] = 7001
sys.argv[21] = -adminName
sys.argv[22] = myadmin
sys.argv[23] = -adminPortEnabled
sys.argv[24] = false
sys.argv[25] = -administrationPort
sys.argv[26] = 9002
sys.argv[27] = -managedName
sys.argv[28] = infraServer1
sys.argv[29] = -managedServerPort
sys.argv[30] = 8001
sys.argv[31] = -prodMode
sys.argv[32] = dev
prodMode = dev
Error: setOption() failed. Do dumpStack() to see details.
Error: runCmd() failed. Do dumpStack() to see details.
Problem invoking WLST - Traceback (innermost last):
  File "/u01/oracle/container-scripts/createInfraDomain.py", line 309, in ?
  File "/u01/oracle/container-scripts/createInfraDomain.py", line 46, in createInfraDomain
  File "/u01/oracle/container-scripts/createInfraDomain.py", line 56, in createBaseDomain
  File "/tmp/WLSTOfflineIni2565586074186487770.py", line 84, in setOption
  File "/tmp/WLSTOfflineIni2565586074186487770.py", line 19, in command
        at com.oracle.cie.domain.script.jython.CommandExceptionHandler.handleException(CommandExceptionHandler.java:69)
        at com.oracle.cie.domain.script.jython.WLScriptContext.handleException(WLScriptContext.java:3085)
        at com.oracle.cie.domain.script.jython.WLScriptContext.runCmd(WLScriptContext.java:738)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)

com.oracle.cie.domain.script.jython.WLSTException: com.oracle.cie.domain.script.jython.WLSTException: ServerStartMode can only be either "dev", "prod" or "secure"

RetVal from Domain creation 1
Domain Creation Failed.. Please check the Domain Logs

**Comment by tlemoing** [comment]
I find my problem
Replace CRLF by LF in the properties files
