### ISSUE TITLE
OracleRestDataServices: allow advanced installation for multitenant pluggable databases

### ISSUE THREAD

**Issue by hitrov** [oracle/docker-images#2037]
Hi.

Before using the container I successfully installed REST services using local JDK (with SQL Developer and all the stuff)
```bash
java -jar ords.war install advanced
```
if I use already defined config as a volume map for the container
```bash
# docker run --name ords --network dbnet -p 8888:8888 -e ORACLE_HOST=prebuildee -e ORACLE_PORT=1521 -e ORACLE_SERVICE=ORCLPDB1 -e ORACLE_PWD=oracle -e ORDS_PWD=*** -e CONTEXT_ROOT=ords -v /root/ords-config-data/ords:/opt/oracle/ords/config/ords oracle/restdataservices:21.2.0
2021-07-29T14:13:46.387Z INFO        HTTP and HTTP/2 cleartext listening on host: localhost port: 8888
2021-07-29T14:13:46.411Z INFO        Disabling document root because the specified folder does not exist: /root/ords-config-data/ords/standalone/doc_root
2021-07-29T14:13:48.526Z INFO        Configuration properties for: |apex|pu|
cache.caching=false
cache.directory=/tmp/apex/cache
cache.duration=days
cache.expiration=7
cache.maxEntries=500
cache.monitorInterval=60
cache.procedureNameList=
cache.type=lru
database.api.enabled=true
db.connectionType=basic
db.hostname=prebuildee
db.port=1521
db.servicename=ORCLPDB1
debug.debugger=false
debug.printDebugToScreen=false
error.keepErrorMessages=true
error.maxEntries=50
feature.sdw=true
jdbc.DriverType=thin
jdbc.InactivityTimeout=1800
jdbc.InitialLimit=3
jdbc.MaxConnectionReuseCount=1000
jdbc.MaxLimit=10
jdbc.MaxStatementsLimit=10
jdbc.MinLimit=1
jdbc.statementTimeout=900
log.logging=false
log.maxEntries=50
misc.compress=
misc.defaultPage=apex
restEnabledSql.active=true
security.disableDefaultExclusionList=false
security.maxEntries=2000
db.password=******
db.username=ORDS_PUBLIC_USER
resource.templates.enabled=true

2021-07-29T14:13:48.529Z WARNING     *** jdbc.MaxLimit in configuration |apex|pu| is using a value of 10, this setting may not be sized adequately for a production environment ***
2021-07-29T14:13:48.530Z WARNING     *** jdbc.InitialLimit in configuration |apex|pu| is using a value of 3, this setting may not be sized adequately for a production environment ***
2021-07-29T14:13:52.250Z INFO        Oracle REST Data Services initialized
Oracle REST Data Services version : 21.2.0.r1741826
Oracle REST Data Services server info: jetty/9.4.42.v20210604
```
then everything's working.

but I always get 404 in a browser when REST services are not configured yet - when I wanna use container for this purpose.
as well as an exception when running standalone web server.

```bash
# docker run --name ords --network dbnet -p 8888:8888 -e ORACLE_HOST=prebuildee -e ORACLE_PORT=1521 -e ORACLE_SERVICE=ORCLPDB1 -e ORACLE_PWD=oracle -e ORDS_PWD=*** -e CONTEXT_ROOT=ords oracle/restdataservices:21.2.0                                                    Requires to login with administrator privileges to verify Oracle REST Data Services schema.

Connecting to database user: SYS AS SYSDBA url: jdbc:oracle:thin:@//prebuildee:1521/ORCLPDB1

Retrieving information.
Enter a number to select a feature to enable:
   [1] SQL Developer Web  (Enables all features)
   [2] REST Enabled SQL
   [3] Database API
   [4] REST Enabled SQL and Database API
   [5] None
Choose [1]:Exception in thread "main" java.lang.reflect.InvocationTargetException
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:567)
        at oracle.dbtools.jarcl.Entrypoint.invoke(Entrypoint.java:66)
        at oracle.dbtools.jarcl.Entrypoint.main(Entrypoint.java:77)
Caused by: java.io.IOError: java.io.EOFException
        at oracle.dbtools.common.util.Console$1.readLine(Console.java:97)
        at oracle.dbtools.installer.config.Setting.prompt(Setting.java:53)
        at oracle.dbtools.installer.config.Setting.prompt(Setting.java:31)
        at oracle.dbtools.installer.config.SetupFeature.featureConfig(SetupFeature.java:68)
        at oracle.dbtools.installer.config.SetupFeature.featureConf(SetupFeature.java:48)
        at oracle.dbtools.installer.config.Setup.execute(Setup.java:182)
        at oracle.dbtools.cmdline.DefaultCommand.execute(DefaultCommand.java:120)
        at oracle.dbtools.cmdline.Commands.execute(Commands.java:226)
        at oracle.dbtools.cmdline.Commands.main(Commands.java:177)
        at oracle.dbtools.cmdline.Commands.main(Commands.java:411)
        ... 6 more
Caused by: java.io.EOFException
        at oracle.dbtools.common.util.Console$1.readLine(Console.java:130)
        at oracle.dbtools.common.util.Console$1.readLine(Console.java:95)
        ... 15 more
2021-07-29T14:20:06.046Z INFO        HTTP and HTTP/2 cleartext listening on host: localhost port: 8888
2021-07-29T14:20:06.111Z INFO        The document root is serving static resources located in: /opt/oracle/ords/doc_root
2021-07-29T14:20:07.209Z INFO        No pools configured yet
2021-07-29T14:20:08.707Z INFO        Oracle REST Data Services initialized
Oracle REST Data Services version : 21.2.0.r1741826
Oracle REST Data Services server info: jetty/9.4.42.v20210604
```

![ords-404](https://user-images.githubusercontent.com/26094610/127505844-1f8acfcf-c607-40aa-94e7-8f6ab71a9dfe.png)

I tried to modify Dockerfile and add `advanced`, it didn't help me.

That's what I expect running against the DB without REST services enabled
```bash
# java -jar ords.war install advanced
Specify the database connection type to use.
Enter number for [1] Basic  [2] TNS  [3] Custom URL [1]:1
Enter the name of the database server [localhost]:
Enter the database listen port [1521]:
Enter 1 to specify the database service name, or 2 to specify the database SID [1]:
Enter the database service name:ORCLPDB1
Enter 1 if you want to verify/install Oracle REST Data Services schema or 2 to skip this step [1]:
Enter the database password for ORDS_PUBLIC_USER:
Confirm password:
Requires to login with administrator privileges to verify Oracle REST Data Services schema.

Enter the administrator username:SYS AS SYSDBA
Enter the database password for SYS AS SYSDBA:
Confirm password:
Connecting to database user: SYS AS SYSDBA url: jdbc:oracle:thin:@//localhost:1521/ORCLPDB1

Retrieving information.
Enter the default tablespace for ORDS_METADATA [SYSAUX]:
Enter the temporary tablespace for ORDS_METADATA [TEMP]:
Enter the default tablespace for ORDS_PUBLIC_USER [SYSAUX]:
Enter the temporary tablespace for ORDS_PUBLIC_USER [TEMP]:
Enter 1 if you want to use PL/SQL Gateway or 2 to skip this step.
If using Oracle Application Express or migrating from mod_plsql then you must enter 1 [1]:2
Enter a number to select a feature to enable:
   [1] SQL Developer Web  (Enables all features)
   [2] REST Enabled SQL
   [3] Database API
   [4] REST Enabled SQL and Database API
   [5] None
Choose [1]:
2021-07-28T20:16:57.913Z INFO        reloaded pools: []
Installing Oracle REST Data Services version 21.2.0.r1741826
... Log file written to /root/ords_install_core_2021-07-28_221658_00061.log
Warning: Nashorn engine is planned to be removed from a future JDK release
... Verified database prerequisites
... Created Oracle REST Data Services proxy user
... Created Oracle REST Data Services schema
... Granted privileges to Oracle REST Data Services
... Created Oracle REST Data Services database objects
... Log file written to /root/ords_install_datamodel_2021-07-28_221715_00056.log
... Log file written to /root/ords_install_apex_2021-07-28_221716_00329.log
Completed installation for Oracle REST Data Services version 21.2.0.r1741826. Elapsed time: 00:00:19.493

Enter 1 if you wish to start in standalone mode or 2 to exit [1]
```
![sql-dev-working](https://user-images.githubusercontent.com/26094610/127506856-5cbc790b-826a-4566-9463-f7d1eb1884fb.png)

That's all I have in config dir
```bash
# cat ords-config-data/defaults.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE properties SYSTEM "http://java.sun.com/dtd/properties.dtd">
<properties>
<comment>Saved on Thu Jul 29 13:58:13 UTC 2021</comment>
<entry key="cache.caching">false</entry>
<entry key="cache.directory">/tmp/apex/cache</entry>
<entry key="cache.duration">days</entry>
<entry key="cache.expiration">7</entry>
<entry key="cache.maxEntries">500</entry>
<entry key="cache.monitorInterval">60</entry>
<entry key="cache.procedureNameList"></entry>
<entry key="cache.type">lru</entry>
<entry key="debug.debugger">false</entry>
<entry key="debug.printDebugToScreen">false</entry>
<entry key="error.keepErrorMessages">true</entry>
<entry key="error.maxEntries">50</entry>
<entry key="jdbc.DriverType">thin</entry>
<entry key="jdbc.InactivityTimeout">1800</entry>
<entry key="jdbc.InitialLimit">3</entry>
<entry key="jdbc.MaxConnectionReuseCount">1000</entry>
<entry key="jdbc.MaxLimit">10</entry>
<entry key="jdbc.MaxStatementsLimit">10</entry>
<entry key="jdbc.MinLimit">1</entry>
<entry key="jdbc.statementTimeout">900</entry>
<entry key="log.logging">false</entry>
<entry key="log.maxEntries">50</entry>
<entry key="misc.compress"></entry>
<entry key="misc.defaultPage">apex</entry>
<entry key="security.disableDefaultExclusionList">false</entry>
<entry key="security.maxEntries">2000</entry>
</properties>
```

```bash
# cat ords-config-data/standalone/standalone.properties
jetty.port=8888
standalone.access.log=/tmp/ords_log
standalone.context.path=/ords
standalone.doc.root=/opt/oracle/ords/doc_root
standalone.scheme.do.not.prompt=true
standalone.static.context.path=/i
standalone.static.do.not.prompt=true
standalone.static.path=/opt/oracle/ords/doc_root/i
```

```bash
# cat ords-config-data/ords/conf/apex_pu.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE properties SYSTEM "http://java.sun.com/dtd/properties.dtd">
<properties>
<comment>Saved on Thu Jul 29 16:07:39 CEST 2021</comment>
<entry key="db.password">***</entry>
<entry key="db.username">ORDS_PUBLIC_USER</entry>
</properties>

```

**Comment by cmolinah** [comment]
I'm having the same issue with ORDS 21.3.1. Is there any workaround? any other version that is working?

**Comment by admuro** [comment]
Hi @hitrov ,

I tried to reproduce your error, first create an environment "A" with Oracle DB 19c and install ORDS. Then I have copied  ORDS configuration from environment "A" to main computer and start a new container "B" with OracleRestDataServices image mapping the same configuration used on evironment "A."

And I have no problem trying to access to the container "B":
http://127.0.0.1:8181/ords/pdbdba/sign-in/  

Please provide what URL are you trying to load and if is mapped to a valid REST services.

Regards

**Comment by hitrov** [comment]
Hi @admuro I tried again and it worked! thanks for that
