### ISSUE TITLE
WLSTException:No element NMProperty is found

### ISSUE THREAD

**Issue by cyluxx** [oracle/docker-images#225]
Hello,

Something went wrong with wlst trying to set nodemanager properties. I'm trying to build a 1221-Domain Image and I must admit that I had changed some domain-properties, but nothing serious. This error occurs in "create-wls-domain.py". Where can I find any documentation about NMProperties? It seems that the Oracle documentation does not include this keyword and I'm not sure how to use it.

```
Error: cd() failed. Do dumpStack() to see details.
Problem invoking WLST - Traceback (innermost last):
  File "/u01/oracle/create-wls-domain.py", line 50, in ?
  File "/tmp/WLSTOfflineIni7353917435542547309.py", line 21, in cd
        at com.oracle.cie.domain.script.jython.CommandExceptionHandler.handleException(CommandExceptionHandler.java:51)
        at com.oracle.cie.domain.script.jython.WLScriptContext.handleException(WLScriptContext.java:1538)
        at com.oracle.cie.domain.script.jython.WLScriptContext.cd(WLScriptContext.java:602)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
com.oracle.cie.domain.script.jython.WLSTException: com.oracle.cie.domain.script.jython.WLSTException: com.oracle.cie.domain.script.ScriptException: No element NMProperty is found
```

**Comment by brunoborges** [comment]
Hi @cyluxx, I'd say this is an issue with your customized WLST, not with the samples nor Dockerfiles we have in this project. I suggest you post your question to either [StackOverflow](http://stackoverflow.com/tags/weblogic) (with the `weblogic` tag), or to post to the [Oracle Community](https://community.oracle.com/community/fusion_middleware/weblogic/) website.
