### ISSUE TITLE
docker build -t 12212-medrec . fails insufficient tmp space

### ISSUE THREAD

**Issue by steveswing** [oracle/docker-images#418]
I'm experiencing the following error trying to do docker build -t 12212-medrec .
```
$ docker --log-level=debug build -t 12212-medrec .
time="2017-06-15T12:07:12-04:00" level=debug msg="Trusting certs with subjects: [<redacted>]"
Sending build context to Docker daemon 235.4 MB
Step 1/14 : FROM oracle/weblogic:12.2.1.2-developer
 ---> acb28d731cdd
Step 2/14 : MAINTAINER Monica Riccelli <monica.riccelli@oracle.com>
 ---> Using cache
 ---> 63f8d9600f08
Step 3/14 : ENV FMW_PKG "fmw_12.2.1.2.0_wls_supplemental_quick_Disk1_1of1.zip" FMW_JAR "fmw_12.2.1.2.0_wls_supplemental_quick.jar" MW_HOME "$ORACLE_HOME" PATH "$ORACLE_HOME/wlserver/server/bin:$O
RACLE_HOME/wlserver/../oracle_common/modules/org.apache.ant_1.9.2/bin:$JAVA_HOME/jre/bin:$JAVA_HOME/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:$ORACLE_HOME/oracle_common/com
mon/bin:$ORACLE_HOME/wlserver/common/bin:$ORACLE_HOME/user_projects/domains/medrec/bin:$ORACLE_HOME/wlserver/samples/server/medrec/:$ORACLE_HOME/wlserver/samples/server/:$ORACLE_HOME/wlserver/../
oracle_common/modules/org.apache.maven_3.2.5/bin"
 ---> Using cache
 ---> 362557adf082
Step 4/14 : COPY $FMW_PKG /u01/
 ---> Using cache
 ---> 1dc1f6a903f9
Step 5/14 : USER root
 ---> Using cache
 ---> bec1f71597c2
Step 6/14 : COPY startSample.sh /u01/oracle/
 ---> Using cache
 ---> 52eb4199be17
Step 7/14 : RUN chmod +xr /u01/oracle/startSample.sh
 ---> Using cache
 ---> 2d26c719e1b9
Step 8/14 : USER oracle
 ---> Using cache
 ---> f86e7755c983
Step 9/14 : RUN cd /u01 && $JAVA_HOME/bin/jar xf /u01/$FMW_PKG && cd - &&     $JAVA_HOME/bin/java -jar /u01/$FMW_JAR  ORACLE_HOME=$ORACLE_HOME &&     echo $USER &&     mv /u01/oracle/startSample.
sh /u01/oracle/wlserver/samples/server/  &&     rm /u01/$FMW_PKG /u01/$FMW_JAR
 ---> Running in c77c2ca5381f
Java HotSpot(TM) 64-Bit Server VM warning: Insufficient space for shared memory file:
   5
Try using the -Djava.io.tmpdir= option to select an alternate temp location.

java.io.IOException: No space left on device
        at java.io.FileOutputStream.writeBytes(Native Method)
        at java.io.FileOutputStream.write(FileOutputStream.java:326)
        at sun.tools.jar.Main.copy(Main.java:880)
        at sun.tools.jar.Main.copy(Main.java:911)
        at sun.tools.jar.Main.extractFile(Main.java:1069)
        at sun.tools.jar.Main.extract(Main.java:981)
        at sun.tools.jar.Main.run(Main.java:311)
        at sun.tools.jar.Main.main(Main.java:1288)
The command '/bin/sh -c cd /u01 && $JAVA_HOME/bin/jar xf /u01/$FMW_PKG && cd - &&     $JAVA_HOME/bin/java -jar /u01/$FMW_JAR  ORACLE_HOME=$ORACLE_HOME &&     echo $USER &&     mv /u01/oracle/star
tSample.sh /u01/oracle/wlserver/samples/server/  &&     rm /u01/$FMW_PKG /u01/$FMW_JAR' returned a non-zero code: 1
```
```
$ docker --version
Docker version 1.11.2, build b9f10c9
```
Note: the docker for windows version I'm using the sudo command is not available.
```
$ sudo docker build -t 12212-medrec .
bash: sudo: command not found
```
```
$ docker info
Containers: 43
 Running: 0
 Paused: 0
 Stopped: 43
Images: 258
Server Version: 17.03.0-ce
Storage Driver: aufs
 Root Dir: /mnt/sda1/var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 227
 Dirperm1 Supported: true
Execution Driver: <not supported>
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
Kernel Version: 4.4.52-boot2docker
Operating System: Boot2Docker 17.03.0-ce (TCL 7.2); HEAD : f11a204 - Thu Mar  2 00:14:47 UTC 2017
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 1.955 GiB
Name: default
ID: 
Docker Root Dir: /mnt/sda1/var/lib/docker
Debug mode (client): false
Debug mode (server): true
 File Descriptors: 18
 Goroutines: 27
 System Time: 2017-06-15T16:08:32.824558938Z
 EventsListeners: 0
Http Proxy: <redacted>
Https Proxy: <redacted>
No Proxy: 192.168.99.1/24,127.0.0.1
Registry: https://index.docker.io/v1/
Labels:
 provider=virtualbox

```

**Comment by steveswing** [comment]
I resolved this by freeing up disk space locally by removing images having no associated container.
One command I used:
```
docker rmi $(docker images | grep "^<none>" | awk '{print $3}')
```
This will remove unused images also:
```
docker images -aq -f 'dangling=true' | xargs docker rmi
```
If you still have the problem you can look for
```
docker volume ls -f 'dangling=true'
```
