### ISSUE TITLE
Configuration of Oracle Fusion Middleware failing

### ISSUE THREAD

**Issue by TBrannan** [oracle/docker-images#524]
I am having a problem with Oracle Fusion Middleware failing.
I am very new to this so I might be putting in bad parameters, any help is appreciated!

```
docker run --name bi --network=bi_net -p 9500:9500 -p 9502:9502 -e ADMIN_USERNAME=weblogic -e ADMIN_PASSWORD=welcome1 -e DB_HOST=database -e DB_PORT=1521 -e DB_SERVICE=ORCLPDB1 -e DB_USERNAME=sys -e DB_PASSWORD=Admin123 -e SCHEMA_PREFIX=DEV -e SCHEMA_PASSWORD=Welcome1 -it 9fe63c0536da
Starting Fusion Middleware Configuration Wizard for BIEE
ORACLE_HOME set as /u01/oracle
BI_PRODUCT_HOME set as /u01/oracle/bi
PATH set as /u01/oracle/bi/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/java/default/bin:/u01/oracle/oracle_common/common/bin:/u01/oracle/wlserver/common/bin:/u01/oracle/container-scripts
LD_LIBRARY_PATH set as /u01/oracle/bi/lib
INSTALL_PROPERTIES /u01/oracle/bi/../oui/mw/bi/metadata/config.properties
INSTALL_INVOCATION /u01/oracle/bi/bin/../../oui/bin/launch.sh -clone ORACLE_HOME=/u01/oracle -invPtrLoc /u01/oracle/oraInst.loc -ignoreSysPrereqs -silent -responseFile /tmp/create_domain_M2gwRpMxqD/response.txt -J-Doracle.as.install.engine.weblogic.config.mode=true -J-Doracle.config.mode=true -J-Doracle.as.install.engine.install.properties.location=/u01/oracle/bi/../oui/mw/bi/metadata/config.properties -J-DSHIPHOME_STAGE_DIR=/u01/oracle/bi/../oui/mw/bi
Launcher log file is /tmp/OraInstall2017-08-02_05-33-41PM/launcher2017-08-02_05-33-41PM.log.
Checking swap space: must be greater than 500 MB.   Actual 1410 MB    Passed
Checking if this platform requires a 64-bit JVM.   Actual 64    Passed


Log: /u01/oracle/.inventory/logs/install2017-08-02_05-33-41PM.log
Copyright (c) 1999, 2016, Oracle and/or its affiliates. All rights reserved.
Reading response file..
Verifying data
[CONFIG] Launching Config Actions
Started Configuration:BI Configuration
[CONFIG]:Create default domains dir
[CONFIG] SUCCESS:Create default domains dir
[CONFIG]:Create schemas using RCU
[CONFIG] [BI Configuration] [Create schemas using RCU]:2017-08-02T17:34:02.212+0000 Starting RCU 
[CONFIG] [BI Configuration] [Create schemas using RCU]:2017-08-02T17:34:02.215+0000 See log file: /u01/oracle/.inventory/logs/config2017-08-02_05-33-41PM/RCUCreateSchema/RCUCreateSchema.out
[CONFIG] [BI Configuration] [Create schemas using RCU]:2017-08-02T17:34:02.215+0000 See log file: /u01/oracle/.inventory/logs/config2017-08-02_05-33-41PM/RCUCreateSchema/RCUCreateSchema.log
[CONFIG] SUCCESS:Create schemas using RCU
[CONFIG]:Create expanded domain
[CONFIG] [BI Configuration] [Create expanded domain]:2017-08-02T17:34:38.160+0000 See log file: /u01/oracle/.inventory/logs/config2017-08-02_05-33-41PM/createExpandedDomain.log
[CONFIG] SUCCESS:Create expanded domain
[CONFIG]:Essbase
[CONFIG] [BI Configuration] [Essbase]:2017-08-02T17:35:23.356+0000 See log file: /u01/oracle/.inventory/logs/config2017-08-02_05-33-41PM/essbase.log
[CONFIG] SUCCESS:Essbase
[CONFIG]:Generate CSS Keys
[CONFIG] [BI Configuration] [Generate CSS Keys]:2017-08-02T17:37:26.180+0000 See log file: /u01/oracle/.inventory/logs/config2017-08-02_05-33-41PM/CSSKeyGeneration.out
[CONFIG] SUCCESS:Generate CSS Keys
[CONFIG]:BIEE
[CONFIG] [BI Configuration] [BIEE]:2017-08-02T17:37:28.433+0000 See log file: /u01/oracle/.inventory/logs/config2017-08-02_05-33-41PM/biee.log
[CONFIG] SUCCESS:BIEE
[CONFIG]:BI Publisher (BIP)
[CONFIG] [BI Configuration] [BI Publisher (BIP)]:2017-08-02T17:38:38.665+0000 See log file: /u01/oracle/.inventory/logs/config2017-08-02_05-33-41PM/bip.log
[CONFIG] SUCCESS:BI Publisher (BIP)
[CONFIG]:Complete domain
[CONFIG] [BI Configuration] [Complete domain]:2017-08-02T17:39:42.381+0000 See log file: /u01/oracle/.inventory/logs/config2017-08-02_05-33-41PM/completeDomain.log
[CONFIG] SUCCESS:Complete domain
[CONFIG]:Store port range
[CONFIG] SUCCESS:Store port range
[CONFIG]:Create SSL certificates
[CONFIG] SUCCESS:Create SSL certificates
[CONFIG]:Create internal channels
[CONFIG] SUCCESS:Create internal channels
[CONFIG]:Sync mid tier database
[CONFIG] [BI Configuration] [Sync mid tier database]:2017-08-02T17:41:35.215+0000 See log file: /u01/oracle/.inventory/logs/config2017-08-02_05-33-41PM/SyncMidTierDB.out
[CONFIG] SUCCESS:Sync mid tier database
[CONFIG]:Create system components
[CONFIG] [BI Configuration] [Create system components]:2017-08-02T17:43:59.810+0000 See log file: /u01/oracle/.inventory/logs/config2017-08-02_05-33-41PM/bieecreatecomponents.log
[CONFIG] SUCCESS:Create system components
[CONFIG]:Add default service instance
[CONFIG] [BI Configuration] [Add default service instance]:2017-08-02T17:44:45.356+0000 Updating security config
[CONFIG] [BI Configuration] [Add default service instance]:2017-08-02T17:44:45.407+0000 Creating BI Service Instance
[CONFIG] SUCCESS:Add default service instance
[CONFIG]:SampleAppLite
[CONFIG] [BI Configuration] [SampleAppLite]:2017-08-02T17:47:48.858+0000 SampleAppLite data
[CONFIG] [BI Configuration] [SampleAppLite]:2017-08-02T17:47:49.291+0000 Unpacking SampleAppLiteData from: /u01/oracle/bi/modules/oracle.biee.application.sample/sample-datafiles.zip to: /u01/oracle/user_projects/domains/bi/bidata/service_instances/ssi/data
[CONFIG] [BI Configuration] [SampleAppLite]:2017-08-02T17:47:49.317+0000 SampleAppLite unpacked 2361774 bytes
[CONFIG] SUCCESS:SampleAppLite
[CONFIG]:Store JMS credential
[CONFIG] SUCCESS:Store JMS credential
Configuration:BI Configuration completed successfully
Started Configuration:BI Startup
[CONFIG]:Start all Servers
[CONFIG] [BI Startup] [Start all Servers]:2017-08-02T17:47:49.959+0000 Starting all Servers ...
[CONFIG] [BI Startup] [Start all Servers]:2017-08-02T17:47:49.963+0000 See log file: /u01/oracle/.inventory/logs/config2017-08-02_05-33-41PM/startallservers.log
[CONFIG] [BI Startup] [Start all Servers]:2017-08-02T17:53:52.809+0000 Failed single shot step: Start all Servers with: Execution of [/u01/oracle/user_projects/domains/bi/bitools/bin/start.sh] failed with exit value 1
[CONFIG] [BI Startup] [Start all Servers]:2017-08-02T17:53:52.824+0000 Current log files for failed step Start all Servers
[CONFIG] [BI Startup] [Start all Servers]:2017-08-02T17:53:52.825+0000 --------------------
[CONFIG] [BI Startup] [Start all Servers]:2017-08-02T17:53:52.827+0000    Log file: /u01/oracle/.inventory/logs/config2017-08-02_05-33-41PM/startallservers.log
[CONFIG] [BI Startup] [Start all Servers]:2017-08-02T17:53:52.828+0000 --------------------
[CONFIG] [BI Startup] [Start all Servers]:2017-08-02T17:53:52.845+0000 Starting domain; Using domainHome: /u01/oracle/user_projects/domains/bi ...
[CONFIG] [BI Startup] [Start all Servers]:2017-08-02T17:53:52.846+0000 
[CONFIG] [BI Startup] [Start all Servers]:2017-08-02T17:53:52.847+0000 Initializing WebLogic Scripting Tool (WLST) ...
[CONFIG] [BI Startup] [Start all Servers]:2017-08-02T17:53:52.848+0000 
[CONFIG] [BI Startup] [Start all Servers]:2017-08-02T17:53:52.848+0000 Welcome to WebLogic Server Administration Scripting Shell
[CONFIG] [BI Startup] [Start all Servers]:2017-08-02T17:53:52.848+0000 
[CONFIG] [BI Startup] [Start all Servers]:2017-08-02T17:53:52.848+0000 Type help() for help on available commands
[CONFIG] [BI Startup] [Start all Servers]:2017-08-02T17:53:52.851+0000 
[CONFIG] [BI Startup] [Start all Servers]:2017-08-02T17:53:52.852+0000 Requesting credentials ...
[CONFIG] [BI Startup] [Start all Servers]:2017-08-02T17:53:52.852+0000 Enter Weblogic login details at prompt
[CONFIG] [BI Startup] [Start all Servers]:2017-08-02T17:53:52.853+0000 Weblogic Username: Weblogic Password: <Aug 2, 2017 5:47:58 PM GMT> <Info> <Security> <BEA-090905> <Disabling the CryptoJ JCE Provider self-integrity check for better startup performance. To enable this check, specify -Dweblogic.security.allowCryptoJDefaultJCEVerification=true.> 
[CONFIG] [BI Startup] [Start all Servers]:2017-08-02T17:53:52.854+0000 <Aug 2, 2017 5:47:58 PM GMT> <Info> <Security> <BEA-090906> <Changing the default Random Number Generator in RSA CryptoJ from ECDRBG128 to HMACDRBG. To disable this change, specify -Dweblogic.security.allowCryptoJDefaultPRNG=true.> 
[CONFIG] [BI Startup] [Start all Servers]:2017-08-02T17:53:52.856+0000 <Aug 2, 2017 5:47:59 PM GMT> <Info> <Security> <BEA-090909> <Using the configured custom SSL Hostname Verifier implementation: weblogic.security.utils.SSLWLSHostnameVerifier$NullHostnameVerifier.> 
[CONFIG] [BI Startup] [Start all Servers]:2017-08-02T17:53:52.859+0000 Node manager not running. Starting it...
[CONFIG] [BI Startup] [Start all Servers]:2017-08-02T17:53:52.861+0000 NMProcess: + /usr/java/jdk1.8.0_141/bin/java -server -Djava.security.egd=file:/dev/./urandom -Dcoherence.home=/u01/oracle/wlserver/../coherence -Dbea.home=/u01/oracle/wlserver/.. -DNodeManagerHome=/u01/oracle/user_projects/domains/bi/nodemanager -DLogToStderr=false -DQuitEnabled=true -Dweblogic.RootDirectory=/u01/oracle/user_projects/domains/bi -Doracle.security.jps.config=/u01/oracle/user_projects/domains/bi/config/fmwconfig/jps-config-jse.xml -Dcommon.components.home=/u01/oracle/oracle_common -Dopss.version=12.2.1.2 -Dweblogic.RootDirectory=/u01/oracle/user_projects/domains/bi -Doracle.bi.home.dir=/u01/oracle/bi -Doracle.bi.config.dir=/u01/oracle/user_projects/domains/bi/config/fmwconfig/biconfig -Doracle.bi.environment.dir=/u01/oracle/user_projects/domains/bi/config/fmwconfig/bienv -Doracle.bi.12c=true -Ddomain.home=/u01/oracle/user_projects/domains/bi -Dfile.encoding=utf-8 -Djava.system.class.loader=com.oracle.classloader.weblogic.LaunchClassLoader -Djava.security.policy=/u01/oracle/wlserver/server/lib/weblogic.policy -Dweblogic.nodemanager.JavaHome=/usr/java/jdk1.8.0_141 weblogic.NodeManager -v
[CONFIG] [BI Startup] [Start all Servers]:2017-08-02T17:53:52.867+0000 NMProcess: NODEMGR_HOME is already set to /u01/oracle/user_projects/domains/bi/nodemanager
[CONFIG] [BI Startup] [Start all Servers]:2017-08-02T17:53:52.868+0000 NMProcess: CLASSPATH=/usr/java/jdk1.8.0_141/lib/tools.jar:/u01/oracle/wlserver/server/lib/weblogic.jar:/u01/oracle/wlserver/../oracle_common/modules/net.sf.antcontrib_1.1.0.0_1-0b3/lib/ant-contrib.jar:/u01/oracle/wlserver/modules/features/oracle.wls.common.nodemanager.jar::/usr/java/jdk1.8.0_141/lib/tools.jar:/u01/oracle/wlserver/modules/features/wlst.wls.classpath.jar:/u01/oracle/wlserver/..
[CONFIG] [BI Startup] [Start all Servers]:2017-08-02T17:53:52.871+0000 NMProcess: Aug 02, 2017 5:48:07 PM oracle.security.opss.internal.runtime.ServiceContextManagerImpl getContext
[CONFIG] [BI Startup] [Start all Servers]:2017-08-02T17:53:52.873+0000 NMProcess: WARNING: Bootstrap services are used by OPSS internally and clients should never need to directly read/write bootstrap credentials. If required, use Wlst or configuration management interfaces.
[CONFIG] [BI Startup] [Start all Servers]:2017-08-02T17:53:52.874+0000 Storing encrypted NodeManager credentials: /u01/oracle/user_projects/domains/bi/nodemanager/nmUserConfig.properties
[CONFIG] [BI Startup] [Start all Servers]:2017-08-02T17:53:52.878+0000 Creating the key file can reduce the security of your system if it is not kept in a secured location after it is created. Creating new key...
[CONFIG] [BI Startup] [Start all Servers]:2017-08-02T17:53:52.880+0000 NodeManager started
[CONFIG] [BI Startup] [Start all Servers]:2017-08-02T17:53:52.883+0000 
[CONFIG] [BI Startup] [Start all Servers]:2017-08-02T17:53:52.888+0000 Reading domain...
[CONFIG] [BI Startup] [Start all Servers]:2017-08-02T17:53:52.893+0000 /Servers/AdminServer/ListenPort=9500
[CONFIG] [BI Startup] [Start all Servers]:2017-08-02T17:53:52.898+0000 Accessing admin server using URL t3://7e73aadec401:9500
[CONFIG] [BI Startup] [Start all Servers]:2017-08-02T17:53:52.901+0000 Reading domain...
[CONFIG] [BI Startup] [Start all Servers]:2017-08-02T17:53:52.914+0000 /Servers/AdminServer/ListenPort=9500
[CONFIG] [BI Startup] [Start all Servers]:2017-08-02T17:53:52.917+0000 Accessing admin server using URL t3://7e73aadec401:9500
[CONFIG] [BI Startup] [Start all Servers]:2017-08-02T17:53:52.920+0000 Starting AdminServer ...
[CONFIG] [BI Startup] [Start all Servers]:2017-08-02T17:53:52.921+0000 Started AdminServer
[CONFIG] [BI Startup] [Start all Servers]:2017-08-02T17:53:52.923+0000 Storing encrypted AdminServer credentials: /u01/oracle/user_projects/domains/bi/servers/AdminServer/security/adminServerUserConfig.properties
[CONFIG] [BI Startup] [Start all Servers]:2017-08-02T17:53:52.927+0000 
[CONFIG] [BI Startup] [Start all Servers]:2017-08-02T17:53:52.932+0000 Creating the key file can reduce the security of your system if it is not kept in a secured location after it is created. Creating new key...
[CONFIG] [BI Startup] [Start all Servers]:2017-08-02T17:53:52.936+0000 
[CONFIG] [BI Startup] [Start all Servers]:2017-08-02T17:53:52.939+0000 Starting all servers ...
[CONFIG] [BI Startup] [Start all Servers]:2017-08-02T17:53:52.940+0000 Starting bi_server1 (Original State:SHUTDOWN) ...
[CONFIG] [BI Startup] [Start all Servers]:2017-08-02T17:53:52.942+0000 Problem invoking WLST - Traceback (innermost last):
[CONFIG] [BI Startup] [Start all Servers]:2017-08-02T17:53:52.944+0000   File "/u01/oracle/bi/modules/oracle.bi.sysman/scripts/start_servers.py", line 251, in ?
[CONFIG] [BI Startup] [Start all Servers]:2017-08-02T17:53:52.957+0000   File "/u01/oracle/bi/modules/oracle.bi.sysman/scripts/start_servers.py", line 232, in startAll
[CONFIG] [BI Startup] [Start all Servers]:2017-08-02T17:53:52.957+0000   File "/u01/oracle/bi/modules/oracle.bi.sysman/scripts/start_servers.py", line 179, in startManagedServersAndSystemComponents
[CONFIG] [BI Startup] [Start all Servers]:2017-08-02T17:53:52.960+0000 AttributeError: 'NoneType' object has no attribute 'getSystemComponents'
[CONFIG] [BI Startup] [Start all Servers]:2017-08-02T17:53:52.962+0000 
[CONFIG] [BI Startup] [Start all Servers]:2017-08-02T17:53:52.964+0000 Domain status; Using domainHome: /u01/oracle/user_projects/domains/bi ...
[CONFIG] [BI Startup] [Start all Servers]:2017-08-02T17:53:52.966+0000 
[CONFIG] [BI Startup] [Start all Servers]:2017-08-02T17:53:52.969+0000 Initializing WebLogic Scripting Tool (WLST) ...
[CONFIG] [BI Startup] [Start all Servers]:2017-08-02T17:53:52.970+0000 
[CONFIG] [BI Startup] [Start all Servers]:2017-08-02T17:53:52.974+0000 Welcome to WebLogic Server Administration Scripting Shell
[CONFIG] [BI Startup] [Start all Servers]:2017-08-02T17:53:52.982+0000 
[CONFIG] [BI Startup] [Start all Servers]:2017-08-02T17:53:52.983+0000 Type help() for help on available commands
[CONFIG] [BI Startup] [Start all Servers]:2017-08-02T17:53:52.984+0000 
[CONFIG] [BI Startup] [Start all Servers]:2017-08-02T17:53:52.985+0000 <Aug 2, 2017 5:53:42 PM GMT> <Info> <Security> <BEA-090905> <Disabling the CryptoJ JCE Provider self-integrity check for better startup performance. To enable this check, specify -Dweblogic.security.allowCryptoJDefaultJCEVerification=true.> 
[CONFIG] [BI Startup] [Start all Servers]:2017-08-02T17:53:52.987+0000 <Aug 2, 2017 5:53:43 PM GMT> <Info> <Security> <BEA-090906> <Changing the default Random Number Generator in RSA CryptoJ from ECDRBG128 to HMACDRBG. To disable this change, specify -Dweblogic.security.allowCryptoJDefaultPRNG=true.> 
[CONFIG] [BI Startup] [Start all Servers]:2017-08-02T17:53:52.988+0000 <Aug 2, 2017 5:53:43 PM GMT> <Info> <Security> <BEA-090909> <Using the configured custom SSL Hostname Verifier implementation: weblogic.security.utils.SSLWLSHostnameVerifier$NullHostnameVerifier.> 
[CONFIG] [BI Startup] [Start all Servers]:2017-08-02T17:53:52.993+0000 /Servers/AdminServer/ListenPort=9500
[CONFIG] [BI Startup] [Start all Servers]:2017-08-02T17:53:53.001+0000 Accessing admin server using URL t3://7e73aadec401:9500
[CONFIG] [BI Startup] [Start all Servers]:2017-08-02T17:53:53.008+0000 Start Admin Server connect Exception caught Error occurred while performing connect : Error getting the initial context. There is no server running at t3://7e73aadec401:9500 : Failed to initialize JNDI context, tried 2 time or times totally, the interval of each time is 0ms. 
[CONFIG] [BI Startup] [Start all Servers]:2017-08-02T17:53:53.015+0000 t3://7e73aadec401:9500: Destination 172.19.0.3, 9500 unreachable.; nested exception is: 
[CONFIG] [BI Startup] [Start all Servers]:2017-08-02T17:53:53.029+0000 	java.net.ConnectException: Connection refused (Connection refused); No available router to destination.; nested exception is: 
[CONFIG] [BI Startup] [Start all Servers]:2017-08-02T17:53:53.029+0000 	java.rmi.ConnectException: No available router to destination. 
[CONFIG] [BI Startup] [Start all Servers]:2017-08-02T17:53:53.033+0000 Use dumpStack() to view the full stacktrace :
[CONFIG] [BI Startup] [Start all Servers]:2017-08-02T17:53:53.033+0000 Reading domain...
[CONFIG] [BI Startup] [Start all Servers]:2017-08-02T17:53:53.038+0000 Error: runCmd() failed. Do dumpStack() to see details.
[CONFIG] [BI Startup] [Start all Servers]:2017-08-02T17:53:53.042+0000 Problem invoking WLST - Traceback (innermost last):
[CONFIG] [BI Startup] [Start all Servers]:2017-08-02T17:53:53.047+0000   File "/u01/oracle/bi/modules/oracle.bi.sysman/scripts/status_servers.py", line 29, in ?
[CONFIG] [BI Startup] [Start all Servers]:2017-08-02T17:53:53.048+0000   File "/u01/oracle/bi/modules/oracle.bi.sysman/scripts/process_control.py", line 581, in statusComponents
[CONFIG] [BI Startup] [Start all Servers]:2017-08-02T17:53:53.050+0000   File "/u01/oracle/bi/modules/oracle.bi.sysman/scripts/process_control.py", line 455, in outputComponentsStatus
[CONFIG] [BI Startup] [Start all Servers]:2017-08-02T17:53:53.053+0000   File "/u01/oracle/bi/modules/oracle.bi.sysman/scripts/process_control.py", line 243, in connectAdminServer
[CONFIG] [BI Startup] [Start all Servers]:2017-08-02T17:53:53.060+0000   File "/u01/oracle/bi/modules/oracle.bi.sysman/scripts/process_control.py", line 179, in requestCredentialsAndConnectToAdminServer
[CONFIG] [BI Startup] [Start all Servers]:2017-08-02T17:53:53.064+0000   File "/u01/oracle/bi/modules/oracle.bi.sysman/scripts/process_control.py", line 513, in getAdminServerUrl
[CONFIG] [BI Startup] [Start all Servers]:2017-08-02T17:53:53.072+0000   File "/tmp/WLSTOfflineIni1957847160654628470.py", line 127, in readDomain
[CONFIG] [BI Startup] [Start all Servers]:2017-08-02T17:53:53.074+0000   File "/tmp/WLSTOfflineIni1957847160654628470.py", line 19, in command
[CONFIG] [BI Startup] [Start all Servers]:2017-08-02T17:53:53.077+0000 60713: Attempt to execute command "readDomain" in invalid state: Configuration
[CONFIG] [BI Startup] [Start all Servers]:2017-08-02T17:53:53.080+0000 60713: Check the logs for more information.
[CONFIG] [BI Startup] [Start all Servers]:2017-08-02T17:53:53.080+0000  @com.oracle.cie.domain.script.jython.WLSTState.processCommand(WLSTState.java:211)
[CONFIG] [BI Startup] [Start all Servers]:2017-08-02T17:53:53.083+0000 	at com.oracle.cie.domain.script.jython.CommandExceptionHandler.handleException(CommandExceptionHandler.java:69)
[CONFIG] [BI Startup] [Start all Servers]:2017-08-02T17:53:53.086+0000 	at com.oracle.cie.domain.script.jython.WLScriptContext.handleException(WLScriptContext.java:2768)
[CONFIG] [BI Startup] [Start all Servers]:2017-08-02T17:53:53.089+0000 	at com.oracle.cie.domain.script.jython.WLScriptContext.runCmd(WLScriptContext.java:701)
[CONFIG] [BI Startup] [Start all Servers]:2017-08-02T17:53:53.094+0000 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[CONFIG] [BI Startup] [Start all Servers]:2017-08-02T17:53:53.104+0000 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[CONFIG] [BI Startup] [Start all Servers]:2017-08-02T17:53:53.115+0000 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[CONFIG] [BI Startup] [Start all Servers]:2017-08-02T17:53:53.118+0000 	at java.lang.reflect.Method.invoke(Method.java:498)
[CONFIG] [BI Startup] [Start all Servers]:2017-08-02T17:53:53.120+0000 
[CONFIG] [BI Startup] [Start all Servers]:2017-08-02T17:53:53.124+0000 com.oracle.cie.domain.script.jython.WLSTException: com.oracle.cie.domain.script.jython.WLSTException: 60713: Command execution failed.
[CONFIG] [BI Startup] [Start all Servers]:2017-08-02T17:53:53.134+0000 60713: Attempt to execute command "readDomain" in invalid state: Configuration
[CONFIG] [BI Startup] [Start all Servers]:2017-08-02T17:53:53.136+0000 60713: Check the logs for more information.
[CONFIG] [BI Startup] [Start all Servers]:2017-08-02T17:53:53.140+0000  @com.oracle.cie.domain.script.jython.WLSTState.processCommand(WLSTState.java:211)
[CONFIG] [BI Startup] [Start all Servers]:2017-08-02T17:53:53.143+0000 
[CONFIG] [BI Startup] [Start all Servers]:2017-08-02T17:53:53.149+0000 --------------------
[CONFIG] [BI Startup] [Start all Servers]:2017-08-02T17:53:53.154+0000 
[CONFIG] [BI Startup]:Zipping up config assistant log files to /u01/oracle/user_projects/domains/bi/bilogs/bieeconfiglogs_2017-08-02_05-33-41PM.zip
[CONFIG] [BI Startup]:Zipping up the following log files and directories:
/u01/oracle/.inventory/logs/install2017-08-02_05-33-41PM.log
/u01/oracle/.inventory/logs/install2017-08-02_05-33-41PM.out
/u01/oracle/.inventory/logs/config2017-08-02_05-33-41PM

[CONFIG] [BI Startup]:Completed zipping up log files to /u01/oracle/user_projects/domains/bi/bilogs/bieeconfiglogs_2017-08-02_05-33-41PM.zip on host 7e73aadec401
[CONFIG] [BI Startup]:Run /u01/oracle/user_projects/domains/bi/bitools/bin/diagnostic_dump.sh to get full diagnostics
Configuration:BI Startup failed
Error while running Configuration.
The configuration of Oracle Fusion Middleware failed.```

**Comment by TBrannan** [comment]
I figured it out, I was using an incorrect admin password

**Comment by TBrannan** [comment]
I am now getting this error, how do I increase the memory?

```[CONFIG] [BI Configuration] [Create expanded domain]:2017-08-03T19:08:47.144+0000 Java HotSpot(TM) 64-Bit Server VM warning: INFO: os::commit_memory(0x00000000ef285000, 43175936, 0) failed; error='Cannot allocate memory' (errno=12)

[CONFIG] [BI Configuration] [Create expanded domain]:2017-08-03T19:08:47.149+0000 # There is insufficient memory for the Java Runtime Environment to continue.

[CONFIG] [BI Configuration] [Create expanded domain]:2017-08-03T19:08:47.155+0000 # Native memory allocation (mmap) failed to map 43175936 bytes for committing reserved memory.```

**Comment by brunoborges** [comment]
You will have to check the WebLogic documentation on how to properly set JVM heap memory, and then customize your Docker image accordingly.

**Comment by TBrannan** [comment]
thank you, I appreciate it
