### ISSUE TITLE
[WCS step 7.A.2] ORA-01017: invalid username/password; logon denied. (Docker doesn't work with XE)

### ISSUE THREAD

**Issue by Alcold** [oracle/docker-images#815]
I'm trying to create a virtual machine which simulate an environment with a docker WCS and an external Oracle DB (in this case is an XE version installed in vm).
In step 7.A.2 when I run:

```
$ docker run -d --name WCSitesAdminContainer --network=host -p 7001:7001 -p 9001:9001 -v /u01/scratch/WCSitesVolume/WCSites:/u01/oracle/user_projects -v /u01/scratch/WCSitesVolume/WCSitesShared:/u01/oracle/sites-shared --env-file ./wcsitesadminserver.env.list oracle/wcsites:12.2.1.3
```
 
with [wcsitesadminserver.env.list](https://github.com/oracle/docker-images/files/1852368/wcsitesadminserver.env.list.txt) :
```DOCKER_HOST=docker.reply
DB_CONNECTSTRING=docker.reply:1521/xe
DB_USER=sys
DB_PASSWORD=oracle
RCU_PREFIX=DOCKER
DB_SCHEMA_PASSWORD=oracle
SAMPLES=false
DOMAIN_NAME=sites
SITES_SERVER_NAME=wcsites_server1
ADMIN_USERNAME=weblogic
ADMIN_PASSWORD=welcome1
SITES_ADMIN_USERNAME=ContentServer
SITES_ADMIN_PASSWORD=xceladmin
SITES_APP_USERNAME=fwadmin
SITES_APP_PASSWORD=xceladmin
SITES_SS_USERNAME=SatelliteServer
SITES_SS_PASSWORD=xceladmin
```
I get the following error [log](https://github.com/oracle/docker-images/files/1852369/WCSitesAdminContainer.log):
```
sed: -e expression #1, char 60: unterminated s' command
Install Automation -> Starting automation script
    [mkdir] Created dir: /u01/oracle/user_projects/wcs-wls-docker-install/work
     [echo] [3/27/18 10:13 AM] Work Directory=/u01/oracle/user_projects/wcs-wls-docker-install/work
     [echo] [3/27/18 10:13 AM] DB URL: jdbc:oracle:thin:@
     [echo] [3/27/18 10:13 AM] Info -> The script.db.connectstring has been set.
     [echo] [3/27/18 10:13 AM] Info.setDBConnectStringPropertey -> setting docker.reply:1521/xe
     [echo] [3/27/18 10:13 AM] Validation -> Checking if full path to JAVA executable is correctly specified
     [exec] java version "1.8.0_151"
     [exec] Java(TM) SE Runtime Environment (build 1.8.0_151-b12)
     [exec] Java HotSpot(TM) 64-Bit Server VM (build 25.151-b12, mixed mode)
     [echo] [3/27/18 10:13 AM] Validation -> Checking database connection
     [echo] [3/27/18 10:13 AM] dbUrl-----------------: jdbc:oracle:thin:@docker.reply:1521/xe
     [echo] [3/27/18 10:13 AM] Database Connection --> Success!
     [echo] [3/27/18 10:13 AM] 1st phase: WebCenter Sites installation started...
     [copy] Copying 1 file to /u01/oracle/user_projects/wcs-wls-docker-install/work
     [copy] Copying /u01/wcs-wls-docker-install/rcu.rsp to /u01/oracle/user_projects/wcs-wls-docker-install/work/rcu.rsp
     [echo] [3/27/18 10:13 AM] 1st phase: WebCenter Sites installation completed
     [echo] [3/27/18 10:13 AM] 2nd phase: WebCenter Sites RCU configuration started...
     [echo] [3/27/18 10:13 AM] Installation -> Repository Creation Utility - creates schema
     [echo] [3/27/18 10:13 AM] connectString-----------------: docker.reply:1521/xe
  [replace] Replaced 1 occurrences in 1 files.
  [replace] Replaced 1 occurrences in 1 files.
  [replace] Replaced 1 occurrences in 1 files.
  [replace] Replaced 1 occurrences in 1 files.
  [replace] Replaced 1 occurrences in 1 files.
     [echo] [3/27/18 10:13 AM] Create schema using command: /u01/oracle/oracle_common/bin/rcu -silent -responseFile /u01/oracle/user_projects/wcs-wls-docker-install/work/rcu.rsp -f < /u01/oracle/user_projects/wcs-wls-docker-install/work/rcuPasswords2661036362445159196.txt >/u01/oracle/user_projects/wcs-wls-docker-install/work/rcu_output.log
     [echo] [3/27/18 10:13 AM] RCU Create Schema -> Please wait ... may take several minutes
     [exec] Result: 2
     [echo] [3/27/18 10:13 AM]
     [echo]     RCU Logfile: /u01/oracle/user_projects/wcs-wls-docker-install/work/rcu/RCU2018-03-27_10-13_141248934/logs/rcu.log
     [echo] Processing command line ....
     [echo] Repository Creation Utility - Checking Prerequisites
     [echo] Checking Global Prerequisites
     [echo] The selected database is an Oracle XE Edition database, which is not certified for use in an Oracle Fusion Middleware production environment. For a list of certified databases, refer to the Supported System Configurations information on the Oracle Technology Network.
     [echo] Repository Creation Utility - Checking Prerequisites
     [echo] Checking Component Prerequisites
     [echo] Repository Creation Utility - Creating Tablespaces
     [echo] Validating and Creating Tablespaces
     [echo] Repository Creation Utility - Create
     [echo] Repository Create in progress.
     [echo] Percent Complete: 12
...
     [echo] Percent Complete: 93
     [echo] **ORA-00439: feature not enabled: Advanced replication**
     [echo] File:/u01/oracle/oracle_common/common/sql/iau/scripts/prepareAuditView.sql
     [echo] Statement:CREATE MATERIALIZED VIEW LOG ON IAU_COMMON WITH ROWID
     [echo] Percent Complete: 100
     [echo] Repository Creation Utility: Create - Completion Summary
     [echo] Database details:
     [echo] -----------------------------
     [echo] Host Name                                    : docker.reply
     [echo] Port                                         : 1521
     [echo] Service Name                                 : XE
     [echo] Connected As                                 : sys
     [echo] Prefix for (prefixable) Schema Owners        : DOCKER
     [echo] RCU Logfile                                  : /u01/oracle/user_projects/wcs-wls-docker-install/work/rcu/RCU2018-03-27_10-13_141248934/logs/rcu.log
     [echo] RCU Checkpoint Object                        : /u01/oracle/user_projects/wcs-wls-docker-install/work/rcu/RCU2018-03-27_10-13_141248934/logs/RCUCheckpointObj
     [echo] Component schemas created:
     [echo] -----------------------------
     [echo] Component                                    Status         Logfile
     [echo] Common Infrastructure Services               Success        /u01/oracle/user_projects/wcs-wls-docker-install/work/rcu/RCU2018-03-27_10-13_141248934/logs/stb.log
     [echo] Oracle Platform Security Services            Failed         No log created
     [echo] WebCenter Sites                              Failed         No log created
     [echo] Audit Services                               Failed         /u01/oracle/user_projects/wcs-wls-docker-install/work/rcu/RCU2018-03-27_10-13_141248934/logs/iau.log

     [echo] Audit Services Append                        Success        /u01/oracle/user_projects/wcs-wls-docker-install/work/rcu/RCU2018-03-27_10-13_141248934/logs/iau_append.log
     [echo] Audit Services Viewer                        Success        /u01/oracle/user_projects/wcs-wls-docker-install/work/rcu/RCU2018-03-27_10-13_141248934/logs/iau_viewer.log
     [echo] WebLogic Services                            Success        /u01/oracle/user_projects/wcs-wls-docker-install/work/rcu/RCU2018-03-27_10-13_141248934/logs/wls.log
     [echo] Repository Creation Utility - Create : Operation Completed
     [echo] Repository Creation Utility - Dropping and Cleanup of the failed components
     [echo] Repository Dropping and Cleanup of the failed components in progress.
     [echo] Percent Complete: 33
     [echo] Percent Complete: 66
     [echo] Percent Complete: 72
     [echo] Percent Complete: 100
     [echo] [3/27/18 10:13 AM] Successfully created schemas
     [echo] [3/27/18 10:13 AM] 2nd phase: WebCenter Sites RCU configuration completed successfully.
     [echo] [3/27/18 10:13 AM] 3rd phase: WebCenter Sites Config Wizard has started.
     [echo] [3/27/18 10:13 AM] Installation -> Weblogic Configuration Wizard
     [copy] Copying 1 file to /u01/oracle/user_projects/wcs-wls-docker-install/work
     [echo] [3/27/18 10:13 AM] Weblogic:runConfigWizard:dbUrl-----------------: jdbc:oracle:thin:@docker.reply:1521/xe
     [echo] [3/27/18 10:13 AM] Weblogic Configuration Wizard -> Please wait ... may take several minutes
     [echo] [3/27/18 10:13 AM] Weblogic Configuration Wizard -> command: /u01/oracle/user_projects/wcs-wls-docker-install/work/runConfigWizard.sh
     [exec] CLASSPATH=/usr/java/jdk1.8.0_151/lib/tools.jar:/u01/oracle/wlserver/modules/features/wlst.wls.classpath.jar:
     [exec] PATH=/u01/oracle/wlserver/server/bin:/u01/oracle/wlserver/../oracle_common/modules/thirdparty/org.apache.ant/1.9.8.0.0/apache-ant-1.9.8/bin:/usr/java/jdk1.8.0_151/jre/bin:/usr/java/jdk1.8.0_151/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/java/default/bin:/u01/oracle/oracle_common/common/bin:/u01/oracle/wlserver/common/bin:/u01/oracle/container-scripts:/usr/java/default/bin:/u01/oracle/oracle_common/common/bin:/u01/oracle/wlserver/../oracle_common/modules/org.apache.maven_3.2.5/bin
     [exec] Your environment has been set.
     [exec] Mar 27, 2018 10:14:57 AM oracle.security.jps.internal.policystore.util.JpsDataManagerUtil getDBConnection
     [exec] WARNING: Can not connect DB with URL jdbc:oracle:thin:@//docker.reply:1521/xe
     [exec] java.sql.SQLException: ORA-01017: invalid username/password; logon denied
     [exec]     at oracle.jdbc.driver.T4CTTIoer11.processError(T4CTTIoer11.java:494)
     [exec]     at oracle.jdbc.driver.T4CTTIoer11.processError(T4CTTIoer11.java:441)
     [exec]     at oracle.jdbc.driver.T4CTTIoer11.processError(T4CTTIoer11.java:436)
     [exec]     at oracle.jdbc.driver.T4CTTIfun.processError(T4CTTIfun.java:1061)
     [exec]     at oracle.jdbc.driver.T4CTTIoauthenticate.processError(T4CTTIoauthenticate.java:550)
     [exec]     at oracle.jdbc.driver.T4CTTIfun.receive(T4CTTIfun.java:623)
     [exec]     at oracle.jdbc.driver.T4CTTIfun.doRPC(T4CTTIfun.java:252)
     [exec]     at oracle.jdbc.driver.T4CTTIoauthenticate.doOAUTH(T4CTTIoauthenticate.java:499)
     [exec]     at oracle.jdbc.driver.T4CTTIoauthenticate.doOAUTH(T4CTTIoauthenticate.java:1279)
     [exec]     at oracle.jdbc.driver.T4CConnection.logon(T4CConnection.java:663)
     [exec]     at oracle.jdbc.driver.PhysicalConnection.connect(PhysicalConnection.java:702)
     [exec]     at oracle.jdbc.driver.T4CDriverExtension.getConnection(T4CDriverExtension.java:39)
     [exec]     at oracle.jdbc.driver.OracleDriver.connect(OracleDriver.java:691)
     [exec]     at java.sql.DriverManager.getConnection(DriverManager.java:664)
     [exec]     at java.sql.DriverManager.getConnection(DriverManager.java:247)
     [exec]     at oracle.security.jps.internal.policystore.util.JpsDataManagerUtil.getDBConnection(JpsDataManagerUtil.java:400)
     [exec]     at oracle.security.jps.internal.policystore.util.JpsDataManagerUtil.isNewSchema(JpsDataManagerUtil.java:249)
     [exec]     at oracle.security.jps.internal.core.datamanager.DataManagerFactoryImpl.isNewSchema(DataManagerFactoryImpl.java:252)
     [exec]     at oracle.security.jps.internal.common.rdbms.util.JpsDbBootstrapImpl.<init>(JpsDbBootstrapImpl.java:182)
     [exec]     at oracle.security.opss.tools.lifecycle.OpssLifecycleUtil.getJpsDbBootstrap(OpssLifecycleUtil.java:784)
     [exec]     at oracle.security.opss.tools.lifecycle.OpssLifecycleUtil.checkIfFarmExists(OpssLifecycleUtil.java:706)
     [exec]     at oracle.security.opss.tools.lifecycle.OpssDomainConfigImpl.checkIfFarmExists(OpssDomainConfigImpl.java:907)
     [exec]     at oracle.security.opss.tools.lifecycle.OpssDomainConfigImpl.configureDBSecurityStore(OpssDomainConfigImpl.java:600)
     [exec]     at oracle.security.opss.tools.lifecycle.OpssDomainConfigImpl.configureSubsystem(OpssDomainConfigImpl.java:489)
     [exec]     at oracle.security.opss.tools.lifecycle.OpssDomainConfigImpl.initializeSubsystem(OpssDomainConfigImpl.java:269)
     [exec]     at oracle.security.opss.tools.lifecycle.cie.OpssSecurityConfiguration.initializeSubsystem(OpssSecurityConfiguration.java:188)
     [exec]     at com.oracle.cie.domain.progress.template.importer.ImporterOPSSProcessingPhase.initialize(ImporterOPSSProcessingPhase.java:36)
     [exec]     at com.oracle.cie.domain.progress.domain.generation.OPSSProcessingPhase.processOPSS(OPSSProcessingPhase.java:154)
     [exec]     at com.oracle.cie.domain.progress.domain.generation.OPSSProcessingPhase.execute(OPSSProcessingPhase.java:54)
     [exec]     at com.oracle.cie.domain.progress.AbstractProgressGenerator.run(AbstractProgressGenerator.java:94)
     [exec]     at java.lang.Thread.run(Thread.java:748)
     [exec] Problem invoking WLST - Traceback (innermost last):
     [exec]   File "/u01/oracle/user_projects/wcs-wls-docker-install/work/config.py", line 118, in ?
     [exec]   File "/u01/oracle/user_projects/wcs-wls-docker-install/work/tmp/WLSTOfflineIni4336807574961669077.py", line 139, in updateDomain
     [exec]   File "/u01/oracle/user_projects/wcs-wls-docker-install/work/tmp/WLSTOfflineIni4336807574961669077.py", line 19, in command
     [exec] 64254: Error occurred in "OPSS Processing" phase execution
     [exec] 64254: Encountered error: SecurityContext:
     [exec]  Domain Name: sites
     [exec]  JDBC URL: opss-audit-DBDS:jdbc:oracle:thin:@//docker.reply:1521/xe
     [exec]  JDBC URL: opss-data-source:jdbc:oracle:thin:@//docker.reply:1521/xe
     [exec]  JNDI Name: opss-audit-DBDS:jdbc/AuditAppendDataSource
     [exec]  JNDI Name: opss-data-source:jdbc/OpssDataSource
     [exec]  Driver Name: opss-audit-DBDS:oracle.jdbc.OracleDriver
     [exec]  Driver Name: opss-data-source:oracle.jdbc.OracleDriver
     [exec]  Persistence Type: DATABASE
     [exec]  Platform: WLS
     [exec]  Scratch Dir: scratch
     [exec]  Reconfig Domain: false
     [exec]  Shared Secret Store: null
     [exec]  Extension: true
     [exec]  DisableManagementOperations: falseJDBC Properties:
     [exec] user:DOCKER_IAU_APPEND
     [exec] username:DOCKER_IAU_APPENDJDBC Properties:
     [exec] user:DOCKER_OPSS
     [exec] username:DOCKER_OPSS
     [exec] 64254: Check log for more detail.
     [exec] null
     [exec]     at com.oracle.cie.domain.script.jython.CommandExceptionHandler.handleException(CommandExceptionHandler.java:69)
     [exec]     at com.oracle.cie.domain.script.jython.WLScriptContext.handleException(WLScriptContext.java:2983)
     [exec]     at com.oracle.cie.domain.script.jython.WLScriptContext.runCmd(WLScriptContext.java:735)
     [exec]     at sun.reflect.GeneratedMethodAccessor238.invoke(Unknown Source)
     [exec]     at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
     [exec]     at java.lang.reflect.Method.invoke(Method.java:498)
     [exec] com.oracle.cie.domain.script.jython.WLSTException: com.oracle.cie.domain.script.jython.WLSTException: Error updating domain:
     [exec] 64254: Error occurred in "OPSS Processing" phase execution
     [exec] 64254: Encountered error: SecurityContext:
     [exec]  Domain Name: sites
     [exec]  JDBC URL: opss-audit-DBDS:jdbc:oracle:thin:@//docker.reply:1521/xe
     [exec]  JDBC URL: opss-data-source:jdbc:oracle:thin:@//docker.reply:1521/xe
     [exec]  JNDI Name: opss-audit-DBDS:jdbc/AuditAppendDataSource
     [exec]  JNDI Name: opss-data-source:jdbc/OpssDataSource
     [exec]  Driver Name: opss-audit-DBDS:oracle.jdbc.OracleDriver
     [exec]  Driver Name: opss-data-source:oracle.jdbc.OracleDriver
     [exec]  Persistence Type: DATABASE
     [exec]  Platform: WLS
     [exec]  Scratch Dir: scratch
     [exec]  Reconfig Domain: false
     [exec]  Shared Secret Store: null
     [exec]  Extension: true
     [exec]  DisableManagementOperations: falseJDBC Properties:
     [exec] user:DOCKER_IAU_APPEND
     [exec] username:DOCKER_IAU_APPENDJDBC Properties:
     [exec] user:DOCKER_OPSS
     [exec] username:DOCKER_OPSS
     [exec] 64254: Check log for more detail.
     [exec] null
     [exec] Result: 1
     [echo] [3/27/18 10:14 AM]
     [echo] Initializing WebLogic Scripting Tool (WLST) ...
     [echo] Jython scans all the jar files it can find at first startup. Depending on the system, this process may take a few minutes to complete, and WLST may not return a prompt right away.
     [echo] Welcome to WebLogic Server Administration Scripting Shell
     [echo] Type help() for help on available commands
     [echo] Error: runCmd() failed. Do dumpStack() to see details.
     [echo] [3/27/18 10:14 AM] Error -> Failed to run Weblogic Configuration Wizard successfully

Sites installation has failed. Please check Admin Container log for details
```
- [iau.log](https://github.com/oracle/docker-images/files/1852400/iau.log)

Do you have suggestions? How can I resolve this issue?

**Comment by gvenzl** [comment]
Hi @Alcold,

I'm afraid I'm not an expert on what you are trying to achieve, however, I have an observation here that might help you solving this puzzle. The database connection details seem to be ok, given that:
```
     [echo] [3/27/18 10:13 AM] Validation -> Checking database connection
     [echo] [3/27/18 10:13 AM] dbUrl-----------------: jdbc:oracle:thin:@docker.reply:1521/xe
     [echo] [3/27/18 10:13 AM] Database Connection --> Success!
     [echo] [3/27/18 10:13 AM] 1st phase: WebCenter Sites installation started...
```
seems to say that everything is fine.

Looking through the log output you put here I spotted the following first line that makes me wonder whether that line was the one that would have replace the password, or something:
```
sed: -e expression #1, char 60: unterminated s' command
```

Can it be that this is causing your issue?

**Comment by Alcold** [comment]
Hi @gvenzl,
for me it is not the cause of the issue...

However if it is, I don't know how to fix it... :(

**Comment by gvenzl** [comment]
Hm, that would have been too easy, I guess :)

@ashishchalak, can you help?

**Comment by Alcold** [comment]
After putting oracle EE DB installation was successfully completed.

But I found another issue (I'll open new one).

Thank you @ashishchalak
