### ISSUE TITLE
WebLogic Server 12.2.1 Cannot startup!

### ISSUE THREAD

**Issue by weilai201** [oracle/docker-images#817]
I follow 'OracleWebLogic' document, I build a '1221-domain' image. And then i follow '1221-appdeploy' document, I build my app image now.But When I run it,I get error from cosole .

MALFORMED
weblogic.application.ModuleException: MALFORMED
MALFORMED
        at weblogic.servlet.internal.WebAppModule.createModuleException(WebAppModule.java:2007)
        at weblogic.servlet.internal.WebAppModule.init(WebAppModule.java:288)
        at weblogic.servlet.internal.WebAppModule.init(WebAppModule.java:703)
        at weblogic.application.internal.flow.ScopedModuleDriver.init(ScopedModuleDriver.java:162)
        at weblogic.application.internal.ExtensibleModuleWrapper.init(ExtensibleModuleWrapper.java:98)
        Truncated. see log file for complete stacktrace
Caused By: java.lang.IllegalArgumentException: MALFORMED
        at java.util.zip.ZipCoder.toString(ZipCoder.java:58)
        at java.util.zip.ZipFile.getZipEntry(ZipFile.java:583)
        at java.util.zip.ZipFile.access$900(ZipFile.java:60)
        at java.util.zip.ZipFile$ZipEntryIterator.next(ZipFile.java:539)
        at java.util.zip.ZipFile$ZipEntryIterator.nextElement(ZipFile.java:514)
        Truncated. see log file for complete stacktrace
> 
<Mar 29, 2018 6:48:02 AM GMT> <Error> <Deployer> <BEA-149231> <Unable to set the activation state to true for the application "market".
weblogic.application.ModuleException: Module null can not be activated, not in ACTIVATED state: NEW
        at weblogic.diagnostics.module.WLDFModule.activate(WLDFModule.java:328)
        at weblogic.application.internal.flow.ModuleStateDriver$2.next(ModuleStateDriver.java:216)
        at weblogic.application.internal.flow.ModuleStateDriver$2.next(ModuleStateDriver.java:211)
        at weblogic.application.utils.StateMachineDriver.nextState(StateMachineDriver.java:45)
        at weblogic.application.internal.flow.ModuleStateDriver.activate(ModuleStateDriver.java:61)
        Truncated. see log file for complete stacktrace
> 

I found that there are chinese characters  in some filename ,such as '文件.xls' in test.war file.

I cannot reslove it, What shoud I do?

**Comment by mriccell** [comment]
What operation are you doing from the console?  Are you sure that the directory in the image where the war file was copied to has the correct permissions?
Bash into the container and take a look at the permissions and user.

**Comment by weilai201** [comment]
@mriccell I build my app image use `/docker-images/OracleWebLogic/samples/1221-appdeploy/Dockerfile` and use `docker run -d -p7001:7001 myweblogic` commond run my app.

when I delete  '文件.xls' in war file and build it again,it running ok!  

And I did another test! I run `1221-domain` image and open console `http://localhost:7001/console` in my browser. I deploy test.war use deploy function! But I get the same error like 'MALFORMED'! 

So, I guess Oracle Weblogic use `java.util.Zip` to unzip my war file. The java Zip class cannot support chinese character filename. Is it so?

**Comment by mriccell** [comment]
In WebLogic applications have naming requirements please look at the following documentation for valid characters https://docs.oracle.com/cd/E24329_01/web.1211/e24443/deployunits.htm#i1049419

**Comment by simon-meng-cn** [comment]
@weilai201 In java.util.zip.ZipFile, the UTF-8 character set is used to decode entry names and comments. Your application contains a Chinese character file name. The character set may be GBK. The solution is not to use Chinese characters as file names in the war file.

**Comment by mriccell** [comment]
I will close this issue @weilai201 please let us know if you still have questions.

**Comment by weilai201** [comment]
@mriccell @simon-meng-cn  Thank you！ My solution is “Delete the files which contains chinese character！”
