### ISSUE TITLE
Weblogic fmw_infrastructure 12c Docker Container- Domain Creation Failed.. Please check the Domain Logs

### ISSUE THREAD

**Issue by Manishrana007** [oracle/docker-images#844]
HI Mriccell/others,

I am getting below errors during oracle/fmw-infrastructure:12.2.1.3 docker creation.

```
[oracle@localdev fmwInfra]$ docker run -d -p 9001:7001 --network=InfraNET -v /u01/oracle/fmwInfra:/u01/oracle/user_projects --name InfraAdminContainer --env-file ./infraDomain.env.list oracle/fmw-infrastructure:12.2.1.3.01
5fdfc4446b3f7c09461ab979e6d25118e52a76c92f02fd11132411c825bea55b
[oracle@localdev fmwInfra]$ docker logs --details InfraAdminContainer -f
 Configuring Domain for first time
 If Domain has already been Configured
 Start the Admin and Managed Servers
 =====================================
 CONNECTION_STRING=fc54f8444045:1521/ORCLPDB1
 RCUPREFIX=INFRA7
 DOMAIN_NAME=InfraDomain
 Loading RCU Phase
 =================
 CONNECTION_STRING=fc54f8444045:1521/ORCLPDB1
 RCUPREFIX=INFRA7
 DB_PASSWORD=password
 jdbc_url=jdbc:oracle:thin:@fc54f8444045:1521/ORCLPDB1
 ADMIN_PASSWORD=password
 DB_SCHEMA_PASSWORD=password
 DB_USERNAME=sys
 DOMAIN_HOME: /u01/oracle/user_projects/domains/InfraDomain
 MW_HOME: /u01/oracle
 WL_HOME: /u01/oracle/wlserver
 ADMIN_USER: weblogic
 DOMAIN_ROOT: /u01/oracle/user_projects/domains
 DOMAIN HOME: /u01/oracle/user_projects/domains/InfraDomain
 Loading SOA RCU into database
 Domain Configuration Phase
 ==========================

 Initializing WebLogic Scripting Tool (WLST) ...

 Welcome to WebLogic Server Administration Scripting Shell

 Type help() for help on available commands

 /u01/oracle/container-scripts/createInfraDomain.py called with the following sys.argv array:
 sys.argv[0] = /u01/oracle/container-scripts/createInfraDomain.py
 sys.argv[1] = -oh
 sys.argv[2] = /u01/oracle
 sys.argv[3] = -jh
 sys.argv[4] = /usr/java/default
 sys.argv[5] = -parent
 sys.argv[6] = /u01/oracle/user_projects/domains
 sys.argv[7] = -name
 sys.argv[8] = InfraDomain
 sys.argv[9] = -user
 sys.argv[10] = weblogic
 sys.argv[11] = -password
 sys.argv[12] = password
 sys.argv[13] = -rcuDb
 sys.argv[14] = fc54f8444045:1521/ORCLPDB1
 sys.argv[15] = -rcuPrefix
 sys.argv[16] = INFRA7
 sys.argv[17] = -rcuSchemaPwd
 sys.argv[18] = password
 Error: set() failed. Do dumpStack() to see details.
 Error: runCmd() failed. Do dumpStack() to see details.
 Problem invoking WLST - Traceback (innermost last):
   File "/u01/oracle/container-scripts/createInfraDomain.py", line 271, in ?
   File "/u01/oracle/container-scripts/createInfraDomain.py", line 59, in createInfraDomain
   File "/u01/oracle/container-scripts/createInfraDomain.py", line 72, in createBaseDomain
   File "/tmp/WLSTOfflineIni7109568471411681869.py", line 79, in set
   File "/tmp/WLSTOfflineIni7109568471411681869.py", line 19, in command
        at com.oracle.cie.domain.script.jython.CommandExceptionHandler.handleException(CommandExceptionHandler.java:69)
        at com.oracle.cie.domain.script.jython.WLScriptContext.handleException(WLScriptContext.java:2983)
        at com.oracle.cie.domain.script.jython.WLScriptContext.runCmd(WLScriptContext.java:735)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)

 com.oracle.cie.domain.script.jython.WLSTException: com.oracle.cie.domain.script.jython.WLSTException

 RetVal from Domain creation 1
 Domain Creation Failed.. Please check the Domain Logs
```

Please can you help with sorting out this issue.

Cheers,
Manish

**Comment by Manishrana007** [comment]
Please note that RCU was successfully completed. See logs below.

Processing command line ....
Repository Creation Utility - Checking Prerequisites
Checking Global Prerequisites


Repository Creation Utility - Checking Prerequisites
Checking Component Prerequisites
Repository Creation Utility - Creating Tablespaces
Validating and Creating Tablespaces
Repository Creation Utility - Create
Repository Create in progress.
Percent Complete: 20
Percent Complete: 20
Percent Complete: 22
Percent Complete: 24
Percent Complete: 26
Percent Complete: 26
Percent Complete: 26
Percent Complete: 35
Percent Complete: 35
Percent Complete: 45
Percent Complete: 45
Percent Complete: 45
Percent Complete: 53
Percent Complete: 53
Percent Complete: 63
Percent Complete: 63
Percent Complete: 63
Percent Complete: 71
Percent Complete: 71
Percent Complete: 73
Percent Complete: 73
Percent Complete: 75
Percent Complete: 75
Percent Complete: 84
Percent Complete: 84
Percent Complete: 84
Percent Complete: 85
Percent Complete: 86
Percent Complete: 87
Percent Complete: 87
Percent Complete: 92
Percent Complete: 92
Percent Complete: 96
Percent Complete: 96
Percent Complete: 100

Repository Creation Utility: Create - Completion Summary

Database details:
-----------------------------
Host Name                                    : fc54f8444045
Port                                         : 1521
Service Name                                 : ORCLPDB1
Connected As                                 : sys
Prefix for (prefixable) Schema Owners        : INFRA7
RCU Logfile                                  : /tmp/RCU2018-04-13_03-11_1065786166/logs/rcu.log

Component schemas created:
-----------------------------
Component                                    Status         Logfile

Common Infrastructure Services               Success        /tmp/RCU2018-04-13_03-11_1065786166/logs/stb.log
Oracle Platform Security Services            Success        /tmp/RCU2018-04-13_03-11_1065786166/logs/opss.log
Audit Services                               Success        /tmp/RCU2018-04-13_03-11_1065786166/logs/iau.log
Audit Services Append                        Success        /tmp/RCU2018-04-13_03-11_1065786166/logs/iau_append.log
Audit Services Viewer                        Success        /tmp/RCU2018-04-13_03-11_1065786166/logs/iau_viewer.log
Metadata Services                            Success        /tmp/RCU2018-04-13_03-11_1065786166/logs/mds.log
WebLogic Services                            Success        /tmp/RCU2018-04-13_03-11_1065786166/logs/wls.log

Repository Creation Utility - Create : Operation Completed

**Comment by mriccell** [comment]
The problem is after RCU creation when the actual domain is created you are running into a WLST error.  It is failing in set('Password', password) probably the password you used is not valid so it is not able to create the domain. Every time you are going to build a new image make sure to have a new RCU Prefix and that your domain has not been created in the PV.

**Comment by mriccell** [comment]
Closing due to inactivity, please reopen if you are still seeing the problem.

**Comment by gmichaello** [comment]
Hi Guys,

I'm not sure if there was a fix for the above issue.  But I'm running into exactly the same error, where it is failing to create the domain at the spot where it needs to set/define the password for the domain creation(line 80 in createInfraDomain.py). I've tried putting in a complex password as suggested above with no luck.

 running an image 12.2.1.4 pulled from docker hub 

docker pull store/oracle/fmw-infrastructure:12.2.1.4-191221


Here are my logs
c:\soa-12.2.1.4>docker logs --details InfraSOA
 Domain Home is:  /u01/oracle/user_projects/domains/myinfraDomain1
 Configuring Domain for first time
 Start the Admin and Managed Servers
 =====================================
 CONNECTION_STRING=InfraDB:1521/InfraPDB1.us.oracle.com
 RCUPREFIX=INFRA001
 DOMAIN_NAME=myinfraDomain1
 DOMAIN_HOME=/u01/oracle/user_projects/domains/myinfraDomain1
 Loading RCU Phase
 =================
 CONNECTION_STRING=InfraDB:1521/InfraPDB1.us.oracle.com
 RCUPREFIX=INFRA001
 jdbc_url=jdbc:oracle:thin:@InfraDB:1521/InfraPDB1.us.oracle.com
 Creating Domain 1st execution
 Loading SOA RCU into database
 Domain Configuration Phase
 ==========================

 Initializing WebLogic Scripting Tool (WLST) ...

 Welcome to WebLogic Server Administration Scripting Shell

 Type help() for help on available commands

 Creating Admin Server...
 Error: set() failed. Do dumpStack() to see details.
 Error: runCmd() failed. Do dumpStack() to see details.
 Problem invoking WLST - Traceback (innermost last):
   File "/u01/oracle/container-scripts/createInfraDomain.py", line 308, in ?
   File "/u01/oracle/container-scripts/createInfraDomain.py", line 46, in createInfraDomain
   File "/u01/oracle/container-scripts/createInfraDomain.py", line 80, in createBaseDomain
   File "/tmp/WLSTOfflineIni1955096353876950427.py", line 79, in set
   File "/tmp/WLSTOfflineIni1955096353876950427.py", line 19, in command
        at com.oracle.cie.domain.script.jython.CommandExceptionHandler.handleException(CommandExceptionHandler.java:69)
        at com.oracle.cie.domain.script.jython.WLScriptContext.handleException(WLScriptContext.java:3085)
        at com.oracle.cie.domain.script.jython.WLScriptContext.runCmd(WLScriptContext.java:738)
        at sun.reflect.GeneratedMethodAccessor125.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)

 com.oracle.cie.domain.script.jython.WLSTException: com.oracle.cie.domain.script.jython.WLSTException

 RetVal from Domain creation 1
 Domain Creation Failed.. Please check the Domain Logs

**Comment by maxdone1985** [comment]
I have Same issue , any one knows how to slove  ?

**Comment by samuelmunguti5** [comment]
Try using a password with both numbers and characters e. g. weblogic1234

**Comment by maxdone1985** [comment]
this is what i am using 

username=weblogic
password=weblogic1
DOMAIN_NAME=infraDom
ADMIN_LISTEN_PORT=7001
ADMIN_NAME=myadmin
ADMIN_HOST=InfraAdminContainer
ADMINISTRATION_PORT_ENABLED=false
ADMINISTRATION_PORT=9002
MANAGEDSERVER_PORT=8001
MANAGED_NAME=infraServer13
RCUPREFIX=INFRA019
PRODUCTION_MODE=dev
CONNECTION_STRING=InfraDB:1521/InfraPDB1.us.oracle.com
DOMAIN_HOST_VOLUME=C:\apps\docker\oracle-weblogic\properties

**Comment by arunsoapro** [comment]
You have to use an encrypted password in domain_security.properties and not clear text 
echo -n 'WebLogic_Password' | base64
