### ISSUE TITLE
Error when create SOA AdminServer with domainType 'soaosb' 

### ISSUE THREAD

**Issue by anti996sz** [oracle/docker-images#899]
When  I study the scripts in 'docker-images/OracleSOASuite/dockerfiles/12.2.1.3/container-scripts', and find domainType "soaosb" also supported, so I try to use this type to create SOA AdminServer, but get error as below:

...
INFO: Preparing to update domain...
Jun 10, 2018 2:50:45 AM oracle.mds
WARNING: MDS-11019: The default CharSet US-ASCII is not a unicode character set. File names with non-ASCII characters may not operate as expected. Check locale settings.
INFO: Domain updated successfully
INFO: Extending domain at /u01/oracle/user_projects/domains/InfraDomain
INFO: Applying JRF templates...
Error: runCmd() failed. Do dumpStack() to see details.
Problem invoking WLST - Traceback (innermost last):
  File "/u01/oracle/dockertools/createDomain.py", line 483, in ?
  File "/u01/oracle/dockertools/createDomain.py", line 118, in createDomain
  File "/u01/oracle/dockertools/createDomain.py", line 304, in extendOsbDomain
  File "/u01/oracle/dockertools/createDomain.py", line 214, in readAndApplyJRFTemplates
  File "/tmp/WLSTOfflineIni8087973204141769450.py", line 137, in addTemplate
  File "/tmp/WLSTOfflineIni8087973204141769450.py", line 19, in command

64075: Template is configured.
64075: The template was previously configured.
64075: Selection is reverted. No further actions required.
        at com.oracle.cie.domain.script.jython.CommandExceptionHandler.handleException(CommandExceptionHandler.java:69)
        at com.oracle.cie.domain.script.jython.WLScriptContext.handleException(WLScriptContext.java:2983)
        at com.oracle.cie.domain.script.jython.WLScriptContext.runCmd(WLScriptContext.java:735)
        at sun.reflect.GeneratedMethodAccessor155.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)

com.oracle.cie.domain.script.jython.WLSTException: com.oracle.cie.domain.script.jython.WLSTException: Error adding Template:

64075: Template is configured.
64075: The template was previously configured.
64075: Selection is reverted. No further actions required.

ERROR: Domain Configuration failed. Please check the logs

Command I used when create the AdminServer:

docker run -i -t  --name soaosbas \
	--hostname osbas.cecport.com \
	-p 7101:7001 \
	-p 9101:9001 \
	-v /home/DockerVolume/SOAVolume/soaosbdomain:/u01/oracle/user_projects \
	--network=SOANet \
	--env-file ./soaosb_AdminServer.env.list \
	localhost/oracle/soasuite:12.2.1.3

soaosb_AdminServer.env.list

$ cat soaosb_AdminServer.env.list
CONNECTION_STRING=soadb:1521/soapdb
RCUPREFIX=SOAOSB01
DB_PASSWORD=Welcome1
DB_SCHEMA_PASSWORD=Welcome1
ADMIN_PASSWORD=Welcome1
MANAGED_SERVER=soaosb_server1
DOMAIN_TYPE=soaosb
ADMIN_HOST=soaosbas
ADMIN_PORT=7001

**Comment by rdas76** [comment]
This domain type "SOAOSB" is not supported in this release. This may be supported in future releases.
