### ISSUE TITLE
DB Connection string error while starting WCS Image

### ISSUE THREAD

**Issue by jobsforprabu** [oracle/docker-images#912]
Hi Team,

We are seeing error while starting the WCS docker image. 

Please check the database parameters in the configuration file. --> java.sql.SQLRecoverableException: IO Error: Connection reset by peer, Authentication lapse 116342 ms.
java.sql.SQLRecoverableException: IO Error: Connection reset by peer, Authentication lapse 116342 ms.

we tried to change the conection string error in all the possible ways, but nothing is working 

DB_CONNECTSTRING=WCSites12212Database:1521/ORCLPDB1.localdomain - this is the current string which we are using

DB_CONNECTSTRING=host.com/WCSites12212Database:1521/ORCLPDB1.localdomain - even we tried this one as well. but nothing is working

DB Image is running fine

**Comment by jobsforprabu** [comment]
Here is the error code 

[echo] [6/26/18 12:06 PM] Please check the database parameters in the configuration file. --> java.sql.SQLRecoverableException: IO Error: Connection reset by peer, Authentication lapse 98823 ms.
java.sql.SQLRecoverableException: IO Error: Connection reset by peer, Authentication lapse 98823 ms.
        at oracle.jdbc.driver.T4CConnection.logon(T4CConnection.java:794)
        at oracle.jdbc.driver.PhysicalConnection.connect(PhysicalConnection.java:702)
        at oracle.jdbc.driver.T4CDriverExtension.getConnection(T4CDriverExtension.java:39)
        at oracle.jdbc.driver.OracleDriver.connect(OracleDriver.java:691)
        at java.sql.DriverManager.getConnection(DriverManager.java:664)
        at java.sql.DriverManager.getConnection(DriverManager.java:208)
        at groovy.sql.Sql.newInstance(Sql.java:316)
        at groovy.sql.Sql.newInstance(Sql.java:360)
        at groovy.sql.Sql.withInstance(Sql.java:382)
        at groovy.sql.Sql$withInstance.call(Unknown Source)
        at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:48)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:113)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:149)
        at com.oracle.wcsites.install.Utils.testDBConnection(Utils.groovy:369)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:93)
        at org.codehaus.groovy.runtime.callsite.StaticMetaMethodSite$StaticMetaMethodSiteNoUnwrapNoCoerce.invoke(StaticMetaMethodSite.java:151)
        at org.codehaus.groovy.runtime.callsite.StaticMetaMethodSite.callStatic(StaticMetaMethodSite.java:102)
        at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallStatic(CallSiteArray.java:56)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callStatic(AbstractCallSite.java:194)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callStatic(AbstractCallSite.java:206)
        at com.oracle.wcsites.install.Utils.validateInputs(Utils.groovy:300)
        at com.oracle.wcsites.install.Utils$validateInputs$1.call(Unknown Source)
        at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:48)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:113)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:125)
        at com.oracle.wcsites.install.InstallScript.run(InstallScript.groovy:22)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:93)
        at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:325)
        at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1210)
        at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1019)
        at org.codehaus.groovy.runtime.InvokerHelper.invokePogoMethod(InvokerHelper.java:919)
        at org.codehaus.groovy.runtime.InvokerHelper.invokeMethod(InvokerHelper.java:902)
        at org.codehaus.groovy.runtime.InvokerHelper.runScript(InvokerHelper.java:410)
        at org.codehaus.groovy.runtime.InvokerHelper$runScript.call(Unknown Source)
        at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:48)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:113)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:133)
        at com.oracle.wcsites.install.InstallScript.main(InstallScript.groovy)
Caused by: java.io.IOException: Connection reset by peer, Authentication lapse 98823 ms.
        at oracle.jdbc.driver.T4CConnection.logon(T4CConnection.java:790)
        ... 45 more
Caused by: java.io.IOException: Connection reset by peer
        at sun.nio.ch.FileDispatcherImpl.write0(Native Method)
        at sun.nio.ch.SocketDispatcher.write(SocketDispatcher.java:47)
        at sun.nio.ch.IOUtil.writeFromNativeBuffer(IOUtil.java:93)
        at sun.nio.ch.IOUtil.write(IOUtil.java:65)
        at sun.nio.ch.SocketChannelImpl.write(SocketChannelImpl.java:471)
        at oracle.net.nt.TimeoutSocketChannel.write(TimeoutSocketChannel.java:215)
        at oracle.net.ns.NIOPacket.writeToSocketChannel(NIOPacket.java:211)
        at oracle.net.ns.NIONSDataChannel.writeDataToSocketChannel(NIONSDataChannel.java:181)
        at oracle.net.ns.NIONSDataChannel.writeDataToSocketChannel(NIONSDataChannel.java:132)
        at oracle.jdbc.driver.T4CMAREngineNIO.prepareForReading(T4CMAREngineNIO.java:96)
        at oracle.jdbc.driver.T4CMAREngineNIO.unmarshalUB1(T4CMAREngineNIO.java:534)
        at oracle.jdbc.driver.T4CTTIfun.receive(T4CTTIfun.java:485)
        at oracle.jdbc.driver.T4CTTIfun.doRPC(T4CTTIfun.java:252)
        at oracle.jdbc.driver.T4CTTIoauthenticate.doOAUTH(T4CTTIoauthenticate.java:499)
        at oracle.jdbc.driver.T4CTTIoauthenticate.doOAUTH(T4CTTIoauthenticate.java:1279)
        at oracle.jdbc.driver.T4CConnection.logon(T4CConnection.java:663)
        ... 45 more

Sites installation has failed. Please check Admin Container log for details

**Comment by mriccell** [comment]
@jobsforprabu is the WLS image you are trying to run?  If the answer is yes which WLS image?  I do not see WebLogic Server in the stack trace.

**Comment by jobsforprabu** [comment]
Hi Mricell,

We are completely following the https://github.com/oracle/docker-images/tree/master/OracleWebCenterSites guide to bring up the WCS Image, i believe by default it contains the WLS image

Regards
Prabu ganesh

**Comment by escay** [comment]
I have the same exception in a completely other environment and ran into your question.
In my case I run Payara application server using an Oracle database connection pool gives me:

```
  RAR5110 : Error creating managed Connection with user and password : {0}
java.sql.SQLRecoverableException: IO Error: Connection reset by peer, Authentication lapse 158762 ms.
        at oracle.jdbc.driver.T4CConnection.logon(T4CConnection.java:794)
        at oracle.jdbc.driver.PhysicalConnection.connect(PhysicalConnection.java:688)
...
Caused by: java.io.IOException: Connection reset by peer
        at sun.nio.ch.FileDispatcherImpl.write0(Native Method)
        at sun.nio.ch.SocketDispatcher.write(SocketDispatcher.java:47)
....
```

This is probably caused by the entropy of /dev/random. I found my answer in:
https://communities.ca.com/thread/241794099-restarting-an-agent-with-the-ps-plugin

Adding '-Djava.security.egd=file:/dev/./urandom' to my Payara application server process that used the database driver helped solving this issue. 

Note if this works for you: this is not the most secure solution to use /dev/urandom.
See for more information and the consequences about dev/random problems: 
https://stackoverflow.com/questions/137212/how-to-solve-slow-java-securerandom
