### ISSUE TITLE
OracleFMWInfrstructure: AdministrationServer Container run error 

### ISSUE THREAD

**Issue by dps211** [oracle/docker-images#935]
Hi,
I am trying to run FMW Admin Server by following steps provided in https://github.com/oracle/docker-images/tree/master/OracleFMWInfrastructure

While running below command I am getting error. Command and logs are provided below. Thanks.

docker run -d -p 9001:7001 --network=InfraNET -v hostvol:/u01/oracle/user_projects --name InfraAdminContainer --env-file ./infraDomain.env.list oracle/fmw-infrastructure:12.2.1.2

/u01/oracle/container-scripts/createInfraDomain.py called with the following sys.argv array:
sys.argv[0] = /u01/oracle/container-scripts/createInfraDomain.py
sys.argv[1] = -oh
sys.argv[2] = /u01/oracle
sys.argv[3] = -jh
sys.argv[4] = /usr/java/default
sys.argv[5] = -parent
sys.argv[6] = /u01/oracle/user_projects/domains
sys.argv[7] = -name
sys.argv[8] = InfraDomain
sys.argv[9] = -user
sys.argv[10] = weblogic
sys.argv[11] = -password
sys.argv[12] = MyWLSAdminPassword
sys.argv[13] = -rcuDb
sys.argv[14] = InfraDB:1521/InfraPDB1.us.oracle.com
sys.argv[15] = -rcuPrefix
sys.argv[16] = INFRA6
sys.argv[17] = -rcuSchemaPwd
sys.argv[18] = MYDBPasswd
Error: set() failed. Do dumpStack() to see details.
Error: runCmd() failed. Do dumpStack() to see details.
Problem invoking WLST - Traceback (innermost last):
  File "/u01/oracle/container-scripts/createInfraDomain.py", line 271, in ?
  File "/u01/oracle/container-scripts/createInfraDomain.py", line 59, in createInfraDomain
  File "/u01/oracle/container-scripts/createInfraDomain.py", line 72, in createBaseDomain
  File "/tmp/WLSTOfflineIni2244714046599171538.py", line 79, in set
  File "/tmp/WLSTOfflineIni2244714046599171538.py", line 19, in command
	at com.oracle.cie.domain.script.jython.CommandExceptionHandler.handleException(CommandExceptionHandler.java:69)
	at com.oracle.cie.domain.script.jython.WLScriptContext.handleException(WLScriptContext.java:2768)
	at com.oracle.cie.domain.script.jython.WLScriptContext.runCmd(WLScriptContext.java:701)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)

com.oracle.cie.domain.script.jython.WLSTException: com.oracle.cie.domain.script.jython.WLSTException

RetVal from Domain creation 1
Domain Creation Failed.. Please check the Domain Logs

**Comment by mriccell** [comment]
@dps11 The environment variables used to configure the InfraDomain are defined in the infraDomain.env.list file. In infraDomain.env.list, replace the values for the database and WebLogic passwords.  The WebLogic passwords need to be formatted correctly please see documentation https://docs.oracle.com/middleware/1213/wls/SECMG/password_atn.htm#SECMG207.

**Comment by dps211** [comment]
@mriccell, Thanks! I have changed the password as per recommendation provided. It fixes the issue.

**Comment by dps211** [comment]
Closing this call. Thanks!
